### ISSUE TITLE
Menus disappear on Ubuntu 16.04 after closing to tray & reopening

### ISSUE THREAD

**Issue by luispabon** [nylas/N1#1992] opened 2016-04-18 11:54 UTC
Steps to reproduce: 
1. Open N1; menues appear as they should:

![image](https://cloud.githubusercontent.com/assets/6388823/14603231/7c11d2ee-0564-11e6-9bcc-888edfb29296.png)

2. Press the window close button
3. Re-open main window by clicking on the tray icon > "open inbox"
4. No menues:

![image](https://cloud.githubusercontent.com/assets/6388823/14603278/b164f84a-0564-11e6-825d-89f4a1949fc9.png)

Ubuntu 16.04
Menues on window decoration; always showing menues

**Comment by mbilker** [comment] 2016-04-19 15:03
Thanks for the report @luispabon . Is that Unity in Ubuntu 16.04? Please state the window manager used as it can, but not likely, skew reproduction.

**Comment by luispabon** [comment] 2016-04-20 13:42
Yes indeed: Ubuntu, Unity and Compiz

```
[development@localhost ~] lsb_release -rd
Description:	Ubuntu 16.04 LTS
Release:	16.04
[development@localhost ~] compiz --version
Compiz 0.9.12.2
[development@localhost ~] unity --version
unity 7.4.0
```

**Comment by tsbarnes** [comment] 2016-04-20 17:40
This is a duplicate of #911 and has been fixed upstream in Electron for a while, but for some reason the release versions of N1 aren't haven't bumped the Electron version up yet (I believe 0.36.9 was the version that introduced the fix, but stable N1 is still using 0.36.7).

**Comment by stanfieldr** [comment] 2016-04-23 22:29
Yep master is using electron 0.37.6, but the last release 0.4.25 is using electron 0.36.7. I just built from source and can confirm the menu is working in master.

**Comment by bengotow** [comment] 2016-05-03 15:36
Hey! Thanks for filing this. In `0.4.32`, we moved Electron from version `0.36.7` to `0.37.7`. I believe that should resolve this issue. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!

**Closed by bengotow** 2016-05-03 15:36 UTC
Labels: bug, done-pending-release, linux
