### ISSUE TITLE
Fastmail Login not working

### ISSUE THREAD

**Issue by lapistola** [nylas/N1#3168] opened 2017-01-17 14:26 UTC
##### Are there any related issues?

No
...

##### What operating system are you using?

OS X 10.11.6
...

##### What version of N1 are you using?

1.0.8
...

--

**Bug?**

I get an error when trying to add my Fastmail account:

> child "settings" fails because [child "imap_username" fails because ["imap_username" is required], child "name" fails because ["name" is required], child "xoauth2" fails because ["xoauth2" is required]]

##### Do you have any third-party plugins installed? If so, which ones?

No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Yes, Fastmail.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No
...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No
...

**Comment by nicknikolov** [comment] 2017-01-17 15:00
Hi, I have the exact some issue.

**Comment by hallamoore** [comment] 2017-01-17 15:20
I could use some help reproducing this! Does your email address have the "fastmail.com" domain? Are you clicking to any other account types and then using the back button before choosing fastmail?

**Comment by nicknikolov** [comment] 2017-01-17 15:28
I tried both my own domain name@domain.me and my original fastmail account name@fastmail.co.uk (they are both the same). I went straight to the Fastmail option

**Comment by hallamoore** [comment] 2017-01-17 15:41
Ah, it looks like we're trying to figure out the default IMAP settings from the email domain rather than what provider was clicked on the account type list. Working on a fix for this, but meanwhile you can add your account using the "Add Custom IMAP Account" option in the application menu.

Fastmail IMAP settings: 
    "imap_host": "imap.fastmail.com",
    "imap_port": 993,
    "imap_username": [your full email address],
    "imap_password": [your app password],
    "smtp_host": "smtp.fastmail.com",
    "smtp_port": 465,
    "smtp_username": [your full email address],
    "smtp_password": [your app password]

**Comment by nicknikolov** [comment] 2017-01-17 15:49
@hallamoore Hm, tells me Incorrect username or password, I wonder what I could be doing wrong

**Comment by nicknikolov** [comment] 2017-01-17 15:50
Oh hang on, I missed the fact it's an app password.

**Comment by nicknikolov** [comment] 2017-01-17 15:52
Ok I think It works :)Sent from Nylas Mail, the best free email app for work
          
            
            On Jan 17 2017, at 3:41 pm, hallamoore <notifications@github.com> wrote:
            
            
              Ah, it looks like we're trying to figure out the default IMAP settings from the email domain rather than what provider was clicked on the account type list. Working on a fix for this, but meanwhile you can add your account using the "Add Custom IMAP Account" option in the application menu.
Fastmail IMAP settings:
"imap_host": "imap.fastmail.com",
"imap_port": 993,
"imap_username": [your full email address],
"imap_password": [your app password],
"smtp_host": "smtp.fastmail.com",
"smtp_port": 465,
"smtp_username": [your full email address],
"smtp_password": [your app password]

**Comment by hallamoore** [comment] 2017-01-17 15:53
Great! :)

**Comment by emorikawa** [comment] 2017-01-17 16:28
Fix for this will go out today

**Closed** 2017-01-18 18:55 UTC
Labels: bug, done-pending-release
