### ISSUE TITLE
Assign labels to email addresses and other features request

### ISSUE THREAD

**Issue by scani** [nylas/N1#326] opened 2015-10-31 15:11 UTC
Hello, it would be handy to see all email addresses from all folders displayed on a list so that you can group them and assign labels to them. This way, the label automatically appears on the new email that comes from a specific address.
Next, I need to be able to choose how my name is displayed on the line with my email address - to be Anastasiia Trubitsyna (stasiascani@gmail.com) or Анастасия Трубицына (stasiascani@gmail.com) or some other way. I correspond in different languages and people expect to see my name in a language they speak.
Also, when I have more than one account in N1, I want to see which one exactly has a new message in a pop up notification or elsewhere. It can be 'for stasiascani@outlook.com' or just 'outlook'.
Thanks for your hard work N1 team! Be the best!

**Comment by jstejada** [comment] 2015-12-29 17:21
hey @scani thanks for your suggestions. Account labels has already been implemented. I'm closing this as a duplicate of other issues: #537 #741

**Closed by jstejada** 2015-12-29 17:21 UTC
