### ISSUE TITLE
Horizontal scrollbar on wide messages is not visible

### ISSUE THREAD

**Issue by Acidter** [nylas/N1#1128] opened 2016-01-24 22:40 UTC
No horizontal scrolling letters. Or make zooming letter that it contains in the right window. This is a hindrance.

**Comment by grinich** [comment] 2016-01-25 02:02
I really can't understand what you're saying here.

**Comment by Acidter** [comment] 2016-01-25 08:43
A letter can only scroll vertically, horizontally to scroll can not be.
![1](https://cloud.githubusercontent.com/assets/1911400/12546144/d027588e-c358-11e5-8cd3-7fc116266800.jpg)

**Comment by micphi** [comment] 2016-01-26 02:21
Can confirm. 

If I'm using two panel layout and the right panel isn't wide enough to display the entirety of an email's content, there is no horizontal scrollbar to allow for easy scrolling without having to resort to left/right arrow keys or window resizing.

**Comment by bengotow** [comment] 2016-01-26 19:00
Hey folks—I believe on devices with trackpads, you can pan on the trackpad to scroll the message left and right, but there's no affordance for this. I'll see if we can get it addressed in the future.

**Comment by bengotow** [comment] 2016-01-26 19:30
Merging in #785

**Comment by calope** [comment] 2016-04-07 08:38
I can reproduce the problem in the Windows version 0.4.19.
The problem is with wide images. It's reproducible both single panel as two panel Layout

**Comment by stanfieldr** [comment] 2016-04-22 04:51
As a temporary solution, you guys can click somewhere on the email and use your left and right arrow keys to scroll horizontally if you don't have a trackpad.

**Comment by jackiehluo** [comment] 2016-05-19 23:31
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!

**Closed by jackiehluo** 2016-05-19 23:31 UTC
Labels: bug, done-pending-release
