### ISSUE TITLE
Feature Request: "UNIFIED INBOXES" and give each Email-Address a specific color

### ISSUE THREAD

**Issue by ZaidoR1** [nylas/N1#1036] opened 2016-01-15 11:12 UTC
If I have multiple email accounts added then it would be very nice to have an "ALL INBOXES" folder, where all the new emails from each account appears.
To distinguish each new email, it would be nice to give each email account a specific color and show the color on each email like in the screenshot.
![2016-01-15 11_59_04-nylas](https://cloud.githubusercontent.com/assets/16700058/12351823/208840f2-bb81-11e5-9297-098a52a90063.png)

"CloudMagic" is using this technique as well. Here is a screenshot and the link (https://play.google.com/store/apps/details?id=com.cloudmagic.mail)
![2016-01-15 12_13_38-cloudmagic android-apps auf google play](https://cloud.githubusercontent.com/assets/16700058/12351882/83e8d44a-bb81-11e5-8149-60200408ffd3.png)

**Comment by mbilker** [comment] 2016-01-15 16:46
Dupe of #537

**Closed by mbilker** 2016-01-15 16:46 UTC
