### ISSUE TITLE
stuck at archiving emails

### ISSUE THREAD

**Issue by hadifarnoud** [nylas/N1#2264] opened 2016-05-18 11:04 UTC
I have 3 mailboxes 2 of which are Gmail.

I made 600 emails marked as read and archived. N1 seems to be stuck at applying those changes. 

<img width="250" alt="screen shot 1395-02-29 at 3 31 48 pm" src="https://cloud.githubusercontent.com/assets/589808/15356395/a88c9640-1d0d-11e6-91cc-b3a977b954fb.png">

I see a lot of error 400 in activity logs

<img width="543" alt="screen shot 1395-02-29 at 3 32 20 pm" src="https://cloud.githubusercontent.com/assets/589808/15356441/eb9f1426-1d0d-11e6-9aa6-f86347985956.png">

Nothing seems to work. I updated to lastest version and used a proxy.

**Comment by hadifarnoud** [comment] 2016-05-18 11:07
Spec Suite shows 138 failures at 'Bundle'

**Comment by hadifarnoud** [comment] 2016-05-19 10:42
I tried to clean-install N1 again. Used AppCleaner to remove it completely. It still comes up with my accounts and the same issue of 'applying labels'

**Comment by bengotow** [comment] 2016-05-19 19:40
Hey! Thanks for reporting this. The N1-Snoozed issue should be fixed in the next update, but I don't think it's related to this issue. I think this may be caused by the task queue being blocked by a bad object, which is another problem we fixed this week. Can you try updating to the 0.4.40 (coming this afternoon) and see if it fixes the problem?

**Comment by jackiehluo** [comment] 2016-08-22 19:05
Closing this issue for now—we've changed the way we handle syncback actions in batches.

**Closed by jackiehluo** 2016-08-22 19:05 UTC
