### ISSUE TITLE
Make thread list top-scrollable (rubber band effect)

### ISSUE THREAD

**Issue by athyuttamre** [nylas/N1#1659] opened 2016-03-12 05:08 UTC
It would be a design improvement to have the thread list top-scrollable with a rubber-band effect. Down the line, this could be augmented with pull-to-refresh, but this design update would align with user expectations about scrolling on OSX.

I'm happy to give this a shot; it'll probably required JavaScript supported scrolling, kind of like it's done by [this project](https://github.com/apeatling/web-pull-to-refresh). If someone could point me in the right direction as to what parts of the codebase I should look into, I'll get started.

- [x] Are there any related issues? 
https://github.com/nylas/N1/issues/887, but that asks for a refresh option too. I am suggesting a design update only.

- [x] What operating system are you using? 
OS X.

- [x] What version of N1 are you using? 
0.4.14

**Feature Request?**
- [x] Does this feature exist in another mail client or tool you use? 
Native clients like Mailbox and Airmail.

**Comment by jackiehluo** [comment] 2016-03-13 00:44
@athyuttamre Interesting! I do think it would be confusing to have a pull-to-refresh UI that didn't really refresh the inbox (and, as per the discussion in that issue, should never need to be refreshed manually). What did you have in mind? You probably want to look in the [thread-list](https://github.com/nylas/N1/tree/master/internal_packages/thread-list) package for the code.

**Comment by jstejada** [comment] 2016-03-13 00:46
hey everyone, this is actually a duplicate of #1188, so I'm going to merge it in. Feel free to continue the discussion there

**Closed by jstejada** 2016-03-13 00:46 UTC
