### ISSUE TITLE
After updating to 0.4.25 labels went missing

### ISSUE THREAD

**Issue by garzo** [nylas/N1#1956] opened 2016-04-13 21:18 UTC
After the latest update this morning, I had three labels go missing from N1, resulting in a few rules failing to run properly.  The labels are still present and working on the Gmail web view, but within the App they are missing.

##### Are there any related issues?

... No

##### What operating system are you using?
... OS X 10.10.5

##### What version of N1 are you using?
...  0.4.25-a22631a (0.4.25-a22631a)

--

**Bug?**
##### Do you have any third-party plugins installed?
... No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
... Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

**Comment by Tsmith18256** [comment] 2016-05-16 16:50
I also have this issue on both my computers: Work (OS X 10.11.4) and home (Windows 10). Each case is a different Gmail account and they have both lost labels.

I am updated to version 0.4.38-27d21d1 now and the issue still stands. Removing and re-adding the account did not resolve the issue; the same labels are still missing.

**Comment by thebearjew** [comment] 2016-05-17 22:26
Also experiencing this. Happy to post an image/debug logs to reproduce

**Comment by jackiehluo** [comment] 2016-10-01 06:54
Closing due to lack of information—if it's still an issue, email us at support@nylas.com!

**Closed by jackiehluo** 2016-10-01 06:54 UTC
