### ISSUE TITLE
45 GB of ShipIt updates

### ISSUE THREAD

**Issue by davidgorges** [nylas/N1#76] opened 2015-10-10 19:30 UTC
OSX told me today I was running out of disk space. I checked where this came from, and figured out it was N1!

For some reasone, I have > 200 updates in ``~/Library/Application Support/com.nylas.nylas-mail.ShipIt`` created over the last 2 days. Those are folders with names like ``update.0Msbk6w`` and similar, containing a 218MB Nylas.app.

<img width="752" alt="nylas-grand-perspective" src="https://cloud.githubusercontent.com/assets/3885619/10412913/999442e4-6f4a-11e5-91af-3ec6fc40a2d3.png">

**Comment by bengotow** [comment] 2015-10-10 21:06
Whoa. Thanks for filing this issue - we use Electron's standard "squirrel"
auto-updater, so We need to look into this and see if it's tied to any
known issues there. This definitely needs to get fixed. Stay tuned -

Ben

**Comment by bengotow** [comment] 2015-10-11 07:35
Hi David—just wanted to follow up on this. I think this is the issue: https://github.com/Squirrel/Squirrel.Mac/issues/111.

N1 currently checks for updates frequently (every 5 minutes). When we were in a private beta, we'd sometimes send out multiple updates a day so the interval made sense. It appears that Squirrel will continue downloading the update data over and over again, even if it's already got it, until you install the update.

This is pretty crazy. In the next update, we'll dial back the update interval and adjust the `auto-update-manager` so that it stops asking Squirrel to check for updates after receiving the "update is ready to install" event. That should help a good deal until the issue is fixed on their end.

**Comment by gardner** [comment] 2015-10-11 22:16
I have 316 updates in this folder.

**Comment by davidgorges** [comment] 2015-10-13 17:06
After deleting all files yesterday, N1 flooded my hard disk again today. I guess the problem is that updates do not get installed, when the app stops with the invitiation code screen. 
![bildschirmfoto 2015-10-13 um 10 03 37](https://cloud.githubusercontent.com/assets/3885619/10462108/b3657f96-7191-11e5-90ad-f2986681ac94.png)

A workaround is to install the updates manually via the menu options: ``Nylas N1 -> Restart and install updates``.

**Comment by bengotow** [comment] 2015-10-13 18:49
Hey folks—sorry for the hassle. @davidgorges I've sent you an invitation code. This issue should be resolved by https://github.com/nylas/N1/commit/7e030a1421a5cf4f103ab0e0721a9de226a48360, so after you install the `0.3.16` update it shouldn't happen again. (The app checks less frequently, and will download at most one update each time it's run.)

I'm going to go ahead and close this, but feel free to re-open if you encounter this problem after updating to 0.3.16.

**Closed by bengotow** 2015-10-13 18:49 UTC
