### ISSUE TITLE
Cannot set up SMTP credentials

### ISSUE THREAD

**Issue by lanzz** [nylas/N1#1230] opened 2016-02-08 09:48 UTC
It seems N1 is sending the _email address_ as username for SMTP authentication, even though I've supplied a _different_ username in the configuration wizard:

<img width="340" alt="screen shot 2016-02-08 at 09 42 59" src="https://cloud.githubusercontent.com/assets/130721/12882281/5f27a1c0-ce48-11e5-8ed9-5a4144e2b7e4.png">

In my server log files:

    Feb  8 10:38:00 loom dovecot: imap-login: Disconnected (auth failed, 1 attempts in 9 secs): user=<mihail.milushev@lanzz.org>, method=PLAIN, rip=x.x.x.x, lip=x.x.x.x, TLS: Disconnected, session=<xxx>

As you see, on the server side `dovecot` got a connection attempt using the _email address_ `mihail.milushev@lanzz.org` as username, but in the settings that's definitely not what I have supplied in the username field (`notarealusername` in this case). Understandably, the authentication attempt fails.

I'm running 0.3.45-3b5880e, which is what was available for download on the website; in the "Nylas N1" menu I see a grayed out "Downloading Update" item, but it just sits there, it doesn't seem to be downloading anything or trying to update itself, so if this issue has been fixed since I can't seem to find a way to update.

**Comment by mbilker** [comment] 2016-02-08 15:40
Dupe of #954

**Comment by mbilker** [comment] 2016-02-08 15:41
This is a good writeup of the issue. Could you post it in #954?

**Closed by mbilker** 2016-02-08 15:40 UTC

**Comment by lanzz** [comment] 2016-02-08 17:32
It looks like it was already described clearly enough there. I tried searching for related issues but didn't manage to find #954 :confused:
