### ISSUE TITLE
Gmail Label updates not populating correctly in N1

### ISSUE THREAD

**Issue by gcleveland** [nylas/N1#542] opened 2015-12-02 01:19 UTC
After editing labels in Gmail Gmail > Settings, the labels are creating incorrect duplicates in N1.

Use Case: In Gmail > Settings
Nested Label: [Mailbox]/Accounting
was edited to remove nesting structure.
New Label: Accounting

N1 now shows 2 labels:
[Mailbox]/Accounting
and
Accounting

**Comment by grinich** [comment] 2015-12-02 01:30
hey @bengotow could this be an issue with how we're sending the new name for nested labels via N1?

**Comment by bengotow** [comment] 2015-12-02 02:38
Hi @gcleveland — I've been able to reproduce this in my own Gmail account (I'm also a former Mailbox user ;-)) It looks like N1 receives the correct label modification events from our API, but the sidebar is not updating properly. Switching to another account and switching back updates the sidebar correctly, but it's definitely caching something it shouldn't be. Will fix.

**Comment by bengotow** [comment] 2015-12-02 03:01
Upon further investigation it looks like the sync-engine isn't consistently sending the 'delete label' delta. Cc @khamidou

**Comment by spang** [comment] 2016-01-04 21:46
Duplicate of #192.

**Closed by spang** 2016-01-04 21:46 UTC
Labels: bug, mail-sync
