### ISSUE TITLE
Multi-send takes a long time or fails / Spinning send wheel / Sends multiple copies & times on multisend

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2446] opened 2016-06-15 11:16 UTC
##### Are there any related issues?

...

##### What version of N1 are you using? Version 0.4.45-7637265 (0.4.45-7637265)...

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? 
...

**Comment by oldhickory30** [comment] 2016-06-15 11:18
Every since I updated I'm getting the spinning wheel for a long time while sending, sometimes it sends other times it generates an error, even though it appears it has sent.
![spinningwheel](https://cloud.githubusercontent.com/assets/16170272/16077864/9ae161c2-32b8-11e6-935b-fb98ad2bc65e.jpg)

**Comment by enoversum** [comment] 2016-06-15 15:34
Exact same thing here. IMAP I am using. Long it takes to send. 
And it often creates an error message:

> Error
> 
> We have trouble sending this message to all recipients. *mail@address.com* may not have received this email.
> An internal error occured.
> 
> -> Okay

**Comment by bengotow** [comment] 2016-06-15 17:48
Hey folks—thanks for reporting this. We're looking into this error on our end and we'll keep you posted.

**Comment by dregitsky** [comment] 2016-06-15 18:57
Hey @oldhickory30, @enoversum, and others seeing this issue - can you send an email to support@nylas.com mentioning the email address you're seeing this on, and referencing this github issue?

We need your email address to look up errors related to your account. We'll post updates here as we track down the root cause. Thanks!

**Comment by enoversum** [comment] 2016-06-15 19:17
@dregitsky Just did as you wished, and hope this can be solved. 
Just to add this, a recipient of multiple e-mails of mine - despite the reports that e-mails to him possibly didn't get sent - today reported in that he actually received all of my e-mails at least twice, often even thrice.

**Comment by oldhickory30** [comment] 2016-06-16 03:01
Behaved exactly like this a couple versions ago, but the problem was finally
resolved,

Hopefully it gets fixed soon, makes using N1, virtually impossible currently.

![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-
f8ac5e99-e021?r=cmVwbHkrMDBmNmJkMjA1Yzk1NjQ2OWY1NDRmMzhiMTkwZTA2OTg0MWNhY2M5Mzc2YmUxOTZiOTJjZjAwMDAwMDAxMTM3OTU2ZGQ5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 15 2016, at 11:48 am, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey folks—thanks for reporting this. We're looking into this error on our
end and we'll keep you posted.

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2446#issuecomment-226265299&r=cmVwbHkrMDBmNmJkMjA1Yzk1NjQ2OWY1NDRmMzhiMTkwZTA2OTg0MWNhY2M5Mzc2YmUxOTZiOTJjZjAwMDAwMDAxMTM3OTU2ZGQ5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/APa9IEpZi4vuotsSjnZEgzFrEs0IAqDOks5qMDrdgaJpZM4I2QBX&r=cmVwbHkrMDBmNmJkMjA1Yzk1NjQ2OWY1NDRmMzhiMTkwZTA2OTg0MWNhY2M5Mzc2YmUxOTZiOTJjZjAwMDAwMDAxMTM3OTU2ZGQ5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/APa9IF2_knrX2Oq5WkqFKVAs-4iAcKFnks5qMDrdgaJpZM4I2QBX.gif)

**Comment by enoversum** [comment] 2016-06-16 06:29
@jstejada I am not sure if the new title of this issue is right, as e-mails *do* get sent, multiple times instead. I had the occurrence that an e-mail showed still being sent while already a reply had arrived, so it seems more like N1/Nylas not realising it has successfully been sent, and then sending again.

**Comment by tongnk** [comment] 2016-06-17 04:45
Have this error message too

**Comment by jstejada** [comment] 2016-06-17 05:30
Hi @enoversum, thanks for the additional details. Can you confirm if the email actually got sent more than one time to the **_same_** recipient? Does it send to the same recipient more than once **_despite_** seeing an error message? Is this reproducible -- so, does it always send multiple times to the same recipient when you see the error message? Do you always see an error message? We're currently investigating this issue -- any additional details are appreciated. Sending now occurs per recipient in order for open and link tracking to work correctly, so as a temporary fix, if you disable open and link tracking your emails should send without delay or errors again.

**Comment by antani** [comment] 2016-06-17 07:37
Several times the delivery fails only for a few recipients.

**Comment by oldhickory30** [comment] 2016-06-17 08:11
Some times the email does not make it to the recipient,  strange though it
usually occurs only, when replying.

On Jun 16 2016, at 11:30 pm, Juan &lt;notifications@github.com&gt; wrote:  

> Hi [@enoversum](https://github.com/enoversum), thanks for the additional
details. Can you confirm if the email actually got sent more than one time to
the **_same_** recipient? Does it send to the same recipient more than once
**_despite_** seeing an error message? Is this reproducible -- so, does it
always send multiple times to the same recipient when you see the error
message? Do you always see an error message? We're currently investigating
this issue -- any additional details are appreciated. Sending now occurs per
recipient in order for open and link tracking to work correctly, so as a
temporary fix, if you disable open and link tracking your emails should send
without delay or errors again.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2446#issuecomment-226683864), or
[mute the
thread](https://github.com/notifications/unsubscribe/APa9IO5Kyft8NKQVe0vfwRxPIjNjTzdRks5qMjEOgaJpZM4I2QBX).![](https://github.com/notifications/beacon/APa9IAWrQBvvKzqYaVDhGySGtxGDXxL0ks5qMjEOgaJpZM4I2QBX.gif)

**Comment by enoversum** [comment] 2016-06-17 08:18
@jstejada I can not really tell. I only heard back from one person on a tracked e-mail that they received my e-mails multiple times. I got the warning on one message, sent one to confirm he had actually received it, and already got an answer to the one with the warning in the meantime. I am not sure how it exactly happens, as I kept N1 from updating in the office (while I had updated it at home with the problems occuring as described) or used another client to send mail.

**Comment by oldhickory30** [comment] 2016-06-17 08:25
It does appear that turning the  tracker off however I like the tracker.

Also I realized that certain emails were never sent, after re-opening N1 one
they were sent from 3 day ago. Need to get fix ASAP!

On Jun 17 2016, at 2:11 am, waj &lt;OldHickory30@zoho.com&gt; wrote:  

> Some times the email does not make it to the recipient,  strange though it
usually occurs only, when replying.

>

> On Jun 16 2016, at 11:30 pm, Juan &lt;notifications@github.com&gt; wrote:  
>

>

>> Hi [@enoversum](https://github.com/enoversum), thanks for the additional
details. Can you confirm if the email actually got sent more than one time to
the **_same_** recipient? Does it send to the same recipient more than once
**_despite_** seeing an error message? Is this reproducible -- so, does it
always send multiple times to the same recipient when you see the error
message? Do you always see an error message? We're currently investigating
this issue -- any additional details are appreciated. Sending now occurs per
recipient in order for open and link tracking to work correctly, so as a
temporary fix, if you disable open and link tracking your emails should send
without delay or errors again.

>>

>> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2446#issuecomment-226683864), or
[mute the
thread](https://github.com/notifications/unsubscribe/APa9IO5Kyft8NKQVe0vfwRxPIjNjTzdRks5qMjEOgaJpZM4I2QBX).![](https://github.com/notifications/beacon/APa9IAWrQBvvKzqYaVDhGySGtxGDXxL0ks5qMjEOgaJpZM4I2QBX.gif)

**Comment by Bergg** [comment] 2016-06-18 09:07
I am getting the error message systematically.

**Comment by jstejada** [comment] 2016-06-18 16:57
Hi all, thanks for the additional details! This is a backend problem and should be releasing the fix this Monday. Will keep you posted with any updates.

**Comment by dinhtungdu** [comment] 2016-06-19 05:00
Started using N1 today and got same error. Here is the [screenshot](http://prntscr.com/bi664t). Hope that fixed soon!

**Comment by muditgarg** [comment] 2016-06-22 04:55
@jstejada was there an update released?

**Comment by jstejada** [comment] 2016-06-22 06:41
Hi everyone, we shipped a fix for this issue to our backend today, so it should be fixed! Let me know if you continue to see errors. Thanks!

**Comment by enoversum** [comment] 2016-06-22 07:18
@jstejada Does it mean we will receive a new release, or you rather changed something on the sync engine, so no update needed? Again, this was introduced with the latest version, previous version still worked well though.

**Comment by jstejada** [comment] 2016-06-22 07:18
@enoversum , you don't need to wait for a new release of N1 -- it should be working correctly now without updating N1

**Comment by enoversum** [comment] 2016-06-22 07:27
@jstejada Thanks, will try out enabling tracking again :).

**Comment by oldhickory30** [comment] 2016-06-22 07:35
Still taking a long time, relatively to send, with tracking
enabled,![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-
32311bd1-4312?r=cmVwbHkrMDBmNmJkMjAzNWRmZjBiMWY5MjkzM2VlMTQ0ODQ5MmFiMjMxOThlZDAyNjU1OWU2OTJjZjAwMDAwMDAxMTM4MWY1MzA5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 22 2016, at 12:41 am, Juan &lt;notifications@github.com&gt; wrote:  

> Hi everyone, we shipped a fix for this issue to our backend today, so it
should be fixed! Let me know if you continue to see errors. Thanks!

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2446#issuecomment-227657011&r=cmVwbHkrMDBmNmJkMjAzNWRmZjBiMWY5MjkzM2VlMTQ0ODQ5MmFiMjMxOThlZDAyNjU1OWU2OTJjZjAwMDAwMDAxMTM4MWY1MzA5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/APa9IPQQKfrT40Du-
UdAYcifB3RCpmJaks5qONkwgaJpZM4I2QBX&r=cmVwbHkrMDBmNmJkMjAzNWRmZjBiMWY5MjkzM2VlMTQ0ODQ5MmFiMjMxOThlZDAyNjU1OWU2OTJjZjAwMDAwMDAxMTM4MWY1MzA5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/APa9IELGuVtr0ZbT0hwxtqZ5p2ubeM4Tks5qONkwgaJpZM4I2QBX.gif)

**Comment by oldhickory30** [comment] 2016-06-22 08:15
Just to clarify, N1 is hanging up when replying, if its a new email, it goes
right through w/ tracking
enabled.![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-
96f71ff9-0add?r=cmVwbHkrMDBmNmJkMjAzNWRmZjBiMWY5MjkzM2VlMTQ0ODQ5MmFiMjMxOThlZDAyNjU1OWU2OTJjZjAwMDAwMDAxMTM4MWY1MzA5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 22 2016, at 1:35 am, waj &lt;OldHickory30@zoho.com&gt; wrote:  

> Still taking a long time, relatively to send, with tracking enabled,

>

> On Jun 22 2016, at 12:41 am, Juan &lt;notifications@github.com&gt; wrote:  
>

>

>> Hi everyone, we shipped a fix for this issue to our backend today, so it
should be fixed! Let me know if you continue to see errors. Thanks!

>>

>> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2446#issuecomment-227657011&r=cmVwbHkrMDBmNmJkMjAzNWRmZjBiMWY5MjkzM2VlMTQ0ODQ5MmFiMjMxOThlZDAyNjU1OWU2OTJjZjAwMDAwMDAxMTM4MWY1MzA5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/APa9IPQQKfrT40Du-
UdAYcifB3RCpmJaks5qONkwgaJpZM4I2QBX&r=cmVwbHkrMDBmNmJkMjAzNWRmZjBiMWY5MjkzM2VlMTQ0ODQ5MmFiMjMxOThlZDAyNjU1OWU2OTJjZjAwMDAwMDAxMTM4MWY1MzA5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/APa9IELGuVtr0ZbT0hwxtqZ5p2ubeM4Tks5qONkwgaJpZM4I2QBX.gif)

**Comment by oldhickory30** [comment] 2016-06-22 14:30
Its also hanging up when forwarding a message and WILL NOT complete, forcing
me to restart N1, looks like its still
broke!![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-
974a94ce-c693?r=cmVwbHkrMDBmNmJkMjAzNWRmZjBiMWY5MjkzM2VlMTQ0ODQ5MmFiMjMxOThlZDAyNjU1OWU2OTJjZjAwMDAwMDAxMTM4MWY1MzA5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 22 2016, at 2:15 am, waj &lt;OldHickory30@zoho.com&gt; wrote:  

> Just to clarify, N1 is hanging up when replying, if its a new email, it goes
right through w/ tracking enabled.

>

> On Jun 22 2016, at 1:35 am, waj &lt;OldHickory30@zoho.com&gt; wrote:  
>

>

>> Still taking a long time, relatively to send, with tracking enabled,

>>

>> On Jun 22 2016, at 12:41 am, Juan &lt;notifications@github.com&gt; wrote:  
>

>>

>>> Hi everyone, we shipped a fix for this issue to our backend today, so it
should be fixed! Let me know if you continue to see errors. Thanks!

>>>

>>> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2446#issuecomment-227657011&r=cmVwbHkrMDBmNmJkMjAzNWRmZjBiMWY5MjkzM2VlMTQ0ODQ5MmFiMjMxOThlZDAyNjU1OWU2OTJjZjAwMDAwMDAxMTM4MWY1MzA5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/APa9IPQQKfrT40Du-
UdAYcifB3RCpmJaks5qONkwgaJpZM4I2QBX&r=cmVwbHkrMDBmNmJkMjAzNWRmZjBiMWY5MjkzM2VlMTQ0ODQ5MmFiMjMxOThlZDAyNjU1OWU2OTJjZjAwMDAwMDAxMTM4MWY1MzA5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/APa9IELGuVtr0ZbT0hwxtqZ5p2ubeM4Tks5qONkwgaJpZM4I2QBX.gif)

**Comment by oldhickory30** [comment] 2016-06-22 14:40
Its actually hanging up all over again, not just forwarding, with tracking on.

On Jun 22 2016, at 8:31 am, waj &lt;OldHickory30@zoho.com&gt; wrote:  

> Its also hanging up when forwarding a message and WILL NOT complete, forcing
me to restart N1, looks like its still broke!

>

> On Jun 22 2016, at 2:15 am, waj &lt;OldHickory30@zoho.com&gt; wrote:  
>

>

>> Just to clarify, N1 is hanging up when replying, if its a new email, it
goes right through w/ tracking enabled.

>>

>> On Jun 22 2016, at 1:35 am, waj &lt;OldHickory30@zoho.com&gt; wrote:  
>

>>

>>> Still taking a long time, relatively to send, with tracking enabled,

>>>

>>> On Jun 22 2016, at 12:41 am, Juan &lt;notifications@github.com&gt; wrote:  
>

>>>

>>>> Hi everyone, we shipped a fix for this issue to our backend today, so it
should be fixed! Let me know if you continue to see errors. Thanks!

>>>>

>>>> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2446#issuecomment-227657011), or
[mute the thread](https://github.com/notifications/unsubscribe
/APa9IPQQKfrT40Du-
UdAYcifB3RCpmJaks5qONkwgaJpZM4I2QBX).![](https://github.com/notifications/beacon/APa9IELGuVtr0ZbT0hwxtqZ5p2ubeM4Tks5qONkwgaJpZM4I2QBX.gif)

**Comment by oldhickory30** [comment] 2016-06-23 13:36
Still having issues with tracking on, lagging will not send and / or duplicates outgoing email! Is it still being  worked on?

**Comment by dcrystalj** [comment] 2016-06-24 08:13
I have still this bug. People wants to kill me. It just keeps sending.

**Comment by emorikawa** [comment] 2016-07-06 18:44
This appears to be related to bugs when to sending to multiple people. We're actively investigating this on the API side and will post when we have updates. Here. Getting additional reports from @grinich as well.

**Comment by jackiehluo** [comment] 2016-07-06 19:26
Another incidence: https://nylas.zendesk.com/agent/tickets/3750

**Comment by oldhickory30** [comment] 2016-07-06 19:29
The problem seems to be corrected on my end, no delays anymore when sending
with tracking on.![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu
/local-
1e501bbb-b412?r=cmVwbHkrMDBmNmJkMjA3YjdjYmNmMzgxMzNmYTk2ODBmZmVlMzdkNDliYTg5NDNkNDU2YTI4OTJjZjAwMDAwMDAxMTM5NTFkOGM5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=)

On Jul 6 2016, at 1:27 pm, Jackie Luo &lt;notifications@github.com&gt; wrote:  

> Another incidence:
[https://nylas.zendesk.com/agent/tickets/3750](https://nylas.zendesk.com/agent/tickets/3750&r=cmVwbHkrMDBmNmJkMjA3YjdjYmNmMzgxMzNmYTk2ODBmZmVlMzdkNDliYTg5NDNkNDU2YTI4OTJjZjAwMDAwMDAxMTM5NTFkOGM5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=)

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2446#issuecomment-230880362&r=cmVwbHkrMDBmNmJkMjA3YjdjYmNmMzgxMzNmYTk2ODBmZmVlMzdkNDliYTg5NDNkNDU2YTI4OTJjZjAwMDAwMDAxMTM5NTFkOGM5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/APa9IAeP9nNh85W9G7HGURrSMgWxYwP9ks5qTAGMgaJpZM4I2QBX&r=cmVwbHkrMDBmNmJkMjA3YjdjYmNmMzgxMzNmYTk2ODBmZmVlMzdkNDliYTg5NDNkNDU2YTI4OTJjZjAwMDAwMDAxMTM5NTFkOGM5MmExNjljZTA5OGY3OTM4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/APa9IOLwD7Dg5n-0AXgUbXCGo8KdS8vLks5qTAGMgaJpZM4I2QBX.gif)

**Comment by jackiehluo** [comment] 2016-07-06 19:29
Another incidence: https://nylas.zendesk.com/agent/tickets/3707

**Comment by jackiehluo** [comment] 2016-07-28 23:43
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!

**Closed by jackiehluo** 2016-07-28 23:43 UTC
Labels: bug, done-pending-release, mail-sync, needs-attention
