### ISSUE TITLE
Spell check always corrects in English

### ISSUE THREAD

**Issue by iammikey1** [nylas/N1#535] opened 2015-12-01 21:25 UTC
Hi!

I have a problem with the spelling: my language is set as spanish but it automatically turn on the corrector in english so it appears as wrong every single word.

![captura de pantalla 2015-12-01 a las 22 21 11](https://cloud.githubusercontent.com/assets/16107849/11514693/26bbaa10-987a-11e5-9e32-ce81006b422c.png)

**Comment by bengotow** [comment] 2015-12-01 21:56
Hi @iammikey1 thanks for filing this. I've confirmed that right now, spellcheck is always in English.

**Comment by iammikey1** [comment] 2015-12-01 22:00
And there´s no way to change it or disable it ?

> On Dec 1 2015, at 10:56 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi [@iammikey1](https://github.com/iammikey1) thanks for filing this. I've
confirmed that right now, spellcheck is always in English.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/535#issuecomment-161108087).![](https://github.com/notifications/beac
on/APXJSY6aEPt4H68mfa4NdqbimXN6ygAZks5pLg8BgaJpZM4GspK8.gif)

**Comment by mbilker** [comment] 2015-12-01 22:24
Isn't the spellcheck engine derived from Atom?

**Comment by bengotow** [comment] 2015-12-10 00:33
This should be fixed in 9af40833accdc2beddf6fecad0a3e5261cfaffa9 - we use the same `node-spellcheck` module that Atom does, but we weren't initializing it with the user's current language.

**Closed by bengotow** 2015-12-10 00:33 UTC
Labels: bug, i18n

**Comment by mbilker** [comment] 2015-12-10 05:40
Hmm. The spec tests are failing under Linux with this merged in. My build is https://travis-ci.org/mbilker/N1/builds/95960482. I know running under Trusty does not change anything. My Arch Linux very is also very similar.

**Comment by koenpunt** [comment] 2015-12-21 09:49
Is there a possibility to make the spelling language differ from the system language? Because I'm having my Mac's language set to English, but I mostly e-mail in Dutch..

**Comment by Muurtegel** [comment] 2015-12-21 13:53
I'm in a similar situation as @koenpunt. My Mac's language is set to English, but I send emails in several languages. Most apps seem to recognise what language I'm typing in and adjust the spelling check to that language.

**Comment by mbilker** [comment] 2015-12-22 03:04
@Muurtegel Unfortunately for your case, N1 uses `node-spellchecker` which uses OS X's spellchecker extension, but it defaults to the primary language that is in `navigator.language`.

**Comment by bartn** [comment] 2016-01-06 10:26
Just as @koenpunt and @Muurtegel I am struggling with the spell-checker for multi-languages.

**Comment by jaap** [comment] 2016-01-06 11:32
Same issue as @bartn, @koenpunt and @Muurtegel, setting the spell-check language within N1 would be great.

**Comment by mbilker** [comment] 2016-01-06 17:22
@jaap the spellchecker on Windows and OS X uses native API's to get spellchecking done. Multi-language support is not available yet.

**Comment by lmartins** [comment] 2016-03-12 14:00
I see this is marked as fixed although im still having the problem in the latest release. Only me?

**Comment by Muurtegel** [comment] 2016-03-14 08:49
Apparently it's fixed as in that it spell-checks in your system's language. So you could change the system language to change the spellcheck.

Ideally, we would like Multi-language support and some language detection.

**Comment by lmartins** [comment] 2016-03-14 09:25
Ok, although that is hardly a definite solution. I have my system in English and spend all day writing both in Portuguese and English languages, so it should detect the language or if not possible at least allow the user to pick the language.

**Comment by Muurtegel** [comment] 2016-03-14 09:29
I feel your pain, I write in Dutch and English. I hope there will be a good solution at some point.

**Comment by koenpunt** [comment] 2016-03-14 09:32
If it would let you pick out the different navigator languages, as `navigator.languages` in Chrome returns an array of all languages defined in the settings. Although in Electron it's empty (`[]`), which is probably related to this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=570349#c4

Although we would still need an interface for switching the language.

**Comment by nlenkowski** [comment] 2016-04-15 11:38
This issue should probably not be closed.

I'm in a similar frustrating situation here. I write in both Spanish and English daily, my OS language is English. Nylas refuses to spellcheck in Spanish consistently and provides no way to manually specify the message language. I don't have this problem in other email applications (Mail, Airmail, Polymail, etc) they auto-detect the language as I write. I'm on OS X El Capitan running Nylas 0.4.25-a22631a, the latest release to date.

**Comment by lmartins** [comment] 2016-04-15 11:42
Theres a dedicated issue to this problem https://github.com/nylas/N1/issues/1392, that's why this one is closed:

**Comment by nlenkowski** [comment] 2016-04-15 11:59
Thanks, didn't see this was a duplicate of #1392. Glad to see work on the issue is ongoing.
