### ISSUE TITLE
Difficulty inputting Chinese characters

### ISSUE THREAD

**Issue by brettgerry** [nylas/N1#91] opened 2015-10-15 01:15 UTC
A user is reporting that Chinese characters cannot be input because while typing, they are "interrupted".
See this for the see what is happening:
https://uploads.intercomcdn.com/i/o/2451028/fcfba025c9d47feefe812307/gif.gif

**Comment by jacobbubu** [comment] 2015-10-22 06:06
Yes. I've encountered the same thing.

**Comment by emorikawa** [comment] 2015-10-23 22:35
Duplicate of #62

**Closed by emorikawa** 2015-10-23 22:35 UTC
Labels: bug
