### ISSUE TITLE
disconnect

### ISSUE THREAD

**Issue by dHRUSHIT** [nylas/N1#2466] opened 2016-06-16 12:11 UTC
##### Are there any related issues?

...
No. I searched with keywords - Outlook,Disconnect,Reconnect, Outlook disconnect but could not find anything relevant
##### What operating system are you using?
...
Windows 10
##### What version of N1 are you using?
...
0.4.45
--

**Bug?**
##### Do you have any third-party plugins installed?
...
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
Yes Outlook.
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
Yes 
![disconnect_error](https://cloud.githubusercontent.com/assets/6815551/16116257/777d5024-33e9-11e6-8e65-616092360ba5.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by Omeryl** [comment] 2016-06-16 20:31
Hey @dHRUSHIT,

There's a few ways you can go about fixing this: 
1. Delete and readd the account in your preferences in N1.
2. If that fails to work, close the entire N1 mail client and remove your cache by deleting `.nylas` in your home folder. 
2. If all else fails, it's probably easiest to email support@nylas.com from the email in question. It looks to be a Sync Engine-related issue.

**Comment by jackiehluo** [comment] 2016-07-07 18:06
Going to close this issue for now, since it's not a bug for us to fix—if you didn't email support@nylas.com, feel free to do that!

**Closed by jackiehluo** 2016-07-07 18:06 UTC
Labels: mail-sync, windows
