### ISSUE TITLE
24 hour Time/Date Format

### ISSUE THREAD

**Issue by benjamindahl** [nylas/N1#1879] opened 2016-04-05 06:51 UTC
**Feature Request**
I'd like to view time and date in localized format (German) as 24 hours view like it is standard in OS X

e.g. 
5th of April 9pm would look like this
5.4.2016  20:52

cheers 

Benny

**Comment by mbilker** [comment] 2016-04-05 16:12
Dupe of #682

**Closed** 2016-04-05 16:12 UTC
Labels: duplicate
