### ISSUE TITLE
Install RPM on Fedora 23: Can't find the Electron executable

### ISSUE THREAD

**Issue by martinoj2009** [nylas/N1#1169] opened 2016-01-30 23:54 UTC
I installed the RPM for N1, but when trying to run the program I get the following error:

> Can't find the Electron executable at /usr/local/bin/electron/electron. Be sure you have run script/bootstrap first from /usr/local/bin or set the ELECTRON_PATH environment variable.

I made sure I had npm and electron installed. I then added electron to /usr/local/bin/electron/electron, but then electron returned an error saying that wasn't a valid electron program. 

I'm on Fedora 23.

**Comment by martinoj2009** [comment] 2016-01-31 00:13
So this only happens when I run the command nylas, however, when I open the icon it works fine.

**Comment by mbilker** [comment] 2016-01-31 02:19
Dupe of #411

**Closed by mbilker** 2016-01-31 02:19 UTC
