### ISSUE TITLE
Trash label applied to drafts

### ISSUE THREAD

**Issue by vaanijyadmin** [nylas/N1#708] opened 2015-12-15 02:17 UTC
Trash label is tagged on to the thread even after draft is deleted and every draft conversation is also label  as Trash

**Comment by jstejada** [comment] 2015-12-19 01:03
hey @vaanijyadmin -- so you mean that the thread gets labeled as Trash after you've deleted a draft?

**Comment by vaanijyadmin** [comment] 2015-12-19 22:56
The entire thread is labeled as Trash when there is a associated draft.In gmail its labelled as Inbox but in N1 its labeled as Trash and Inbox
<img width="218" alt="screen shot 2015-12-19 at 5 55 33 pm" src="https://cloud.githubusercontent.com/assets/9113357/11915560/c3b2e59c-a679-11e5-8c2a-ee2cee08411d.png">
<img width="275" alt="screen shot 2015-12-19 at 5 39 18 pm" src="https://cloud.githubusercontent.com/assets/9113357/11915562/c69ded92-a679-11e5-9a3e-cebba600e873.png">

**Comment by grinich** [comment] 2016-01-25 23:24
dupe of #1135

**Closed by grinich** 2016-01-25 23:24 UTC
