### ISSUE TITLE
Spams in Sent [GMAIL]

### ISSUE THREAD

**Issue by akshar26** [nylas/N1#973] opened 2016-01-12 16:00 UTC
Spam messages are being shown up in Sent. Also, some old deleted sent messages are shown up in Sent even if my Sent is completely empty in Gmail.

**Comment by mbilker** [comment] 2016-01-12 20:09
Dupe of #409

**Comment by grinich** [comment] 2016-01-25 23:25
dupe of #1135

**Closed** 2016-01-25 23:25 UTC
Labels: duplicate
