### ISSUE TITLE
Search does not work (No search results)

### ISSUE THREAD

**Issue by ewiggin** [nylas/N1#750] opened 2015-12-18 08:05 UTC
I can't search anything. My email threads all are organized on folders, but i can't search an email on Inbox.

![image](https://cloud.githubusercontent.com/assets/657517/11892216/41700574-a566-11e5-920e-c4f9c821ff65.png)

![image](https://cloud.githubusercontent.com/assets/657517/11892211/2dc6ae10-a566-11e5-8b2c-9ad825f0b8a1.png)

**Comment by jstejada** [comment] 2015-12-18 23:00
hi @ewiggin -- thanks for reporting this. Could you open the DevTools and pull the logs name out of the Console tab and send that?

**Comment by lavoiekeven** [comment] 2015-12-21 15:57
I have the same problem. 

Lastest version available: 0.3.32

![capture_d ecran_122115_105536_am](https://cloud.githubusercontent.com/assets/16387206/11934629/5e67b97a-a7d1-11e5-80b6-dba72effadd0.jpg)

**Comment by xaph** [comment] 2015-12-24 09:59
same here with Version 0.3.32-b11131d on macos.

**Comment by enoversum** [comment] 2016-01-05 08:02
I think he is referring to search not working. I didn’t find the thread here anymore, but it had been reported and confirmed already weeks ago. I can confirm that on the Windows version with two IMAP accounts, search still does not work, even for recent mail. It is just not displaying any results.

**Comment by kamiller42** [comment] 2016-01-08 15:06
If I could cast all my votes for this, I would. Searching is one of the three primary functions of an email app: send, receive, search. No working search is severely crippling the app for me.

**Comment by ewiggin** [comment] 2016-01-13 13:38
@jstejada 0.3.36 on Windows 10. Today update the app but not work...

**Comment by PhoenixFlying** [comment] 2016-01-13 14:05
@jstejada me too(0.3.36 on Ubuntu 14.04 64bits)

take 'firefox' as an example here:
![selection_003](https://cloud.githubusercontent.com/assets/12250549/12296263/93f1964c-ba41-11e5-9b26-a6c30b6345bd.png)

![selection_004](https://cloud.githubusercontent.com/assets/12250549/12296276/acada798-ba41-11e5-9983-a136e468de37.png)

**Comment by benjamingarcia** [comment] 2016-01-14 09:49
@jstejada me too. I'm on _Mac OS ElCapitan_ with N1 version **0.3.43-b95f1f7** :cry: . It's the only problem for me to use only N1.

**Comment by sanderploegsma** [comment] 2016-01-16 15:31
Same for me. The search field actually auto completes my search for me, but when I select that proposed search query, it won't find anything. :confused:

**Comment by simonfrom44** [comment] 2016-01-18 14:50
Agree with previous comments, searching is one of the primary functions of an email app.

**Comment by kristiankim** [comment] 2016-01-20 22:05
Ah, I just reported the same issue. Can't search IMAP emails which preventing me from using this otherwise lovely app.

**Comment by djutopie** [comment] 2016-01-25 17:09
Same here, can't search IMAP email...

**Comment by bonaldi** [comment] 2016-01-26 16:09
Seeing the same thing here. Potentially relevant part of my logs, which makes it look like it's timing out trying to talk to api.nylas.com:

```
{"host":"blahblah.local",
"timestamp":"2016-01-26T15:58:35.267Z",
"payload": {"error": {"stack":"Error: ETIMEDOUT\n    at /Users/SNIP/Desktop/Nylas N1.app/Contents/Resources/app.asar/node_modules/request/request.js:761:15","message":"ETIMEDOUT",
"code":"ETIMEDOUT",
"connect":false},
"response":{"statusCode":0},"requestOptions":{"method":"GET","path":"/threads/search?q=Pies","accountId":"blahblah","json":true,"returnsModel":false,"url":"https://api.nylas.com/threads/search?q=Pies","timeout":15000,"auth":{"user":"blahblahblah","pass":"","sendImmediately":true},"startTime":1453823899952},"statusCode":0,"name":"APIError","message":"Error: ETIMEDOUT"}}
```

**Comment by zlangbert** [comment] 2016-01-29 02:55
+1

**Comment by jstejada** [comment] 2016-02-01 19:47
Hi all, it seems that this issue is occurring only with IMAP accounts? Is anyone experiencing this issue with another type of account, like Gmail or Exchange? Our current search uses whatever search service the imap provider for the account provides, so it may be the case that it is very slow or nonexistent. 

I'm labeling as mail-sync so we can double check with our back-end team.

**Comment by bonaldi** [comment] 2016-02-01 20:13
Happens for me with an Exchange 2010 account too

**Comment by zlangbert** [comment] 2016-02-01 20:14
@jstejada I have Gmail and a GoDaddy based IMAP account set up. Gmail search works great, IMAP doesn't work at all. Hope that helps

**Comment by enoversum** [comment] 2016-02-01 20:21
@jstejada It's IMAP only in my case, but can report in that other clients in the past and still presently are able to search and find e-mail further than the local cache reaches,on the very same accounts and underlying software on the server.

**Comment by sanderploegsma** [comment] 2016-02-01 20:56
For me it actually is gmail. It seems like the search function is only able to find recent e-mails, everything older than a certain period of time, like 30 days or something doesn't come up.

**Comment by aw3stin1** [comment] 2016-02-03 01:06
+1

**Comment by ewiggin** [comment] 2016-02-08 07:19
I test N1 with a company IMAP account.

**Comment by bw1984** [comment] 2016-02-08 23:53
i've got exactly the same issue. searching on IMAP brings back no results (despite autosuggest working). ive got the latest version (just updated today) on el capitan. mine has never worked since i got it last year

**Comment by FromBabylon** [comment] 2016-02-10 08:27
Same issue here. Autosuggest works but search brings no results

OS X El Capitan but got same problem on 10.10 before

**Comment by dcrystalj** [comment] 2016-02-11 21:44
imap search is not working on version 0.4.5

**Comment by matthewcrist** [comment] 2016-02-19 19:46
Same here. Search not working on 0.4.5-b0ec335.

**Comment by JoanPlume** [comment] 2016-02-20 20:27
What is the solution !!

**Comment by ajanssens** [comment] 2016-02-23 13:38
+1

**Comment by robr3rd** [comment] 2016-02-24 16:29
Also affected.

OS X El Capitan (v10.11.3) / Nylas N1 (v0.4.5-b0ec335 [latest]) / Exchange account

**Comment by FlorianBrinkmann** [comment] 2016-02-24 16:32
I have the same problem on Windows 10 with N1 0.4.5, I use IMAP accounts.

**Comment by saqebakhter** [comment] 2016-02-24 17:57
Same issue here

**Comment by kristianlam** [comment] 2016-02-26 04:30
Same issue here.

Version 0.4.9-575c091 (0.4.9-575c091)
OS X 10.11.4 Beta (15E49a)

**Comment by blakkheimgw** [comment] 2016-02-26 16:04
Same problem here, with an IMAP account, on Linux OS. Today's update, 0.4.9-575c091 didn't fix it.

The bug report is 2 months old and no one is assigned to...

**Comment by lmartins** [comment] 2016-02-27 15:23
I've tested with both IMAP and iClod accounts with the same result, zero results. It is strange considering the search box suggestions are actually quite good.

**Comment by Wikunia** [comment] 2016-02-28 08:49
Same here
v0.4.10 on Archlinux

**Comment by tartley** [comment] 2016-02-28 22:33
On N1 I sometimes get no search results at all (when I know there should be some), depending on what my search term is. Retrying a search with no results will reliably continue to return no results.

The same search from Thunderbird, and from a webmail UI (https://webmail.webfaction.com) finds everything fine.

I'm unsure precisely when Thunderbird does a server-side search versus searching local files, but I'm guessing the webmail UI must be using server-side search?

This is on an IMAP account.

The search term is a single word ("Sophie"), which is both the name part of a "From" contact, and the email address itself starts "Sophie.Tyler@..." and it is present in the body of the email.

When I'm typing "Sophie" in the N1 search box, I get some completion options, one of which is the email address of the Sophie I'm looking for ("Sophie.Tyler@..."). If I select that option and search, I still get no results.

**Comment by robr3rd** [comment] 2016-02-29 00:40
Latest update is still broken on OS X and Arch Linux with both Exchange and IMAP accounts

As others have mentioned, the autocompletion results are actually *perfect* in every way and impressively quick -- I cannot understate how accurate and quick the autocompletions are vs every other client.

@jstejada As I just happened to see you edit the title, if you happen to swing by this area again, please consider removing "with IMAP accounts" from the subject line since Exchange issues have also been reported by at least @bonaldi  (https://github.com/nylas/N1/issues/750#issuecomment-175094147) and myself.

For that matter, the whole title is currently a misnomer. "Search doesn't work" would be most accurate due to:

1. It affects both IMAP and Exchange
1. "is very slow," isn't something that has actually been reported by anybody here (that I've noticed anyway)

**Comment by Bergg** [comment] 2016-02-29 10:46
N1 on Fedora this only affects IMAP. Search on Exchange works well.

**Comment by janhuntjens** [comment] 2016-03-01 09:34
Also affected here. Takes a long time and always says 'Nothing to display.'. Regardless of the search term entered in my experience.

**Comment by robr3rd** [comment] 2016-03-02 14:09
UPDATE: Just tried this again this morning and it works! (on OS X El Capitan 10.11.3 using Exchange and up-to-date Nylas v0.4.10-4e3595b)

I did not update Nylas at all for this, so I wonder...did you guys do some magic with an intermediary syncing engine or something?

To be clear:

- Search suggestions work (still)
- Selecting one of the suggestions (which searches for the subject as a quoted string) works now
- Searching a manual query (i.e. *not* selecting a suggestion) also works now.

So, it would seem that all common styles of search are running smoothly.

**Comment by saqebakhter** [comment] 2016-03-02 14:16
Not working for me still - just tried it

> On Mar 2 2016, at 9:09 am, Robert Robinson &lt;notifications@github.com&gt;
wrote:  

>

> UPDATE: Just tried this again this morning and it works! (on OS X El Capitan
10.11.3 using Exchange and up-to-date Nylas v0.4.10-4e3595b)

>

> I did not update Nylas at all for this, so I wonder...did you guys do some
magic with an intermediary syncing engine or something?

>

> To be clear:

>

>   * Search suggestions work (still)

>   * Selecting one of the suggestions (which searches for the subject as a
quoted string) works now

>   * Searching a manual query (i.e. _not_ selecting a suggestion) also works
now.

>

> So, it would seem that all common styles of search are running smoothly.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/750#issuecomment-191250389).![](https://github.com/notifications/beac
on/AANq2SmptiNzvjHLA2s218XcNFoVNCyvks5ppZoagaJpZM4G39fv.gif)

**Comment by lmartins** [comment] 2016-03-02 14:19
Same here, still the same unfortunately.

> On Mar 2 2016, at 2:17 pm, saqebakhter &lt;notifications@github.com&gt;
wrote:  
Not working for me still - just tried it  
  
&gt; On Mar 2 2016, at 9:09 am, Robert Robinson
&amp;lt;notifications@github.com&amp;gt;  
wrote:  
  
&gt;  
  
&gt; UPDATE: Just tried this again this morning and it works! (on OS X El
Capitan  
10.11.3 using Exchange and up-to-date Nylas v0.4.10-4e3595b)  
  
&gt;  
  
&gt; I did not update Nylas at all for this, so I wonder...did you guys do
some  
magic with an intermediary syncing engine or something?  
  
&gt;  
  
&gt; To be clear:  
  
&gt;  
  
&gt; * Search suggestions work (still)  
  
&gt; * Selecting one of the suggestions (which searches for the subject as a  
quoted string) works now  
  
&gt; * Searching a manual query (i.e. _not_ selecting a suggestion) also works  
now.  
  
&gt;  
  
&gt; So, it would seem that all common styles of search are running smoothly.  
  
&gt;  
  
&gt; —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N  
1/issues/750#issuecomment-191250389).![](https://github.com/notifications/beac  
on/AANq2SmptiNzvjHLA2s218XcNFoVNCyvks5ppZoagaJpZM4G39fv.gif)  
  

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/750#issuecomment-191253326).![](https://github.com/notifications/beac
on/AAJRrRG6ExWFZBoHRXKGbCOQ0eYPrMmfks5ppZvbgaJpZM4G39fv.gif)

**Comment by enoversum** [comment] 2016-03-02 14:59
+1 still not working on IMAP.

**Comment by Bergg** [comment] 2016-03-02 15:01
Still working on exchange, still not working on imap.

**Comment by aminasoode** [comment] 2016-03-05 13:42
+1

**Comment by arslankhalidch** [comment] 2016-03-07 15:23
not working on anything, gmail, exchange, imap

**Comment by shravanpn7** [comment] 2016-03-07 23:39
Search works on Gmail but not on exchange account. I am using Version 0.4.10-4e3595b (0.4.10-4e3595b).

**Comment by rtaibah** [comment] 2016-03-08 09:21
Not working here either. Using IMAP here Version 0.4.10-4e3595b (0.4.10-4e3595b)

**Comment by robr3rd** [comment] 2016-03-08 17:49
UPDATE: UPDATE: Annnnnnd it's broken again. Haven't changed anything. It worked every single day between my last update (https://github.com/nylas/N1/issues/750#issuecomment-191250389) and yesterday, only now it is no longer working.

**Comment by lmartins** [comment] 2016-03-12 10:08
Just to confirm that after this week's update the issue still present.

**Comment by howardroark** [comment] 2016-03-17 22:46
Searching IMAP accounts has never worked for me since using N1.  Works for gmail just fine though.

**Comment by olivierlacan** [comment] 2016-03-19 22:08
Since `0.4.16-8cb7748` update this issue appears resolved for me.

**Comment by kristianlam** [comment] 2016-03-20 00:10
Running Version 0.4.16-8cb7748 and still no luck.

**Comment by FlorianBrinkmann** [comment] 2016-03-20 09:54
Can confirm that the issue still exists

**Comment by pipa18** [comment] 2016-03-23 11:51
Yes, still the same.

**Comment by robr3rd** [comment] 2016-03-26 14:57
March 25th update (version 0.4.19-d41e72c) resolved this for me.

I can now search on:
- "Message Contains: "
- "Threads" (subject line)
- "People" (sender/recipient email address)

At first, People was throwing transient Exchange errors, but after trying the others again and coming back around to it after a while, it eventually worked consistently.

**Comment by lmartins** [comment] 2016-03-26 18:35
For me is still the same, doesn't work. I haven't seen anything search related in the changelog so my guess is nothing changed there, although considering the issue history it seems to an intermittent problem for some.

**Comment by enoversum** [comment] 2016-03-27 19:54
Same old, same old on my IMAP accounts. Not even finding messages that are definitely in my local cache which I can see in my list of e-mails.

**Comment by howardroark** [comment] 2016-03-27 20:33
I suspect part of the problem is that N1 does not search locally. IMAP has never worked for me either.  It may require a specific IMAP configuration that many hosts lack.  

Sitting behind N1 is Nylas, which is meant to be a middleware layer translates the multitude of email services out there into universal context.  I think Nylas is meant to be the core sellable product and N1 is a way to draw attention that way and work out the bugs.

At least that is how I understand the ecosystem.

**Comment by entreprenik2** [comment] 2016-03-28 08:49
So here's what I don't get... Why aren't results that are in the inbox (that you can see right there in front of you) not immediately shown in the search screen? Surely it's easier and way faster to do a fulltext search on from, to, subject, and body fields on all messages stored locally than it is to ping # online accounts?

**Comment by khamidou** [comment] 2016-03-30 20:49
We've just shipped a fix for IMAP and Exchange search. Could all the people affected try to see if search now works for them? 

Thanks,

k

**Comment by lmartins** [comment] 2016-03-30 21:05
Im assuming that change is server side since the app doesn't detect any update. For me now it starts searching but never finishes, eventually throwing an error which says "Search failed for one or more accounts. Search aborted. Please try again"

**Comment by kristianlam** [comment] 2016-03-30 21:59
Same thing. Failed with "Search failed for one or more accounts. Search aborted. Please try again"

**Comment by enoversum** [comment] 2016-03-31 07:42
Same old, same old :cry: .

**Comment by bonaldi** [comment] 2016-03-31 09:41
Different error for me, with my Exchange server: "An unexpected error happened. Please try again"

**Comment by fonnesbeck** [comment] 2016-04-01 14:11
I get messages like the following quite frequently. Not sure if it is related:

![message](http://fonnesbeck-dropshare.s3.amazonaws.com/Screen-Shot-2016-04-01-09-10-35.png)

**Comment by jstejada** [comment] 2016-04-05 17:32
hey everyone, we've added client side search in https://github.com/nylas/N1/commit/8a1aa6e9bb3e6914c279a313537b70b6b95682f5, and some additional back end improvements which should substantially improve the search experience

**Comment by FlorianBrinkmann** [comment] 2016-04-05 17:58
Still does not work. I get an error that the search failed for one or more accounts and that an internal error occured (IMAP accounts)

**Comment by lmartins** [comment] 2016-04-05 20:19
@FlorianBrinkmann I believe we'll need to wait for the next N1 release

**Comment by jstejada** [comment] 2016-04-05 21:10
@FlorianBrinkmann , correct. It is on master, but it hasn't been released yet

**Comment by FlorianBrinkmann** [comment] 2016-04-06 05:59
Oh yes, that makes sense…

**Comment by bengotow** [comment] 2016-04-13 00:56
Hey folks! Thanks for taking the time to report issues here. This afternoon we shipped version 0.4.25 which addresses search performance in two significant ways:

1. N1 now does client-side search of your last 10,000 threads, returning results very quickly. We've found that most of the time, this will get you what you want in <100msec.

2. N1 now uses an API on the sync engine that streams search results as they're retrieved from your backend provider. For IMAP users, this means you'll see results from your Inbox folder, followed by results from Sent and other folders. Previously the backend waited for results from /all/ your folders before returning them, which could lead to search taking 10+ seconds.

There are several other improvements we'll be working on this summer, including showing more results., but this should dramatically improve the state of search in N1. You can grab the update now from the Releases page—it'll be rolled out to auto-updaters over the next few hours. I'm going to close this issue—feel free to re-open or create new tickets if you continue to have specific issues. Cheers!

**Comment by dcrystalj** [comment] 2016-04-13 08:13
I have updated to 0.4.25 - ubuntu, and must say that search is finally working but most of the time it's far from quickly. I am using IMAP only. If I enter mail or subject or name of sender from last few days, it does not search locally and so it is slow. Without internet it does not find anything

**Comment by FlorianBrinkmann** [comment] 2016-04-13 09:36
Seems to work with 0.4.25, and it’s quick after the mailbox are synced. But I always get the message, that a new update is available and it wants to install 0.4.19 …

**Comment by enoversum** [comment] 2016-04-13 09:57
Is it only me, or am I put back to 0.4.19 after an update? Had updated after the internal message to do so. Checking version, it says 0.4.29. Tried the Check for Update function, and it’s notifying me of no newer version. Search works the way it did, no results, only error messages :cry: .

**Comment by jstejada** [comment] 2016-04-13 15:24
hey @enoversum there is a known issue with the autoupdater: #1939

**Comment by jstejada** [comment] 2016-04-13 15:26
Hey @dcrystalj , as @FlorianBrinkmann mentioned, we build the local search index after your mail has completely synced, so it might be the case that when you searched the first time the search index was still being built. After the index has been built, you should be able to search quickly offline. Let me know if that is not the case

**Comment by enoversum** [comment] 2016-04-13 15:40
@jstejada Thanks for confirming :wink: . Luckily, my manually updated N1 does not ask for a downgrade and confirms I use the current version, so all fine here. 

One thing really strange is that it only seems to show recent or at least selective results. I used a simple search term like 'katja', and it displays four conversations from which three are older and do not contain the search term at all (not in subject/recipient/sender/body). However, searching with my 'old' e-mail client for the same term turns up 156 different conversations related to the search term, with one from about a week ago which has the search term in its body text, some e-mails with Katja as the sender, some as recipient etc. I started the search on N1 from the Inbox (and I hope it doesn’t matter on which folder I am in order to search all mail). So search seems to bring up some results, but is a little wonky in what it returns. My 'older' client saves an amount of mail right on my computer I suppose, so search is quite efficient and fast, while older results are retrieved from the server which takes a few seconds, but isn’t as slow as N1 is even with those few results. I hope this report helps to clear up things :smile: .

**Comment by jstejada** [comment] 2016-04-13 16:54
Thanks for the additional details @enoversum -- that is really weird. Just to confirm if the search index was created, you can open the Activity Window via `Developers -> Open Activity Window`, open the console logs in that window via `Cmd (Crtl) - Shift - I` and looking for a message that says `Thread Search: Index built successfully`.
We'll look at incrementing the size of the index and the search parameters to keep improving it. Thanks!

**Comment by enoversum** [comment] 2016-04-14 06:44
@jstejada Thanks for getting back ;). I tried to follow your guide, but wasn’t able to open up the Console in the Activity Window with your shortcut. Neither with i or L. I tried the normal Console on Nylas, but it didn’t contain the message you referenced (and I guess it is actually the wrong place to look for it).

**Comment by Bergg** [comment] 2016-04-14 09:20
Version 0.4.25 fixes the issue for me. Full search in imap and exchange now working.

**Comment by kristiankim** [comment] 2016-04-15 15:02
Updated the app and tried searching IMAP email, I can't say it's working. It did pull some result quickly but it missed lots of threads. It pulled the result from the latest and it suddenly jumped back to last year's email, missing in between. Anyone with the same issue?

**Comment by richpollen** [comment] 2016-04-22 08:21
same issues for me. no search results come up when searching for anything

**Comment by benjamingarcia** [comment] 2016-04-22 12:32
Works for me!  :metal:
Thanks, now good by _Mail_

**Comment by dcrystalj** [comment] 2016-04-22 23:06
works for me as well for new/read mails. Nylas is finally fully functional and
useful.  
  
Lp,

Tomaz

  

On Apr 22 2016, at 2:32 pm, benjamin &lt;notifications@github.com&gt; wrote:  

> Works for me! ![:metal:](https://assets-
cdn.github.com/images/icons/emoji/metal.png)  
Thanks, now good by _Mail_

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/750#issuecomment-213405976)![](https://github.com/notifications/beaco
n/ABZJ9xO-DWbmvxIpBOeVlSDAyV_iKV_zks5p6L_1gaJpZM4G39fv.gif)

**Comment by jayachandranm** [comment] 2016-04-25 06:56
Search now seems to work fine (Nylas 0.4.15, ubuntu-16.04). But deleting an item from the search result does not immediately remove that entry from the lisiting.

**Comment by ewiggin** [comment] 2016-05-17 08:26
This functionality not work fine. I have a lot of emails inside folders and the search tool box not search for all emails. Maybe 20% the results are correct, 80% not showed. This not work for me. 

I have the last version.

**Comment by ewiggin** [comment] 2016-05-19 07:00
![seleccion_005](https://cloud.githubusercontent.com/assets/657517/15385173/07a58032-1da0-11e6-80ac-75753e01ca6c.png)
![seleccion_001](https://cloud.githubusercontent.com/assets/657517/15385177/0c660290-1da0-11e6-8319-ccd897b6a1c0.png)

**Comment by ewiggin** [comment] 2016-06-03 08:37
Please re-open this issue. Nylas search on Imap not work. I have thousands mails i can't search correctly...

**Comment by dcrystalj** [comment] 2016-06-03 09:07
for me it's working perfectly on gmail && outlook.com imap

**Comment by enoversum** [comment] 2016-06-03 09:09
I can confirm it kind of works, but only gives partial results on IMAP. Some recent threads, and then mostly complete bogus e-mails that do not contain the search term at all. Most of all, older e-mail as well as e-mails that are only a bit older and supposively even in the local cache, still often cannot be found.

**Comment by ewiggin** [comment] 2016-06-03 13:39
@enoversum this is correct. Thanks.

**Comment by cpescott** [comment] 2016-06-22 15:47
@enoversum I am experiencing the same issues - I wish this would work :(

**Comment by barriem** [comment] 2016-08-09 17:24
same issue here on OSX (10.11.5), Nylas (0.4.47-3a2a94c)

**Comment by manishie** [comment] 2016-08-30 22:53
Not working for me either for a Gmail account on OSX 10.11.6, N1 0.4.49-c9c04b7.  Search only returns a couple of weeks of emails.  I get 30 results, vs 344 in the Gmail web interface.

**Comment by abojchevski** [comment] 2016-08-31 13:26
Not working for me as well. Both for my Gmail account and for my work IMAP account.

**Comment by arifb** [comment] 2016-08-31 18:58
Search with gmail account is completely broken for me on 0.4.49-c9c04b7. Here is the stack when I submit a search:
```
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:306 Error: QuerySubscription: Applied all changes and result set contains duplicate IDs.
    at SearchQuerySubscription.QuerySubscription._createResultAndTrigger (query-subscription.es6:270)
    at _fetchMissingModels.then.models (query-subscription.es6:248)
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:507)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:581)
    at Promise._settlePromiseAtPostResolution (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:245)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:128)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133)
    at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15)
    at tryOnImmediate (timers.js:543)
    at processImmediate [as _immediateCallback] (timers.js:523)
```

**Comment by arifb** [comment] 2016-09-06 19:01
With the latest update I no longer get the error in the previous comment, however search is still broken. When I search `from:hello@nylas.com` for example, there are a couple obvious issues:

- it doesn't seem to be using the Gmail advanced search api, like it used to
- seems like it's subbing `NaN` in for the `f` for some reason, here's the search from the console

```
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:385  120msec: SELECT `Thread`.`data` FROM `Thread`  WHERE `Thread`.`subject` like 'NaNrom:hello@nylas.com%' AND `Thread`.`account_id` = '8542sbpk6ebr76xpk2xj52fk7'  ORDER BY `Thread`.`last_message_received_timestamp` DESC LIMIT%c 4```

**Comment by jstejada** [comment] 2016-09-07 17:09
another incidence: https://nylas.zendesk.com/agent/tickets/6080

**Comment by jstejada** [comment] 2016-09-07 17:11
another incidence: https://nylas.zendesk.com/agent/tickets/6086

**Comment by hallamoore** [comment] 2016-09-09 18:35
Another incidence: https://nylas.zendesk.com/agent/tickets/6143

**Comment by jackiehluo** [comment] 2016-09-09 23:22
Another incidence: #2818

**Comment by jeremysawesome** [comment] 2016-09-13 15:50
I'm also running into a similar issue. When I search for something the select box get's suggestions but searching for anything shows "No search results available".

This is using version `0.4.51`

**Comment by arifb** [comment] 2016-09-14 21:46
Upgraded to Version 0.4.52-5c342df just now, issue persists, again with the strange NaN in developer console. Searching for `from:admin@email.com` results in this in console:

    SELECT `Thread`.`data` FROM `Thread`  WHERE `Thread`.`subject` like 'NaNrom:admin@email.com%'
    AND `Thread`.`account_id` = 'truncated'  ORDER BY
    `Thread`.`last_message_received_timestamp` DESC LIMIT%c 4

**Comment by jstejada** [comment] 2016-09-19 19:03
hey @arifb thanks for the updates -- we're looking into this now. Will post any updates here. Thanks for your patience!

**Comment by jackiehluo** [comment] 2016-09-21 16:45
Another incidence: https://nylas.zendesk.com/agent/tickets/6296

**Comment by jstejada** [comment] 2016-09-28 18:08
https://github.com/nylas/N1/commit/ab954521307d93418ff289fa9b0c337e41995f0a

**Comment by jstejada** [comment] 2016-09-28 18:09
We've added a couple of fixes to search which will go out on a release this week!

**Comment by tcr** [comment] 2016-09-28 18:44
One more report of this, with the stack trace (169 times this error occurs, then no search results found):

```169 Error: QuerySubscription: Applied all changes and result set contains duplicate IDs.
    at SearchQuerySubscription.QuerySubscription._createResultAndTrigger (query-subscription.es6:270)
    at _fetchMissingModels.then.models (query-subscription.es6:248)
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:507)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:581)
    at Promise._settlePromiseAtPostResolution (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:245)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:128)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133)
    at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15)
    at tryOnImmediate (timers.js:543)
    at processImmediate [as _immediateCallback] (timers.js:523)module.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:306
169/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:306 Error: QuerySubscription: Applied all changes and result set contains duplicate IDs.
    at SearchQuerySubscription.QuerySubscription._createResultAndTrigger (query-subscription.es6:270)
    at _fetchMissingModels.then.models (query-subscription.es6:248)
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:507)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:581)
    at Promise._settlePromiseAtPostResolution (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:245)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:128)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133)
    at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15)
    at tryOnImmediate (timers.js:543)
    at processImmediate [as _immediateCallback] (timers.js:523)module.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:306QuerySubscription._createResultAndTrigger @ query-subscription.es6:274_fetchMissingModels.then.models @ query-subscription.es6:248tryCatcher @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26Promise._settlePromiseFromHandler @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:507Promise._settlePromiseAt @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:581Promise._settlePromiseAtPostResolution @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:245Async._drainQueue @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:128Async._drainQueues @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133Async.drainQueues @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15tryOnImmediate @ timers.js:543processImmediate @ timers.js:523
```

**Comment by bengotow** [comment] 2016-09-30 17:26
Hey folks—thanks for all the feedback. If you've been having trouble with search in N1, try installing version 0.4.56 which was released this morning. You can download it from the GitHub Releases page, or choose `Application Menu > Check for Updates` within the app. It includes fixes for two significant issues that were impacting IMAP and Exchange accounts, and I'm going to go ahead and close this. Cheers!

**Closed by bengotow** 2016-09-30 17:26 UTC
Labels: bug, done-pending-release, mail-sync, needs-attention
