### ISSUE TITLE
Crashing when opening

### ISSUE THREAD

**Issue by avves** [nylas/N1#506] opened 2015-11-29 08:26 UTC
When I close (not quit) N1 and open it again from the Dock it crashes.

See this: http://d.pr/v/E7XW/3XhPgctH

Console:
![image](https://cloud.githubusercontent.com/assets/238139/11456066/ba76a4ea-967b-11e5-9535-fd8dc4d16233.png)

OS X Yosemite 10.10.5
Nylas N1 0.3.25-c174641

**Comment by jstejada** [comment] 2015-11-29 09:25
Hi @avves , thanks for reporting this. I'm closing as a duplicate of #488

**Comment by avves** [comment] 2015-11-29 09:57
:+1:

**Closed** 2015-11-30 19:59 UTC
