### ISSUE TITLE
Major problem with account removal

### ISSUE THREAD

**Issue by Iain-Stevenson** [nylas/N1#1021] opened 2016-01-14 15:31 UTC
This is a pretty hard problem to reproduce!

Scenario

Windows 10 Surface Pro 4 (x64) Latest build
N1 Version 0.3.43

Registered accounts
1 Exchange (Personal)
2 GMail (Personal)
1 IMAP (Professional)

All synced up to date

The Exchange account has an (already reported) incorrect flat folder structure (does not match that of Outlook.com). The IMAP (outlook.com) account works fine,  I attempted to remove that exchange account and re register it as IMAP. 

When I clicked remove for the exchange account, bang! The N1 program completely disappeared (crashed) and auto restarted as if it was newly installed, with no accounts registered and set up as if new....becuase it took me through the new user screens

It also chose the Dark them by default (Probably from last working choice) and this unreadable screen resulted.

![image](https://cloud.githubusercontent.com/assets/1642735/12328322/c8f4a780-bad2-11e5-841d-992b479a6223.png)

I re-registered my personal account as an IMAP account this time and its now syncing as if new... The folders appear to be hierarchical, which was why I removed the account in the first place.

There's about 3000+ messages in there so will take some time to confirm.

This journey has proved to me that there is a folder sync issue for Exchange format accounts, and a whopping bug when removing accounts! Sorry, I don;t have time to try and reproduced that again.

The above description is a faithful representation of what just happened.

**Comment by Iain-Stevenson** [comment] 2016-01-14 16:27
So far since this occurred the 'Syncing your mailbox' stayed there all this time and has only just finished. Oh, then it started up again.... This is better than before, and it went away altogether on previous version after a few seconds.

**Comment by Iain-Stevenson** [comment] 2016-01-14 16:30
Just though of some more context for the above problem that may be useful. N1 was only started a while back after installing SQLExpress 2014 forced a reboot. So its not due to a long run time build up of problems. BTW: The machine is under active rebuild from a rom reset so this is about as clean a machine as I can get hold of....

**Comment by mbilker** [comment] 2016-01-14 17:36
First of all, thank for reporting this issue @Iain-Stevenson. I have experienced this issue before on my own computer while testing a plugin I developed. The whole `~/.nylas/config.cson` file was empty only defining `'*'.env` to `production`. The `edgehill.db` file was intact (speeding up the mail sync process).

**Comment by bengotow** [comment] 2016-01-14 18:36
Hey @Iain-Stevenson — hmm, thanks for reporting this. It sounds like your preferences file was definitely being emptied for some reason, though it's strange that the theme stayed `ui-dark` after that point. This may be a duplicate of #314 , but I'm not sure.

**Comment by Iain-Stevenson** [comment] 2016-01-14 18:43
I'm going to try and recreate the fault, it will take a whole as ideally I have to get my second large account to sync (3+ items) and register my other GMail accounts as well.

If it does happen again is there anything specific I should look for/at. please remember that whilst I am an experienced developer I know nothing about N1 or is architecture or development so far. I am familiar with REST services Angular, JSON Javascrip and .NET so I should be able to find out loads of stuff if pointed in the right direction.

**Comment by Iain-Stevenson** [comment] 2016-01-14 18:54
Point of interest: Having added in my professional account (IMAP) it pretty much instantly synced, I mean 15 seconds for 3000+ items. The Nylas server must have re-connected me to its store of items from yesterdays sync (it was an IMAP account sync first time round) Clearly my Personal account was a new IMAP sync and had to be done from scratch.

Newbie sticking his neck out here and I'm guessing the Exchange sync problems with the flat organisation of the folders could be wholly a NYLAS server side problem and not a fault with the N1 implementation.
BTW: wrt #314 There's no way I am running out of disk space spare 100Gb to play with or memory with a spare 8Gb headroom.

**Comment by Iain-Stevenson** [comment] 2016-01-14 19:35
OK Added all the other accounts in (GMail) and took out IMAP personal account for outlook. Did not fault (but that is not same scenario).

Added in Personal Outlook account as Exchange. Folders are back to being flat structure and are taking a long time to sync. no visual syncing indicator at all. I will wait until tomorrow to let it catch up and then try and repeat what I did that kicked this all off.

**Comment by Iain-Stevenson** [comment] 2016-01-15 09:08
I performed a repeat exercise of removing the Outlook (Exchange) account again, and it did not repeat the failure. Everything worked as I would have expected. Damn :-) I was hoping I could shed some light on this problem.

I then re-added the account back in as an IMAP registration and it works beautifully, and once again synced really fast. There must be some sort of caching going on with the nylas server as the time to sync on my workstation was again, a hand full of seconds...!

**Comment by grinich** [comment] 2016-01-18 17:51
Yep, we do some caching to make things easier for users who are quickly connecting/disconnecting accounts.

I'm going to close this bug since we can't figure out how to reproduce it. I strongly suspect it is related to #314

**Comment by grinich** [comment] 2016-01-18 17:52
Or rather, #897

**Closed by grinich** 2016-01-18 17:51 UTC
Labels: account-management, bug

**Comment by Iain-Stevenson** [comment] 2016-01-18 19:44
OK, understood, by all means close this down, you cant fix a non reproducible problem. Personally not convinced its a disk or memory space issue as I said before plenty of both. Working set issue potentially and most likely. Following Information is for posterity only then. :-)

This was running on a Windows 10 fully patched x64 Surface Pro 4 development class machine with 16Gb RAM and 512Gb storage, with 8 & 100Gb free respectively at the time of the incident. no idea what my working set was at that time.

A-ha moment in progress: I also had N1 running concurrently on my DELL laptop would this have had an impact?


The machine was undergoing installations of Visual Studio and other related products close to that time but no concurrently with the error. This may have caused something to twitch inside the windows run time, but what that may have been is anyone's guess.
