### ISSUE TITLE
Update broke bullets

### ISSUE THREAD

**Issue by MikeyAnderson** [nylas/N1#1973] opened 2016-04-15 17:44 UTC
The bullets no longer work by using a dash.

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by markbao** [comment] 2016-04-18 04:09
+1. More detail:

Version 0.4.25-a22631a (0.4.25-a22631a)

Regression: 0.4.19 did not contain this bug.

Reproduce:

1. Open compose.
2. In body, type "- asdf".
3. Also type "1. asdf"

Expected behavior: creation of bulleted and numbered list.

Actual behavior: stays as text.

**Comment by markbao** [comment] 2016-04-18 04:10
+1. More detail:

Version 0.4.25-a22631a (0.4.25-a22631a)

Regression: 0.4.19 did not contain this bug.

Reproduce:

1. Open compose.
2. In body, type "- asdf".
3. Also type "1. asdf"

Expected behavior: creation of bulleted and numbered list.

Actual behavior: stays as text.

@mbilker Can you help categorize this?

**Comment by mbilker** [comment] 2016-04-18 05:22
I have also experienced this on the latest master. I also tried two dashes (--) followed by a space and also a tab.

**Comment by TaylorBarr** [comment] 2016-04-21 17:57
Love for this to be fixed! Kind of a headache in my messaging style since I use bullets for everything. Hopefully a new release will come soon:)

**Comment by jackiehluo** [comment] 2016-04-21 18:02
Yep, it's been fixed, and it'll be out in the next release!

**Comment by bengotow** [comment] 2016-05-03 15:33
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!

**Closed by bengotow** 2016-05-03 15:33 UTC
Labels: bug, done-pending-release

**Comment by markbao** [comment] 2016-05-03 17:22
Confirmed fixed after updating, thank you @bengotow!
