### ISSUE TITLE
Can´t delete all emails from Trash at once and forever

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#684] opened 2015-12-12 01:49 UTC
As a user, when I see all emails in INBOX.Trash I need to see a way to select all and delete them forever. Currently I can only select and archive (why would I want to archive things in the trash?) the only thing I want to see in the trash is Select all > delete.

**Comment by bengotow** [comment] 2015-12-12 03:16
Closing as a duplicate of #599

**Closed by bengotow** 2015-12-12 03:16 UTC
