### ISSUE TITLE
Clicking N1 in the Dock should reveal all windows, not just the main window

### ISSUE THREAD

**Issue by psoiree** [nylas/N1#1117] opened 2016-01-23 07:56 UTC
Hello guys!

I've noticed that You can't maximize the window of Nylas by double-clicking the main upper bar. Also when two windows of Nylas are opened (for example main window + new email) You can't bring both of them to the front of other OS X windows. Only main window comes up when You click on the Nylas icon in the dock. So when You started writing new e-mail and You wanted to check something on safari for example (and also You have two monitors...) You can't get back to Your e-mail until You move all the windows and find that specific one.

Another thing about windows: what Sparrows had and most of e-mail clients also have is ability to click on the e-mail which will show up the window with this e-mail so You can browse other e-mails while having this one opened. At the moment when You want - for example - copy part of the text from Your sent e-mail and have it opened for reference and also browse other e-mail You just can't do it.

Regards,
Paul

**Comment by bengotow** [comment] 2016-01-26 19:46
Hey @psoiree — thanks for filing this! I think the first bit is a duplicate of #974  and the second bit is #779 . I'm going to rename this to just discuss the behavior of the dock "bring to foreground", which does need to show secondary windows.

**Comment by psoiree** [comment] 2016-01-27 09:56
Hello @bengotow ! Indeed it is the duplicate but setting the dock doesn't help. It's kinda frustrating when You have to set the size of the window manually :)

**Comment by psoiree** [comment] 2016-02-18 09:14
Guys, it's been a month... This thing drives me crazy. You can't write two e-mails at once until You find the windows and put them side by side manually...

**Comment by psoiree** [comment] 2016-04-23 10:16
@bengotow Hi :) Did You find the solution guys? Now it's been 4 months and You're about to release Nylas Pro but how can I recommend it to my friends if You can't adress such issue?

**Comment by bengotow** [comment] 2016-05-09 23:55
It looks like the dock clicking issue has been fixed upstream in Electron - going to close this! I think you're talking about #779? We'll probably address that in the next few months, but it'd be great if you could follow up on that issue. PRs are always welcome, of course.

**Closed by bengotow** 2016-05-09 23:55 UTC
Labels: bug, os x
