### ISSUE TITLE
Add signatures

### ISSUE THREAD

**Issue by xedef** [nylas/N1#213] opened 2015-10-27 04:29 UTC
It would be great to have an HTML signature per account

**Comment by bryan** [comment] 2015-10-29 19:01
I believe they have people already working on it.
Check out their roadmap: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

Duplicate of https://github.com/nylas/N1/issues/1

**Comment by bengotow** [comment] 2015-11-30 22:08
Hey folks—signatures are landing in a release later this afternoon (0.3.26). Enjoy!

**Closed by bengotow** 2015-11-30 22:08 UTC
