### ISSUE TITLE
Feature request: Ability to do pgp encryption

### ISSUE THREAD

**Issue by artailicous** [nylas/N1#432] opened 2015-11-19 19:40 UTC
It would be great with an easy to use integrated ability to do pgp encryption. Or one can of course leave that to someone do develop as an plugin perhaps?

**Comment by mbilker** [comment] 2015-11-19 21:11
Hello. That is me. Sill in development.

**Comment by mbilker** [comment] 2015-11-19 21:11
Also #96, #65, #19.

**Comment by mbilker** [comment] 2015-11-19 21:12
Currently working on it at: https://github.com/mbilker/email-pgp

**Comment by artailicous** [comment] 2015-11-19 21:49
As noted by @dcposch in #19 this would require in-depth integration to work properly. As I understand it dear @mbilker, you are working on a decryption plugin or do you have plans for more extensive features. Have you noticed any issues with the current plugin framework to make a smooth PGP decryption in N1?

**Comment by mbilker** [comment] 2015-11-20 02:24
@artailicous not that I know of. The `AutoloadImage` internal plugin was the basis for how to format a message body before displaying it to the user, and I can force a redraw with `MessageBodyProcessor.resetCache()`. I am working on an encryption plugin using the Translate composer example plugin as a basis. Working on Keybase integration since that is the easiest way to go for encryption with public keys.

Storage of private keys is harder because I am targeting multiplatform and GPG is not available on all platforms. I use openpgpjs for decryption, but it is slow compared to some other engines. kbpgp from Keybase doesn't do signature verification correctly resulting in failed decryptions that openpgpjs and GPG can decrypt just fine.

**Comment by grinich** [comment] 2015-11-20 02:48
@madhugb how does kbpgp fail for signature verification?

**Comment by mbilker** [comment] 2015-11-20 02:56
@grinich https://gist.github.com/mbilker/8f38bc825e42b902c478

The file run is `kbpgp/test-kbpgp.js` of the email-pgp project with `node test-kbpgp.js \`head -1\` > ~/output`. I will produce the example where the code causes a misread of the key needed.

**Comment by mbilker** [comment] 2015-11-20 03:02
https://github.com/keybase/kbpgp/blob/4340167caf1004d836f9ef609ee89d0152471fa3/src/openpgp/processor.iced#L221-L238 is where I noticed weird results using the node REPL to step by step process my message.

**Comment by mbilker** [comment] 2015-11-20 04:11
I just encountered a bug and posted #436.

**Comment by mbilker** [comment] 2015-11-24 03:17
Ok. #436 closed.

**Comment by grinich** [comment] 2015-11-24 23:05
Closing as dupe of #96

**Closed by grinich** 2015-11-24 23:05 UTC
