### ISSUE TITLE
Latest update reset accounts and settings

### ISSUE THREAD

**Issue by Dids** [nylas/N1#906] opened 2016-01-06 09:26 UTC
I'm running N1 on OS X and noticed that last night N1 had entirely reset itself. It had lost all preferences and mailboxes/accounts, although it did keep the themes (but didn't keep them as active).

I should also point out that after restarting N1 and going through the initial setup again, the app prompted me to install an update, so I'm assuming there's some sort of auto-update mechanism that borked the entire installation.

Was this intentional? Is this going to happen with every update?

**Comment by pedropapa** [comment] 2016-01-06 11:54
I just installed the latest update now (0.3.36-e8239a9) and everything is working just fine, no resets or settings lost.

**Comment by Dids** [comment] 2016-01-06 12:34
The manual installation itself went fine for me too, but I've had my mac open overnight, and that's when N1 had reset itself. After going through the initial setup again, I noticed the update notification, which worked when manually installing, but this still doesn't explain the reset that happened.

**Comment by bengotow** [comment] 2016-01-06 17:54
Hey @Dids — is there any chance you're running out of disk space on your machine? We're currently investigating #897, which might be the cause of your issue.

**Comment by Dids** [comment] 2016-01-07 09:00
@bengotow I think I was, actually!

**Comment by akizor** [comment] 2016-01-07 13:46
@bengotow I can confirm this also, actually i was getting an "out of space" warning, although it's plenty of space available. Everything was reset.

**Comment by grinich** [comment] 2016-01-18 17:53
I'm going to close this as a dupe of #897. Thanks!

**Closed by grinich** 2016-01-18 17:53 UTC
Labels: account-management, bug
