### ISSUE TITLE
Trashed items showing in Inbox

### ISSUE THREAD

**Issue by malaparte** [nylas/N1#349] opened 2015-11-03 16:05 UTC
As of 11/2 or 11/1, I've started seeing emails that were previously trashed, and are labeled as such, appearing in my inbox.
<img width="246" alt="screen shot 2015-11-03 at 08 04 03" src="https://cloud.githubusercontent.com/assets/1800364/10913152/992aed0c-8201-11e5-8789-fe487053550d.png">

**Comment by Glark** [comment] 2015-11-22 23:28
Me too. In Gmail when you reply in an email thread, trash it that the email threads bubbles up to the inbox again because of another reply, the thread shows itself in the inbox again.

Feels like N1 is doing that same thing but keeping the trash tag on it.

So I guess:
- Gmail Inbox = no trash tags
- N1 inbox = keeps trash tags

I have no idea what's better here. I get you might want to know if something in the inbox is also in the trash but it does feel error-y.

**Comment by jackiehluo** [comment] 2015-12-02 15:54
Same for me! And not as @Glark is saying, that trashed threads resurface after someone adds a new response. I have a lot of threads that just persist in the inbox after I delete them.

**Comment by hostmaster** [comment] 2015-12-15 11:45
Same for me. I think an option to 'Hide messages with Trash' tag' could be useful. 
I've enabled an option 'Show unread counts for all labels' and now all labels are full of deleted messages, which are not actually deleted but have 'Trash' label.

**Comment by plainspace** [comment] 2016-01-06 18:08
+1

**Comment by strumpet** [comment] 2016-01-07 21:19
+1

**Comment by framerate** [comment] 2016-01-08 21:26
This is the main thing preventing me from really diving into N1 (well that and unified inbox). I test other mail clients and these TRASH messages don't show up there (or in google inbox).

For the record, only the top message should be in the inbox. The rest are coming from TRASH and SPAM apparently.

<img width="376" alt="screen shot 2016-01-08 at 1 24 21 pm" src="https://cloud.githubusercontent.com/assets/74291/12209939/41c43af8-b60b-11e5-9730-6a8f287ca8f3.png">

**Comment by grinich** [comment] 2016-01-25 23:25
dupe of #1135

**Closed by grinich** 2016-01-25 23:25 UTC
Labels: bug, mail-sync
