### ISSUE TITLE
Losing all configuration every time I restart OSX

### ISSUE THREAD

**Issue by colllin** [nylas/N1#719] opened 2015-12-16 15:16 UTC
Including accounts & preferences.

**Comment by mbilker** [comment] 2015-12-16 20:48
More information needed. N1 version, OS X version, Log files pertaining to N1.

**Comment by whollytrinity** [comment] 2015-12-20 12:23
Using Mac OSX 10.11.2 and N1 version 0.3.32. Losing the windows configuration at every restart, does not stay at the window widths required.

**Comment by colllin** [comment] 2015-12-21 15:21
I haven't seen it in the last few days, so I don't think I have any logs that would show it.  Also OSX 10.11.2.  Either the latest version fixed it, or if you want to hear my wild hunch: I think when I first installed Nylas, I never Quit except for Nylas being automatically closed when OSX restarted.  Then it seemed like it started saving preferences properly after I quit one time without restarting OSX.  So I'm thinking...  it might be related to preferences/accounts being saved on exit instead of as they're edited?  It [looks like](https://github.com/nylas/N1/blob/master/src/nylas-env.coffee#L716) the only place they're saved is related to a window unload event.  Possibly this event is unreliable when OSX is shutting down? Either way, I don't see any reason not to save the preferences immediately when they're edited.

**Comment by mbilker** [comment] 2015-12-22 01:33
Hmm. I had a similar issue on Linux recently. I installed the experimental Markdown plugin (don't bother trying it out, its **really** experimental) and it caused N1 to crash, taking the whole configuration with it.

I guess OS X doesn't give the correct event notification to Electron, or N1 isn't listening to the proper event. N1 could save the configuration after an incoming event with debounce time to prevent IO thrashing.

**Comment by bengotow** [comment] 2016-02-26 23:02
This will most likely be resolved in 5691fc88caf6047179d65ca0833f91578d6fbac5, which will ship in a patch this evening. I think the problem was caused by our sync workers writing to config very frequently, which dramatically increased the likelihood a crash would leave the config in an inconsistent state.

**Closed by bengotow** 2016-02-26 23:02 UTC
Labels: needs-steps-to-reproduce, platform-os-x
