### ISSUE TITLE
Command-Q does not quit app

### ISSUE THREAD

**Issue by jetlej** [nylas/N1#247] opened 2015-10-28 13:55 UTC
Command-Q closes the app window, but does not quit the app itself. I have to use Force Quit in order to fully close it (Mac OSX El Capitan)

**Comment by bengotow** [comment] 2015-10-28 19:01
Hey @jetlej —thanks for filing this. I'm going to close as a duplicate of https://github.com/nylas/N1/issues/173. We should have it fixed soon.

**Closed by bengotow** 2015-10-28 19:01 UTC
