### ISSUE TITLE
npm 1.4 is required to build N1

### ISSUE THREAD

**Issue by fehrm** [nylas/N1#2694] opened 2016-08-01 13:50 UTC
##### What operating system are you using?
Windows 10 X64

##### What version of N1 are you using?
Latest source

The error I receive after running script\bootstrap.cmd is 
"npm 1.4 is required to build N1"

This is the same for both Node 4.4.7 and 6.3.1.
Python is installed, VS2015 as well. Both configured as stated on node-gyp githubpage.

**Comment by bengotow** [comment] 2016-08-01 16:41
Hey! Hmm that's strange—I actually built N1 on Windows over the weekend, and it didn't work until I upgraded past npm 1.x. Will dig in and see if I can reproduce this—

**Comment by bengotow** [comment] 2016-08-01 18:07
Hey! What version of NPM are you using? I believe N1 may require NPM >= 1.4. I've been using NPM 2 and NPM 3 for a while.

**Comment by fehrm** [comment] 2016-08-01 18:16
Thanks for the fast response!

I managed to solve/circumvent it, I was using an utility called [nodist](https://github.com/marcelklehr/nodist) to manage my Node installations and I guess your script didn't like the way it invoked Node? Eitherway, uninstalling nodist and installing the latest Node from nodejs.org solved that issue.

**Comment by fehrm** [comment] 2016-08-01 23:57
Have other issues now though, I had to run:
 `npm install npm@latest -g` 
which solved my issues with node-gyp failing to compile runas and keytar. I also had to remove git and it's utilities (ls etc) from my PATH to solve same the bootstrap to fail at the mentioned packages.

Now though I end up with this error after the bootstrap script tries to run apm clean:
```
C:\Code\Git\N1\apm\node_modules\atom-package-manager\lib\auth.js:14
      throw error;
            ^
Error: A dynamic link library (DLL) initialization routine failed.
C:\Code\Git\N1\apm\node_modules\keytar\build\Release\keytar.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Code\Git\N1\apm\node_modules\keytar\lib\keytar.js:4:12)
    at Object.<anonymous> (C:\Code\Git\N1\apm\node_modules\keytar\lib\keytar.js:58:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)```

**Comment by jackiehluo** [comment] 2016-10-01 05:17
Closing because it looks like this issue was resolved (the new one looks different?).

**Closed by jackiehluo** 2016-10-01 05:17 UTC
Labels: self-hosting / contributing, windows
