### ISSUE TITLE
(probably) Feature request : allow self-signed SSL certificates

### ISSUE THREAD

**Issue by Krands** [nylas/N1#466] opened 2015-11-25 08:51 UTC
Hi,

I have a beautiful self-hosted [Yunohost] (https://github.com/YunoHost) server, and it uses a self-signed SSL certificate.

While I am sure to have the good credentials, N1 tells me I don't. I also verified the port, which they are correct. Since I can use SSL with N1, it looks like the latter does not recognize my self-signed certficate, which is a bummer.

What if you implement a function which, when there's a self-signed certificate, N1 recognize it as SSL and, if unknown, asks if it should trust the server ? I know Let's Encrypt will be available soon, but it could be interesting to have the function anyway.

Cheers ! :beers:

**Comment by mbilker** [comment] 2015-11-25 15:51
Dupe of #442

Self-signed certificates are not allowed. The Nylas Sync Engine checks certificates (#427, #344, #153, #47), though they are working on supporting more security configurations as stated in #344.

**Comment by Krands** [comment] 2015-11-25 16:09
Ho sorry, the #442 was not obvious to me, because it didn't look like mine at the title. But the two latters, i should've checked.

As you say, in #344 they are working on it. I'll be patient for this as much as for Let's Encrypt :smile:

**Comment by mbilker** [comment] 2015-11-25 16:50
I got a Let's Encrypt certificate for my website https://mbilker.us. The installation process is (mostly) painless and you can use the certificates in other programs because the path for the symlinked current certificate and keys remains constant, the symlink changes whenever the certificate is refreshed.

**Comment by jstejada** [comment] 2015-11-25 18:27
hey guys! I'm going to merge this into #442

**Closed by jstejada** 2015-11-25 18:27 UTC
