### ISSUE TITLE
Anti Spam W/ Nylas?

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#1763] opened 2016-03-16 16:08 UTC
Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

- What operating system are you using? MAC 10.11.3

- What version of N1 are you using? 0.4.14-53cd69b

**Bug?**
- Do you have any third-party plugins installed? Yes

- Is the issue related to a specific email provider (Gmail, Exchange, etc.)? Unsure

- Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot. 

**Feature Request?**
- Does this feature exist in another mail client or tool you use?
Yesy

**Comment by oldhickory30** [comment] 2016-03-16 16:12
I'm trying to determine whether Nylas actually has an anti Spam function, it appears it does not?
I'm able to move the suspected email into my a spam folder, however I end up getting the same email hours later. At this point I have to go to my email provider, and check spam email on the server side. Maybe this would be  a great plugin to develop! Very frustration not to control spam!

**Comment by mbilker** [comment] 2016-03-16 16:23
Dupe of #1213

**Closed by mbilker** 2016-03-16 16:23 UTC
