### ISSUE TITLE
When I close the Nylas window, the systray item disappears too

### ISSUE THREAD

**Issue by ismith** [nylas/N1#434] opened 2015-11-19 21:23 UTC
OS X, closing the window with cmd-w or clicking the red window button; N1 is still running, still there in the dock, but not present in the menu bar.  When I click the dock icon, it seems to restart N1; the unread-count badge disappears from the dock icon, the "Loading" splash screen shows up.

**Comment by artailicous** [comment] 2015-11-19 21:57
Yes, the program shuts down when one close the window currently. Would be nice if one could make the app start at system start in systray (if one prefer that). And also, that it would remain in systray when closing the app window (if one prefer that).

**Comment by jstejada** [comment] 2015-11-20 00:00
hey guys, is this behavior consistent on OSX? This is the intended behavior on Windows and Linux, but not on OSX. @ismith could you provide a dump of the logs from the mac Console app? We can't seem to be able to replicate this

**Comment by AhmadElMelegy** [comment] 2015-11-20 16:45
Why it's an intended behavior ? I want to make the the app working in background.

**Comment by bengotow** [comment] 2015-11-25 23:03
Hey gang we'll be fixing this in the next release. Going to merge this in to #475.

**Closed by bengotow** 2015-11-25 23:03 UTC
Labels: bug

**Comment by ismith** [comment] 2015-11-25 23:07
Awesome, thanks.
