### ISSUE TITLE
Hints when the mouse pass over the buttons

### ISSUE THREAD

**Issue by jorosmtz** [nylas/N1#300] opened 2015-10-30 02:04 UTC
I consider useful the hints on the buttons. Sometimes I don't remember the functions of buttons (especially when it's unknown to me a new software). At those moments, strange the hints.

**Comment by bengotow** [comment] 2015-10-30 22:45
Closing as a duplicate of https://github.com/nylas/N1/issues/277

**Closed by bengotow** 2015-10-30 22:45 UTC
