### ISSUE TITLE
Feature request: Split View Mode for OSX

### ISSUE THREAD

**Issue by scottnguyen** [nylas/N1#1524] opened 2016-03-01 17:13 UTC
OS: OSX 10.11.3
N1: Version 0.4.10-4e3595b

Feature Request:
When I hold the full screen window, it'd be nice if N1 could go in split screen mode.

**Comment by bengotow** [comment] 2016-03-01 18:44
Closing as duplicate of #313

**Closed by bengotow** 2016-03-01 18:44 UTC
