### ISSUE TITLE
Nylas crashed seemingly randomly after waking up from sleep

### ISSUE THREAD

**Issue by johanbrook** [nylas/N1#2179] opened 2016-05-09 16:28 UTC
##### Are there any related issues?

Not this particular crash.

##### What operating system are you using?

OS X 10.11.4.

##### What version of N1 are you using?

0.4.33-e8f137e

##### Do you have any third-party plugins installed?

[Markdown Composer](https://github.com/nylas/N1-Markdown-Composer).

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I don't think so.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Hard to say, I returned to the computer in sleep, and Nylas had crashed.

[Crash log here](http://cl.ly/g7R4)

Here is the latest logs before the crash (see segfault there):

```
2016-05-09 12:21:22,994 Nylas[15327]: BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d
2016-05-09 12:21:23,627 Nylas[15327]: assertion failed: 15E65: libxpc.dylib + 78986 [2CC7CF36-66D4-301B-A6D8-EBAE7405B008]: 0x89
2016-05-09 12:28:28,069 Nylas[15887]: Streaming log data to /var/folders/v9/tw72bsl9245ckv_zd3nmtwwm0000gn/T/Nylas-N1-15887.log
2016-05-09 12:28:28,612 Nylas[15887]: App load time: 630ms
2016-05-09 12:34:54,790 Nylas[15887]: BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d
2016-05-09 12:34:55,419 Nylas[15887]: assertion failed: 15E65: libxpc.dylib + 78986 [2CC7CF36-66D4-301B-A6D8-EBAE7405B008]: 0x89
2016-05-09 12:51:50,969 com.apple.xpc.launchd[1]: (com.nylas.nylas-mail.520672[15887]) Service exited due to signal: Segmentation fault: 11
```

**Comment by bengotow** [comment] 2016-05-09 16:48
Weird - in the stack trace it was actually an audio dispatch queue that crashed, not the main thread. I think that this was caused by N1 trying to play the "you've got mail" sound? Will keep investigating this.

**Comment by bengotow** [comment] 2016-05-09 16:48
Might be related to #1910

**Comment by johanbrook** [comment] 2016-05-09 16:53
Roger. Regarding audio: I had unplugged headphones before leaving the computer, and I've noticed that random OS X apps have crashed when I unplug the headphones (huge "wtf".. ). Miiight be related, not sure.

**Comment by bengotow** [comment] 2016-05-09 20:09
I think this is probably resolved by 25a21189cff3326ac2921d79b2f09dee87659927, but let's keep an eye on it and see.

**Comment by jstejada** [comment] 2016-05-19 23:44
Hey, v0.4.40 has shipped with a fix and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!

**Closed by jstejada** 2016-05-19 23:44 UTC
Labels: done-pending-release

**Comment by johanbrook** [comment] 2016-05-20 04:43
Thanks! Will try out 👌
