### ISSUE TITLE
Account names don't change with a search query entered

### ISSUE THREAD

**Issue by jffrybrwn** [nylas/N1#767] opened 2015-12-18 20:21 UTC
If you search for something and then try to switch accounts with a keyboard shortcut, the account folders change but the email address / account name at the top-right does not, and neither do the messages/results. My expectation would be that switching accounts would clear the query.

**Comment by jstejada** [comment] 2015-12-18 22:08
@jffrybrwn thanks for reporting this! you mean top-left right?

**Comment by jffrybrwn** [comment] 2015-12-18 22:10
Oh whoops—yes!

**Comment by bengotow** [comment] 2015-12-28 22:25
This has been fixed in 608060ed6d954fc116973c8d999a5114d3027c8d (Dup #850). The intended behavior is to switch accounts and re-run the search in the other mailbox. (At least until we have unified inbox, accidentally searching in the wrong mailbox is a pretty common use case...) Cheers!

**Closed by bengotow** 2015-12-28 22:25 UTC
Labels: bug
