### ISSUE TITLE
Flickering status icon on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by peterbrinck** [nylas/N1#1960] opened 2016-04-14 07:42 UTC
##### Are there any related issues?

None that I could find

##### What operating system are you using?
Ubuntu 14.04 LTS

##### What version of N1 are you using?
N1 0.4.25-a22631a

--

**Bug?**
##### Do you have any third-party plugins installed?
No (only the built-in)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No idea if it's reproducible
But here's a gif
![flickering](https://cloud.githubusercontent.com/assets/6154068/14520444/cff56aee-0224-11e6-97a7-730088db7d9c.gif)

The status icon is flickering, like when N1 is updating or something, and it doesn't matter if there's any unread mails or not

**Comment by bengotow** [comment] 2016-04-14 19:15
Hmmm that's really interesting — @mbilker any chance you've run into this? I think we may be refreshing the icon, so we could detect that the before/after states are the same, but either way I don't think it should flicker.

**Comment by bengotow** [comment] 2016-04-14 19:30
Hey folks—I've made a few changes in 67d28d4e592b36794163c24867df8b35e75587c9 to 1) avoid tearing down and re-creating the tray if, for some reason, we receive no-op config changes (eg from `true` to `true`), and also changed it so that it won't re-assign the tray image if it is identical. I think this should resolve the issue, but I'm not able to reproduce on Mac OS X.

**Comment by mbilker** [comment] 2016-04-14 19:47
@bengotow I have not run into this. I use `i3` and it does not flicker. It does show the correct status icons.

**Comment by CrazyLemon** [comment] 2016-04-17 13:27
Just my 2 cents.. I did use it on 14.04.4 for a few months and i didn't had any issues with tray icon flickering.

**Comment by bengotow** [comment] 2016-05-03 15:33
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!

**Closed by bengotow** 2016-05-03 15:33 UTC
Labels: done-pending-release, needs-steps-to-reproduce
