### ISSUE TITLE
Custom Sync Engine URL returns undefined for APIRoot

### ISSUE THREAD

**Issue by amansubhan** [nylas/N1#1260] opened 2016-02-09 08:02 UTC
```
env: "local"
  syncEngine:
    APIRoot: "http://147.55.21.25:5555"
```
Forwards the APIRoot as localhost:5555
![screenshot from 2016-02-09 12-59-51](https://cloud.githubusercontent.com/assets/3634377/12910517/38bf90ca-cf2d-11e5-9772-033c80160abc.png)

whereas
```
env: "custom"
  syncEngine:
    APIRoot: "http://147.55.21.25:5555"
```
doesnt read the value in APIRoot and executes the url with blank host.

![screenshot from 2016-02-09 13-00-50](https://cloud.githubusercontent.com/assets/3634377/12910518/38c00172-cf2d-11e5-993b-70bc8344c8ed.png)

**Comment by mbilker** [comment] 2016-02-09 18:19
Thanks for the report @amansubhan. Could you run `NylasEnv.config.get('syncEngine.APIRoot')` in the Javascript console (available from `Developer -> Toggle Developer Tools` and select the `Console` tab).

I saw this error before, but the `or` declaration should stop it from turning into `undefined`.

**Comment by bengotow** [comment] 2016-02-10 21:30
Hi @amansubhan — I think the problem is that `syncEngine` should not be indented:

```

env: "local"
syncEngine:
  APIRoot: "http://147.55.21.25:5555"

```

**Comment by mbilker** [comment] 2016-02-10 22:41
@bengotow `env` should be set to `custom`

**Comment by amansubhan** [comment] 2016-02-11 05:54
Recently i tried to compile on my CentOS 7 64bit. And i think ive messed up my system pretty much deep.
Now when im installing the rpm and running nylas, im getting the following error

`Can't find the Electron executable at /usr/local/bin/electron/electron. Be sure you have run script/bootstrap first from /usr/local/bin or set the ELECTRON_PATH environment variable.`

Will you please guide me to revoke the doing of nylas build script (although it failed), and make rpm version working again.

**Comment by mbilker** [comment] 2016-02-11 06:45
Use /usr/share/nylas/nylas to run N1. It is also available from the
Applications menu depending on your desktop environment.

This is a known issue.

**Comment by bengotow** [comment] 2016-02-26 07:53
Going to go ahead and close this since the original issue was addressed - feel free to re-open or search existing issues for other problems!

**Closed** 2016-02-26 07:53 UTC
Labels: bug, needs-steps-to-reproduce
