### ISSUE TITLE
Support signatures

### ISSUE THREAD

**Issue by ghhernandes** [nylas/N1#273] opened 2015-10-29 14:33 UTC
One thing that i miss, is signature support for emails like gmail (with images, font format, etc.).

Gabriel.

**Comment by bryan** [comment] 2015-10-29 19:01
I believe they have people already working on it.
Check out their roadmap: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

Duplicate of https://github.com/nylas/N1/issues/1

**Closed** 2015-10-29 19:29 UTC
