### ISSUE TITLE
Add a feature to make N1 work like mobile email clients

### ISSUE THREAD

**Issue by behrangsa** [nylas/N1#1291] opened 2016-02-10 16:00 UTC
On mobile email clients, as well as some desktop clients such as the now dead Mailbox, the entire mailbox which can sometimes be 10GB or more does not get downloaded.

Instead only the Inbox folder is downloaded. Other folders, when you click on them, download the most 50 recent emails on demand and as you scroll to the bottom of the view, the next 50 are downloaded, etc.

Add an option to N1 to make it work like this.

**Comment by mbilker** [comment] 2016-02-10 17:11
Dupe of #1198

**Closed by mbilker** 2016-02-10 17:11 UTC
