### ISSUE TITLE
Changing Account label will fail due to quick refresh

### ISSUE THREAD

**Issue by bobgrowth** [nylas/N1#856] opened 2015-12-29 03:01 UTC
I would like to change my account label and it's hard to change it.
It will refresh quickly to previous name so I have to click somewhere else to stop it from refreshing.

I'm using a gmail account in Win10 64 bit
and the version of N1 is 0.3.32

**Comment by jstejada** [comment] 2015-12-29 17:23
hey @bobgrowth thanks for reporting this. what do you mean by stop refreshing? do you mean while the mailbox is syncing like in this issue #838 ?

**Comment by bobgrowth** [comment] 2015-12-30 00:25
Yes, it's just that I wasn't aware if the mailbox was syncing or not.

**Comment by mbilker** [comment] 2015-12-30 02:24
Since this seems like a dupe of #838, I am closing this issue.

**Closed by mbilker** 2015-12-30 02:24 UTC
