### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by PMassicotte** [nylas/N1#1360] opened 2016-02-17 13:08 UTC
Hi.

When I am typing a message, the CPU usage goes up to 100% and the typing is *very* slow (basically unusable).

![nylas](https://cloud.githubusercontent.com/assets/4519221/13110366/e7d15e88-d57f-11e5-8be4-937ac75ab426.png)

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Stepping:              3
CPU MHz:               2004.890
BogoMIPS:              7183.07
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7

**Comment by PMassicotte** [comment] 2016-02-17 13:19
I noticed that if I remove my signature the problem is resolved. So it is kinda related to a (simple) html signature that I am using.

**Comment by bengotow** [comment] 2016-02-17 22:37
Whoa! That's super interesting. If it's not too personal, could you post a text file with your signature in it? You could remove / replace your info. I think there may be something specific about your signature that is causing one of our processing steps to hang.

**Comment by PMassicotte** [comment] 2016-02-18 07:26
There you go. The signature was written in markdown and then html generated in Atom. I just noticed that there is a TON of unnecessary html code. This must be the problem.

[signature.zip](https://github.com/nylas/N1/files/135794/signature.zip)

**Comment by molstrangler** [comment] 2016-04-25 10:07
I had the same issue when using my own HTML signatures.  when replying to an email, entering text was painfully slow.  I revert to standard N1 signatures and performance has returned.

**Comment by grinich** [comment] 2016-05-18 00:36
@PMassicotte what language is your OS set in? Could this be a dupe of #1069 ?

**Comment by PMassicotte** [comment] 2016-05-18 11:17
I am using Linux Mint (English language). Not sure if it is related to #1069 since I was occuring all the time, not only when replying.

**Comment by jacobwindsor** [comment] 2016-05-26 15:23
I also notice the same issue one Windows 10. Most definitely to do with the signature since performance is normal when I use an account with no signature

**Comment by jackiehluo** [comment] 2016-06-30 22:43
Another incidence: https://twitter.com/vinnytroia/status/748373119119859712

**Comment by jstejada** [comment] 2016-07-11 17:36
Another incidence: https://nylas.zendesk.com/agent/tickets/4031

**Comment by emorikawa** [comment] 2016-07-11 20:31
It appears to be related to this issue: https://github.com/nylas/N1/issues/1069 I'm closing this to merge it into #1069

**Closed by emorikawa** 2016-07-11 20:31 UTC
Labels: performance
