### ISSUE TITLE
Snooze email

### ISSUE THREAD

**Issue by martellalex** [nylas/N1#1320] opened 2016-02-12 05:44 UTC
I've been trying out Outlook iOS as a replacement for Mailbox app and its swipe functionality is pretty good.

One of the crucial missing pieces though is a **menu of quick snoozing options.**  This is something Mailbox really nailed as per below.

![image](https://cloud.githubusercontent.com/assets/8480779/12999764/d29a435e-d1a6-11e5-85d1-3584c8a2d2f7.png)

At the moment with Outlook I find it takes at least 2 more steps to properly snooze an email vs Mailbox.

For instance, in Outlook every time I snooze an email I have to set a specific time and date (there are some other options like "in a few hours" or "this evening" "tomorrow morning" but I have rarely used them).  The key missing ones that are missing are Desktop (which I appreciate would be difficult to implement because it requires an iOS app, but the premise is you're walking along on your mobile, and just snooze something to come up next time you open up your desktop client) and also "later today", "next week", "in a month" and "this weekend".

Even building in the latter 4 in addition to "this evening" and "tomorrow morning" would really nail snoozing.

What I'm saying I guess is you want to avoid not having the right snooze options and users ending up having to manually enter the snooze time for each email.

**Comment by mbilker** [comment] 2016-02-12 06:36
This is on deck for development. Also dupe of #71

**Closed by mbilker** 2016-02-12 06:36 UTC
