### ISSUE TITLE
No option to update account password

### ISSUE THREAD

**Issue by gardenofwine** [nylas/N1#369] opened 2015-11-05 09:11 UTC
After connecting to an Exchange account everything was fine. After a week, I changed my Exchange password NOT via Nylas. 

Nylas then stopped syncing, didn't provide an error message, and I couldn't change the account password - I needed to unlink and then add the account all over again.

**Comment by bengotow** [comment] 2015-12-02 18:03
Merging as a duplicate of #230—thanks!

**Closed by bengotow** 2015-12-02 18:03 UTC
Labels: account-management

**Comment by Sam2304** [comment] 2015-12-04 10:09
+1 Currently have to unlink relink to update a password. :/

**Comment by squiter** [comment] 2016-01-07 12:41
In my Exchange account I don´t have a unlink option. How can I update my password?

**Comment by Sam2304** [comment] 2016-01-08 13:00
The way I do it currently is as follows:

1. Head to the accounts drop down, select manage accounts:
![accounts](https://cloud.githubusercontent.com/assets/3308997/12198442/cbe54802-b607-11e5-8460-ee8c0302e164.png)

2. Highlight your exchange account & click the - button:
![accounts](https://cloud.githubusercontent.com/assets/3308997/12198275/58ba5f62-b606-11e5-8f24-aa81f826dc0e.png)

3. This will remove the account, then follow the steps you followed originally to re-link it with the new password.  I've found that the relinking process is very quick so I haven't been too bothered with this issue so far.

Hope that helps?
