### ISSUE TITLE
Sync with Gmail

### ISSUE THREAD

**Issue by DiegoNS** [nylas/N1#550] opened 2015-12-02 15:48 UTC
When I mark as read or archive a email on Nylas, gmail keeps it in the Inbox folder

**Comment by matthewbassett** [comment] 2015-12-03 05:40
+1 on this one. Same issue as @DiegoNS The default option for the "V" key shortcut in gmail is to add label and archive the email. However with the "V" key shortcut in Nylas, the label is added, but you must manually archive the email. Thanks for a fantastic client (:

**Comment by spang** [comment] 2016-01-04 23:06
Duplicate of #781.

**Closed by spang** 2016-01-04 23:06 UTC
Labels: mail-sync
