### ISSUE TITLE
debian jessie, N1.deb 0.3.45: /usr/bin/nylas fails, but /usr/share/nylas/nylas runs

### ISSUE THREAD

**Issue by SebKuzminsky** [nylas/N1#1197] opened 2016-02-03 22:02 UTC
I'm on Debian Jessie (8.3), with a vanilla install.  I downloaded N1.deb from the nylas website:

> \> dpkg -s nylas
Package: nylas
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 229408
Maintainer: Nylas Team <support@nylas.com>
Architecture: amd64
Version: 0.3.45
Depends: git, gconf2, gconf-service, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, libnotify4, libxtst6, libnss3, python, gvfs-bin, xdg-utils
Suggests: libgnome-keyring0, gir1.2-gnomekeyring-1.0
Description: An extensible, open-source mail client built on the modern web.
 Nylas N1 is an extensible, open source mail client built on the modern web.

Running "nylas" gives this error:

> \> which nylas
/usr/bin/nylas
\> nylas
Can't find the Electron executable at /usr/bin/electron/electron. Be sure you have run script/bootstrap first from /usr/bin or set the ELECTRON_PATH environment variable.

But this other executable I found in thge deb seems to work:

> \> /usr/share/nylas/nylas 
Gtk-Message: Failed to load module "canberra-gtk-module"
Streaming log data to /tmp/Nylas-N1-11929.log
App load time: 182ms

The expected behavior is that the nylas that's in the PATH should start the program.

**Comment by bengotow** [comment] 2016-02-03 23:51
This should be addressed soon by https://github.com/nylas/N1/pull/593.

**Comment by mbilker** [comment] 2016-02-03 23:56
Dupe of #411

**Closed by mbilker** 2016-02-03 23:56 UTC
