### ISSUE TITLE
Archiving an already archived item moves to trash

### ISSUE THREAD

**Issue by adeloscope** [nylas/N1#828] opened 2015-12-25 05:49 UTC
Selecting and archiving an already archived message (using 'y' keyboard shortcut) sends message to trash.  Expected behavior would be similar to gmail both in a list view, and in an open message view.  

gmail account
mac 10.11.2
N1 Version 0.3.32-b11131d (0.3.32-b11131d)

**Comment by mbilker** [comment] 2015-12-26 06:26
Hmm. Thanks @adeloscope! I can confirm this is a bug. Web Gmail's behavior is nothing, except for displaying a toast notification that the message was archived.

**Comment by adeloscope** [comment] 2015-12-26 20:46
That's why they call me the exterminator!  

(They don't really call me that)

**Comment by bengotow** [comment] 2015-12-28 19:08
Good find! It looks like this is actually the currently expected behavior, which is a bit strange. When you're looking at your archive, the `MailViewFilter` class returns `canArchiveThreads => false, canTrashThreads => true`, so the shortcut does the only thing it can and trashes the thread. I think the problem is that we map `y`, `backspace`, and `delete` to the `core:remove-from-view` action, when in reality `y` should be specifically "archive or do nothing."

**Comment by bengotow** [comment] 2015-12-28 19:10
(As a side note, it looks like the `e` shortcut will do what you want in the meantime!)

**Comment by adeloscope** [comment] 2015-12-28 22:21
I realized that I've been using 'y' as the archive shortcut for years on gmail!  Thinking it was 'e', but turns out the behavior is almost identical!

**Comment by jstejada** [comment] 2016-02-02 02:00
this is fixed with https://github.com/nylas/N1/commit/617e2aed095cc1f03ceeae237fb973690cfd2eaf

**Closed by jstejada** 2016-02-02 02:00 UTC
Labels: bug, in progress
