### ISSUE TITLE
Moving messages to folders other than Trash or Archive does not work under Exchange

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/N1#1740] opened 2016-03-15 13:09 UTC
When attempting to move a message to another folder (e.g. Spam) in an Exchange account, the action fails without an error; the message simply stays in place in the inbox. I can delete a message with the delete shortcut or button, and archive it similarly, but using the move message action fails.

Running Version 0.4.14-53cd69b (0.4.14-53cd69b) on OS X 10.11.3.

**Comment by jstejada** [comment] 2016-03-15 17:43
hi @fonnesbeck, thanks for reporting this. I am unable to reproduce this with my Exchange account.
Can you send me the logs from the Console and the output from the Activity Window to see if anything weird is going on?

Thanks!

**Comment by fonnesbeck** [comment] 2016-03-15 17:58
So, it turns out that the messages do move if you wait long enough. I had gone back and tried to replicate this again, clicking on move and selecting a mailbox three consecutive times, then after waiting for about 5 seconds the message does finally move.

I tried getting you a log, but selecting "View detailed log" from the developer menu did not bring up anything. Is there another way of accessing the log?

**Comment by jstejada** [comment] 2016-03-15 18:04
Yes, in the menu, select `Developer -> Toggle Developer Tools` and in there select the `Console` tab.
Also, select `Developer -> Open Activity Window` and let me know if you see any failed requests there.

Thanks!

**Comment by jstejada** [comment] 2016-03-15 18:04
this might be related to #1720

**Comment by jstejada** [comment] 2016-05-04 22:21
Hey @fonnesbeck —this should be fixed in 0.4.32, which shipped Monday. Feel free to file a new ticket if you are still having issues with the thread list not reflecting your actions properly.

**Closed by jstejada** 2016-05-04 22:21 UTC
