### ISSUE TITLE
No RPM package.

### ISSUE THREAD

**Issue by ment0s** [nylas/N1#455] opened 2015-11-24 22:06 UTC
Hi, I just would like to ask if you guys would want to make an RPM package as debian is not the only distribution and assuming that because browser reports "linux" it should not automatically assume that it should give out the .deb package. Please either provide .tar.gz or an choice between packages. Thanks

**Comment by mbilker** [comment] 2015-11-25 01:34
I use Arch Linux, but I built from source. There is a built in RPM building capability. It is commented out in `build/Gruntfile.coffee`. If you do a `script/bootstrap` and then a `script/grunt mkrpm` you should get an RPM. I will go test this in my Fedora VM.

**Comment by ment0s** [comment] 2015-11-25 01:38
ok great, could also someone make main website to detect other distro's  and offer a correct package ? Thanks

**Comment by mbilker** [comment] 2015-11-25 02:34
Also dupe of #107

**Comment by mbilker** [comment] 2015-11-25 02:39
I cannot make that. They currently do not offer an RPM package. There is the architecture to build an RPM package from Atom. The instructions for building an RPM are as follows:
```
sudo dnf install rpmdevtools fedora-packager nodejs npm libgit2-devel libgnome-keyring-devel
sudo npm install -g npm@2
sudo npm install -g inherits@2
git clone https://github.com/nylas/N1
script/build (takes a very long time)
script/grunt mkrpm
find rpm in /tmp/nylas-build/rpm/
```

**Comment by jstejada** [comment] 2015-11-25 18:01
hey guys, I'm going to close this as a duplicate of #107

**Closed by jstejada** 2015-11-25 18:01 UTC
