### ISSUE TITLE
Mark all as read with 'shift + [Mark As Read] button'

### ISSUE THREAD

**Issue by Shmuwol** [nylas/N1#1148] opened 2016-01-28 00:22 UTC
Mark all as read with 'shift + [Mark As Read button]'  or just add a 'select all' button and then use the [Mark As Read] button.

Thanks!

**Comment by bengotow** [comment] 2016-01-28 08:31
Hey! Select-all is coming, but there's already a basic version of it if you're using the Gmail keyboard shortcuts (`* a`). Stay tuned.

**Comment by emorikawa** [comment] 2016-01-28 18:34
Yes! Marking as duplicate of #1077

**Closed by emorikawa** 2016-01-28 18:34 UTC
