### ISSUE TITLE
Simple Way To Empty Trash & Junk Folders?

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2374] opened 2016-06-04 19:02 UTC
##### Are there any related issues?

...

##### What operating system are you using? 10.11.4
...

##### What version of N1 are you using? Version 0.4.40

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...Yes

**Comment by oldhickory30** [comment] 2016-06-04 19:04
Why is there no way way to delete / select all trash and or junk mail for removal.
Do we need a plugin to accomplish this simple everyday task?

**Comment by mbilker** [comment] 2016-06-05 21:52
Dupe of #599

**Closed by mbilker** 2016-06-05 21:52 UTC

**Comment by JordideBonis** [comment] 2018-04-09 12:11
Easy, I've found a way. 

Create a new folder, move all trash messages to the new one. Delete new folder.

It works!!!!
