### ISSUE TITLE
No option to delete all mail in folder

### ISSUE THREAD

**Issue by martinoj2009** [nylas/N1#600] opened 2015-12-07 06:53 UTC
I'm using Ubuntu 15.10. I'd like the ability to delete all mail in a sub-folder. I have a folder dedicated to temporary holding e-mail and it builds up over time. I would rather not go through all the mail, I'd like to be able to right-click the folder (text or icon) and select empty folder, like in any other e-mail clients.

**Comment by enoversum** [comment] 2015-12-07 21:19
Usually you have something like a button or the 'a' shortcut on a list to select all mail in a folder. I for one would love to mark e-mails as read on a folder I store newsletters to, so I +1 this request ;).

**Comment by grinich** [comment] 2015-12-12 21:06
@martinoj2009 what other email client has this feature?

**Comment by martinoj2009** [comment] 2015-12-14 02:18
@grinich Outlook. I do it at work when I'm done with all mail in a folder.

**Comment by lachlanjc** [comment] 2015-12-18 17:07
@grinich I'd love this functionality as well — on a Mac, Cmd-A is the standard shortcut to select all of almost anything, and it'd be great to Cmd-A on messages instead of checking all the boxes.

**Comment by jamen** [comment] 2015-12-28 14:05
+1

**Comment by schade** [comment] 2015-12-31 23:27
I like this idea, but think it should be more granular in a way similar to how inbox emails in Gmail are selected for manipulation. You can indeed select all emails; you can just as easily select all 'unread' emails or all 'read' email or even filtering by label or tag. Something to note about this feature in Gmail; it's default action is to select all, with all the other basic filters showing up on a right click.

**Comment by envygeeks** [comment] 2016-02-19 00:52
@grinich every email client on the planet that is a serious email client has a right click option to empty a folder, and even a empty trash button (of which this client doesn't have.) That's what other email client has the option.

**Comment by grinich** [comment] 2016-02-19 01:25
The Nylas sync engine and APIs don't support deleting mail, so we'll need to build that first. 

Sorry we're not a serious email app yet. I know your comment is in flippant jest, but I was asking because it's useful to have specific examples of how features are implemented so we can make sure our version matches the expected UX affordances for new users. The design challenge of an email app is deceptively complex. 

We get a surprising number of requests that are essentially OMG YOU GUYZ DONT HAVE MY FAVORITE SPECIFIC FEATURE YOU ARE SUCH WORTHLESS IDIOTS KTHXBAI and those are hard to understand and prioritize. Stuff like screenshots of other apps and longer details on use cases are what we'd love to receive. :)

**Comment by envygeeks** [comment] 2016-02-19 01:46
@grinich I was being as respectful as the tone of your initial response.  Examples are plentiful, visit any email client, Thunderbird, Geary, Outlook, Amazon Mail (web client.)  I do not think it needs to be a right click, just simply a button somewhere at least.

On the other parts, if you wish to take my comment personally and assume I was saying you aren't a serious email client, that is your decision.  I consider you heading towards being a serious email client to and was suggesting that if you wish to continue to be touted as serious than this is a critical feature. The idiot bit you were banging on about is a trap, I'll leave that unanswered.

Not all of us have email servers that delete messages automatically (like GMail) because it's a data violation to do that (even for trash) the user must choose to do it on their own accord, but they cannot so they must switch to our web clients to clear all that out, or do it from their phones.

We are one step from believing what sites are saying and recommending this client to our users, and that's this feature, if this feature gets enabled we are happy to overlook the bugs in the Github stuff and the false positives in phishing detection that are over-zealously caused by not considering same domains non-phishing for lists.

**Comment by jeffmcneill** [comment] 2016-05-28 04:59
The workflow for this in Gmail (besides the Spam and Trash folders, which do have a "Delete All" link at the top of the folder/label), is to select all in a view, and try to click the delete button, and then it asks if you want to delete everything in the folder (i.e., select all email, if there is more than has been selected, and then delete all).

Current functionality 28-May-2016 is that all messages can be selected within a label and then added to Trash. The only thing missing, really, is the ability to "Empty" the Trash. I realize that the sync engine is not currently geared to delete (just move things around) but at least for GMAIL the delete for labels, messages and threads is in the API: https://developers.google.com/gmail/api/v1/reference/

Either a right click on Trash, a right click on a specific mailbox's Trash, or a right click on one or more messages in the Trash (or all three) could enable the "Delete permanently" or "Take out the Trash" or "Landfill" or something to invoke deleting a thread or message (this functionality is already present in labels).

**Comment by jackiehluo** [comment] 2016-07-29 01:23
Merging into #886! I think Select All to perform X action is the right fix for this one.

**Closed by jackiehluo** 2016-07-29 01:23 UTC
Labels: enhancement-request

**Comment by envygeeks** [comment] 2016-07-29 01:42
I like that. Thanks!
