### ISSUE TITLE
Loud notification sound after waking computer from sleep

### ISSUE THREAD

**Issue by lazyatom** [nylas/N1#1910] opened 2016-04-08 07:58 UTC
If I've received several emails overnight, when I wake my computer and the notifications show, I get an extra-loud version of the normal notification sound. If I had to guess, I'd say it was multiple instances of the same notification sound being played at exactly the same time.

I'm using version 0.4.19-d41e72c on Mac OS X 10.1.4. The only third-party plugin installed is `n1-unsubscribe`. I'm running against a personal instance of the sync engine (using the nhurel/nylas-sync-engine Docker image, ID 41e88acc5105). The issue doesn't seem to be related to any specific mail provider; I see a single Nylas notification for multiple emails ("X new messages" or something like that), with a very loud, distorted version of the regular notification sound.

**Comment by bengotow** [comment] 2016-04-08 21:08
Hey! I can confirm the problem here is that while N1 is merging the notifications together as they arrive, it's not "de-duping" the sounds, so to speak. It can definitely result in the app playing the same sound back to back many times. Will get this fixed!

**Comment by lazyatom** [comment] 2016-04-08 21:21
Great - thanks!

**Comment by markbao** [comment] 2016-04-09 21:07
@lazyatom Sir, this is a feature. /s

**Comment by emitstop** [comment] 2016-05-09 19:10
Please fix this, I'm going to have to stop using the app because of the blaring noise it makes everytime i turn on my work computer.

**Comment by bengotow** [comment] 2016-07-29 01:24
This should be fixed—cheers!

**Closed by bengotow** 2016-07-29 01:24 UTC
Labels: bug

**Comment by lazyatom** [comment] 2016-07-29 12:55
Great!
