### ISSUE TITLE
Dark Theme | Text Color

### ISSUE THREAD

**Issue by ZarkBit** [nylas/N1#2301] opened 2016-05-23 09:39 UTC
-->Dark text on the Black Theme, shouldn't it become white or something?

##### Are there any related issues?

...No related issues (unless it's related to the negative images on the dark theme, would make sense to turn text into its opposite color)

##### What operating system are you using?
...Windows 7 64bit

##### What version of N1 are you using?
...0.4.40

--

**Bug?**
##### Do you have any third-party plugins installed?
...no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![4jehvnp 1](https://cloud.githubusercontent.com/assets/4160341/15466560/1f2cb132-20d2-11e6-8809-87c00e3758bd.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...I've used Postbox, eM Client, Thunderbird, Becky! Internet Mail, between many others, and I came across such issue.

**Comment by bengotow** [comment] 2016-05-25 20:40
Hey! We've actually seen this a few times... the problem is that the email itself contains styles forcing the text to a specific gray color, so N1 can't override it easily.

**Comment by jackiehluo** [comment] 2016-05-26 06:55
We switched the inversion for the dark theme because it didn't look great and caused some weird effects when the emails weren't displayed as they were intended, but I think we're just going to revert that because it's easier and at least avoids this problem!

**Comment by jeromecovington** [comment] 2016-06-08 17:06
Do we have any idea when this will be released? (Sorry, looked for info about N1's release process and came up empty, so am asking here.)

**Comment by jackiehluo** [comment] 2016-06-08 23:34
@jeromecovington Next release should be coming within the next week or so!

**Comment by bengotow** [comment] 2016-06-14 23:30
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!

**Closed by bengotow** 2016-06-14 23:30 UTC
Labels: done-pending-release
