### ISSUE TITLE
Typing Korean is problematic

### ISSUE THREAD

**Issue by seanchoe** [nylas/N1#288] opened 2015-10-29 23:21 UTC
Cannot type Korean properly. Please see the attached animated GIF.
Same character is being typed multiple times. It only happens from the second line.

![korean_typing](https://cloud.githubusercontent.com/assets/492928/10834720/f77dc6c4-7e58-11e5-877c-4c9406d5d7fb.gif)

**Comment by bengotow** [comment] 2015-10-29 23:59
Hi @seanchoe thanks for filing this issue - we're working on a fix for this. Technically, the problem is that we aren't properly supporting composition events. I'm going to merge this into that issue. https://github.com/nylas/N1/issues/62

**Closed by bengotow** 2015-10-29 23:59 UTC
