### ISSUE TITLE
No longer getting new mail after upgrading to 0.4.37-7d5ecac

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2227] opened 2016-05-15 20:29 UTC
##### Are there any related issues?

...

##### What operating system are you using? 10.11.4
...

##### What version of N1 are you using?
...0.4.37-7d5ecac 
--

**Bug?**
##### Do you have any third-party plugins installed? No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by oldhickory30** [comment] 2016-05-15 20:31
With the latest update I no longer get push notification, closing Nylas and reopening. syncs my folder but somewhat impractical! Moving forward please check your releases prior, this one is buggy as heck.

**Comment by bengotow** [comment] 2016-05-15 21:28
Hey! Do you see your new mail arrive in N1 at all? Or is it just the desktop notifications that do not appear?

**Comment by oldhickory30** [comment] 2016-05-15 21:35
No I do not see my new mail at all in any of my accounts, only refreshes when restarting Nylas. Even re-installed, had to switch back to my old client.

**Comment by ZacCoffman** [comment] 2016-05-16 01:27
Seeing the same on 0.4.37-7d5ecac

**Comment by oldhickory30** [comment] 2016-05-16 02:55
No new mail does not appear at all!

**Comment by stevehanson** [comment] 2016-05-16 04:12
Seeing this as well after updating to 0.4.37-7d5ecac earlier today. New mail only comes in when I restart N1. 

I don't know if it's related, but I saw this notification after updating N1:

![image](https://cloud.githubusercontent.com/assets/1691324/15280112/3d1c2848-1af2-11e6-8d2e-a23fa2897fde.png)

I ran my `config.json` through a JSON validator, which confirmed it was valid JSON. I then deleted the file anyway and restarted N1. It led me through the setup process, and I set up my accounts (3 Google accounts) again. Now, after about 30 minutes, I saw that message again. Not sure what's wrong with my config.json.

**Comment by emorikawa** [comment] 2016-05-16 04:33
It looks like there was an intermittent error where some accounts would get their delta streaming connections reset and lose the ability to get new messages. This has been fixed in 0.4.38. A patch release for this will be going out shortly

**Comment by stevehanson** [comment] 2016-05-16 04:43
Awesome. Thanks for the update!

**Comment by FrasSmith** [comment] 2016-05-16 05:42
Great! You guy's are quick. It's taken me all morning to realize that my email isn't updating and I find you've already fixed it. :-)

**Comment by bengotow** [comment] 2016-05-16 09:16
Hey! A fix for this just shipped in `0.4.38`—grab the update and let me know if you run into any issues. Going to leave this issue open for a bit in case other folks search for it. Cheers—

**Comment by France82** [comment] 2016-05-16 09:43
Ok now it works

**Comment by stevehanson** [comment] 2016-05-16 12:56
Working now for me too. Thanks!

**Comment by joshvickerson** [comment] 2016-05-16 16:29
I've updated to `0.4.38` and I'm having still having this problem. I have to restart Nylas to receive mail.

**Comment by oldhickory30** [comment] 2016-05-16 16:38
I'm also running into glitches with the latest update.

---

On May 16, 2016 at 10:29:50 AM MDT, Josh Vickerson <notifications@github.com> wrote:I've updated to 0.4.38  and I'm having still having this problem. I have to restart Nylas to receive mail.  —You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by pbolger** [comment] 2016-05-17 23:18
+1 I'm finding that the inbox doesn't update unless I select an individual account.

**Comment by jstejada** [comment] 2016-05-19 23:28
Hey folks, v0.4.40 has shipped with a fix and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!

**Closed by jstejada** 2016-05-19 23:28 UTC
Labels: done-pending-release
