### ISSUE TITLE
Bug Report: Button Icons missing

### ISSUE THREAD

**Issue by Chinney** [nylas/N1#805] opened 2015-12-22 18:35 UTC
Since the newest update I am missing some Icons on the `Archive`, `Apply Labels` and `Mark as unread` buttons for GMail aswell as the `Mark as unread`and `Move to folder` buttons for other email services (see image below). The `Trash` Icon appearing upon hovering over an email in the list view is missing aswell. OS: Linux - Ubuntu 15.10

![missin_icons](https://cloud.githubusercontent.com/assets/5702231/11962758/9c270dbc-a8e2-11e5-9d04-d905ecfc14b8.png)

**Comment by jstejada** [comment] 2015-12-22 18:46
hey @Chinney , this seems to be a duplicate of #732 

can you try closing N1, removing ~/.nylas and reinstalling?

**Comment by Chinney** [comment] 2015-12-24 22:11
Yes. Worked. Merry Christmas.

**Closed** 2015-12-25 17:41 UTC
Labels: bug, platform-linux
