### ISSUE TITLE
Feature Request: Refresh/Fetch Button

### ISSUE THREAD

**Issue by tpaulus** [nylas/N1#771] opened 2015-12-18 22:44 UTC
There is currently no way to force a refresh for IMAP accounts. A refresh/fetch button or option would be very nice!

**Comment by zlatkobijelic** [comment] 2015-12-18 22:55
+1

**Comment by jstejada** [comment] 2015-12-18 22:56
Hi @tpaulus, thanks for contributing! -- N1 retrieves new mail via a streaming connecting to the sync engine, so new email is "pushed" to the app as soon as it's available. There isn't any polling, periodic checking for mail, etc. As soon as it's pulled through the sync engine, it's visible in the app.

In the future we may add more info about the sync state, but for no a refresh button would just be a no-op.

Thanks for the feedback! Also, closing as a dupe of #686

**Closed by jstejada** 2015-12-18 22:56 UTC
Labels: feature-request

**Comment by sea-speak** [comment] 2016-05-15 23:14
This is a serious problem for me in Nylas - my Gmail accounts periodically don't refresh at all until I quit and relaunch Nylas. I don't understand the technical reasons why a 'force refresh' button wouldn't work, but it sure would be nice to have one that works. As it is, CTRL-Q is my force refresh button.

**Comment by brianjking** [comment] 2016-05-16 00:12
This is also a point of frustration for me using Nylas N1 as well. Really hope this gets implemented.

Thanks for all the hard work!

**Comment by jstejada** [comment] 2016-05-16 03:26
hi @sea-speak , @brianjking, this is kwown issue in the latest version, we are working on a fix: #2227

**Comment by sea-speak** [comment] 2016-05-16 03:50
Thanks - in my experience, this is not only an issue with the latest version. The latest version is worse. But prior versions still wouldn't update the inbox (sometimes) for quite a while. 






On Sun, May 15, 2016 at 8:27 PM -0700, "Juan" <notifications@github.com> wrote:












hi @sea-speak , @brianjking, this is kwown issue in the latest version, we are working on a fix: #2227
