### ISSUE TITLE
Version 0.4.19 detected as newer than 0.4.25

### ISSUE THREAD

**Issue by jmfederico** [nylas/N1#1939] opened 2016-04-13 02:21 UTC
I just installed version Version 0.4.25-a22631a and as soon as I open it, the app asks me to update to version 0.4.19-d41e72c, which is older.

When I close the app and open it again, the older version opens. So far I locked the app file using finder's lock flag to avoid the downgrade.

I'm using OS X 10.11.4.

**Comment by ArNz8o8** [comment] 2016-04-13 04:43
Yep, got the same issue here. 4.19 didn't detect a newer version so I installed 4.25 by hand. After it was done, it updates back to 4.19 again...

**Comment by FlorianBrinkmann** [comment] 2016-04-13 09:37
I have the same issue …

**Comment by PwnArt1st** [comment] 2016-04-13 11:12
Same here

**Comment by loris** [comment] 2016-04-13 11:22
Confirmed:
![](https://dl.dropboxusercontent.com/spa/tqch4axi0t55dpk/w90xc4_z.png)

**Comment by France82** [comment] 2016-04-13 14:31
same here
Windows 10 64bit

**Comment by czpukmen** [comment] 2016-04-13 15:14
Same issue on Windows 10 Pro 64bit. Works fine on MacOS 10.11.5 Beta 1.

**Comment by bengotow** [comment] 2016-04-13 17:20
Hey folks—sorry for the hassle. With the 0.4.25 release we were testing an update to our auto-updaters that allow us to slowly roll out a new release across the user base. It looks like there was a bug where if you downloaded the new version manually before it was auto-assigned to you by the updater, the Mac OS X version of N1 would try to downgrade to the version it was assigned.

We've pushed 0.4.25 to everyone so this shouldn't be an issue anymore. If you quit and relaunch N1 without installing the update, you won't get the bar again. Sorry for the hassle—we'll be fixing this on the backend this week.

**Closed by bengotow** 2016-04-13 17:20 UTC
