### ISSUE TITLE
Gmail stopped syncing today / Feedback option not working

### ISSUE THREAD

**Issue by psoiree** [nylas/N1#902] opened 2016-01-05 15:43 UTC
Hello :)

I'm more than happy that I found Nylas N1 because Sparrow (shut down 2 years ago) started to make more problems than profit and I didn't want to buy Airmail after reading all these nasty comments about it's functioning. 

Everything was ok until today - N1 suddenly stopped syncing gmail account and is doing nothing than showing me the spinning wheel. I have the current version from website.

Also there's a problem with Feedback option. Clicking on question-mark or "send us feedback" through help doesn't work. It shows only blank window.

![screen shot 2016-01-05 at 16 34 00](https://cloud.githubusercontent.com/assets/16561052/12119313/458d70b0-b3cb-11e5-94e6-4ac387513fbd.png)

**Comment by psoiree** [comment] 2016-01-05 16:36
Deleting account (in N1) and resyncing helped. Feedback window still blank.

**Comment by bengotow** [comment] 2016-01-05 18:00
Hey @psoiree — thanks for posting this. It sounds like something happened to the sqlite database that backs N1. I'll see if we can reproduce this on our end.

**Comment by bengotow** [comment] 2016-01-05 18:00
Related: #863

**Comment by grinich** [comment] 2016-01-07 17:43
Closing as we can't reproduce. Glad you got it fixed!

**Closed by grinich** 2016-01-07 17:43 UTC

**Comment by psoiree** [comment] 2016-01-11 11:12
The problem happened again :(

**Comment by rahatarmanahmed** [comment] 2016-02-04 18:55
I just had this happen to me as well.
![monosnap_2016-02-04_12-54-50](https://cloud.githubusercontent.com/assets/3174006/12825982/844c1114-cb3e-11e5-83df-40e25c414326.png)


Nylas Version 0.3.45-3b5880e (0.3.45-3b5880e)
OS X El Capitan

**Comment by jstejada** [comment] 2016-02-04 19:33
hey @rahatarmanahmed , if this happens again, can you send us the logs? They are accessible via `Developer -> Toggle Developer Tools` and select the `Console` tab
