### ISSUE TITLE
Transparent window on launch

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1100] opened 2016-01-22 02:38 UTC
A user is reporting that upon launching N1 for the first time, the main setup window is shown as transparent. Here's a screenshot of the issue.

![screen 20shot 202016-01-21 20at 208 25 03 20pm](https://cloud.githubusercontent.com/assets/92417/12501071/19e08272-c06e-11e5-99c8-9c832aff6985.png)

**Comment by bengotow** [comment] 2016-04-14 20:27
Closing since we haven't been able to reproduce and a lot has changed since this was filed.

**Closed by bengotow** 2016-04-14 20:27 UTC
Labels: bug, needs-steps-to-reproduce
