### ISSUE TITLE
Rendering of inline graphics isn't working

### ISSUE THREAD

**Issue by tschf** [nylas/N1#462] opened 2015-11-25 05:24 UTC
I'm on Ubuntu 14.04 x64, version 0.3.23-94e0cb9
I've noticed inline images don't seem to be rendered in the client (though, if I right click and hit `Save image...`.. the image is saved with the expected image)

N1:
![n1-inline](https://cloud.githubusercontent.com/assets/1747643/11389048/3011a8ec-9390-11e5-82b1-560c53c04324.png)

Gmail:
![](https://cloud.githubusercontent.com/assets/1747643/11389082/7e8869f2-9390-11e5-93dc-b7f97d874329.png)

I've seen the related issue on Trello https://trello.com/c/m9IFvC60/39-inline-images-in-composer (and a similar ticket on here) but I think that's different.

**Comment by tschf** [comment] 2015-11-25 05:33
Actually, after doing a couple of more tests - it seems only the first time you load the message it appears broken. Click out and in again and it's working.

**Comment by davidmaneuver** [comment] 2015-12-01 14:16
I'm experiencing the same problem. The image src is referring to /Users/<User>/.nylas/downloads/codaouu2zpkzgzmghoabimw99/image001.png. But there is no such file.

**Comment by bengotow** [comment] 2015-12-07 19:27
Hey folks—I've been able to reproduce this. It looks like in some scenarios, we're resolving the inline image to it's path on disk before the file write has finished, which results in the image not being displayed. A fix should be incoming soon.

**Closed** 2015-12-07 23:00 UTC
Labels: bug

**Comment by davidmaneuver** [comment] 2015-12-21 10:37
I'm still experiencing problems with this. The path looks correct but the image is not present on disk. The sender is set to always show images. 
As you can tell the email is sent from Outlook, could be relevant.

I'm on version 0.3.23-b11131d

![screen shot 2015-12-21 at 11 28 22](https://cloud.githubusercontent.com/assets/590050/11928783/7fa60196-a7d6-11e5-9e06-173b51955983.png)

**Comment by dfleury** [comment] 2016-01-12 14:09
Same problem here. My gmail account is enterprise (@corp.globo.com), this may be relevant too

**Comment by Muurtegel** [comment] 2016-03-30 16:55
I experience the same thing. Also on a business account.

**Comment by dennisjanssen** [comment] 2016-03-31 06:55
Same here, also Google Apps account.

**Comment by lashae** [comment] 2016-04-11 09:01
Same here for Google Apps account. I cannot view inline images however they show up when message is viewed via Gmail interface.
