### ISSUE TITLE
Programing Pannel Appear

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2665] opened 2016-07-23 06:38 UTC
##### Are there any related issues?

...

##### What operating system are you using?
...OSX 10.11.6

##### What version of N1 are you using?
...0.4.45-7637265)
--

**Bug?**
##### Do you have any third-party plugins installed?
Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
 No
...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? No
...

**Comment by grinich** [comment] 2016-07-23 20:02
dupe of 2666

**Closed by grinich** 2016-07-23 20:02 UTC
