### ISSUE TITLE
Suddenly terminate itself when I click the icon in dock when it's indeed open 

### ISSUE THREAD

**Issue by jincwang** [nylas/N1#514] opened 2015-11-30 19:46 UTC
Normally, if I don't want to see the application window, I just click the red cross (I don't like to minimize it). And on the dock, the small black spot implys it's still running. So if I want to check the mail, normally I just need to click the icon on the dock and the window shows up again, which is what I always do for the system's email app. But for Nylas N1, when I click it, it always terminates itself. And I have to click again to launch the app, which makes me unhappy. I like your app because it's more user-friendly in some details compared to the system's email app. Can you fix this problem? Thank you.

**Comment by bengotow** [comment] 2015-11-30 19:59
Thanks for reporting this! Closing as a duplicate of #481

**Closed by bengotow** 2015-11-30 19:59 UTC
