### ISSUE TITLE
Unread messages in Trash contribute to unread number in inbox

### ISSUE THREAD

**Issue by thenaterhood** [nylas/N1#1726] opened 2016-03-14 21:30 UTC
- What operating system are you using?
Linux

- What version of N1 are you using?
0.4.14-53cd69b

**Bug?**
- Do you have any third-party plugins installed?
None

- Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Unsure. The only accounts I have in N1 are Gmail.

- Is the issue reproducible with a particular attachment, message, signature, etc?
Happens repeatedly when I delete unread messages without marking them read. Marking them read in Trash makes the unread count for the inbox disappear. Oddly, it doesn't happen with every message, just periodically without any apparent reason.

![nylas-unread-bug](https://cloud.githubusercontent.com/assets/2584772/13760584/44515994-ea0a-11e5-841a-57b919f21716.png)

**Comment by mgroves84** [comment] 2016-03-14 23:15
I am seeing the same issue on Mac OS X with this build.

**Comment by bengotow** [comment] 2016-03-15 00:24
Hey folks, yep - this is caused by #1718. We should have a fix for this on master by tomorrow, but it may take a week or so for it to get into a stable release. Stay tuned!

**Comment by fonnesbeck** [comment] 2016-03-16 17:53
Not sure if this is related at all, but I am observing odd behavior associated with *read* messages being sent to the trash becoming unread, and then triggering this issue. I have my mark as read delay set to "instant", but after spending time reading a message and sending it to the trash, I happened to notice the unread count in the inbox increment (as this issue describes), so when I went to look at the deleted messages, noticed that the message I had just read and deleted was changed to unread.

**Comment by bengotow** [comment] 2016-03-19 00:19
This shipped in `0.4.16`, a small update that went out a few minutes ago. Enjoy!

**Closed by bengotow** 2016-03-19 00:19 UTC
Labels: done-pending-release
