### ISSUE TITLE
Email Notification Minor Issue

### ISSUE THREAD

**Issue by gkumar7** [nylas/N1#1030] opened 2016-01-15 05:26 UTC
Email notifications work fine when the email is from someone else. If I send an email to myself through gmail for example, no email notification is provided by N1. 

I am running archlinux with gnome 3.18.2.

**Comment by mbilker** [comment] 2016-01-15 18:55
Thanks for the more clear report @gkumar7. Does the message appear as read when it shows up in N1?

I know for my own personal mail if the message is marked as read when N1 receives it, it will not display a notification.

**Comment by gkumar7** [comment] 2016-01-15 19:28
Nope, it appears as unread, such as the following example:

![unread-email](https://cloud.githubusercontent.com/assets/5412836/12362988/dd119f20-bb8b-11e5-80a8-eca2ebd0569b.png)

**Comment by mbilker** [comment] 2016-01-15 20:31
@gkumar7 That is odd. I just tried this myself from the Gmail web interface, and it worked just fine. I don't  know why this is not working.

**Comment by bengotow** [comment] 2016-02-06 08:47
Hey @gkumar7 — this is actually intended behavior, but maybe it shouldn't be. The logic is right here: https://github.com/nylas/N1/blob/stable/internal_packages/unread-notifications/lib/main.coffee#L104

**Comment by gkumar7** [comment] 2016-02-12 21:20
Ah, thank you for pointing this out! I feel including this feature really depends on the person. Could it be listed as an option under preferences?

**Closed** 2016-06-02 19:07 UTC
Labels: linux
