### ISSUE TITLE
I can not open mails with big file size attachments.

### ISSUE THREAD

**Issue by omerozturk0** [nylas/N1#415] opened 2015-11-17 11:34 UTC
I can not open mails with big file size attachments. Program is restarting when I trying open it. I want to save all attachments my pc but i can not it too. How can i do it?

https://youtu.be/p_ahYW-pZng

**Comment by mbilker** [comment] 2015-11-17 15:31
What OS? I know where the log file is on Linux (`/tmp`), but I am unaware of the temporary folder for other OS's.

**Comment by omerozturk0** [comment] 2015-11-17 15:40
windows 10 and thats folder C:\Users\CurrentUser\AppData\Local\nylas\

**Comment by mbilker** [comment] 2015-11-17 15:41
Open up the Developer Console and what file does the first line say. It should end with something like `Nylas-N1-13578.13737.log`.

**Comment by omerozturk0** [comment] 2015-11-17 15:46
C:\Users\CurrentUser\AppData\Local\Temp\Nylas-N1-6240.5472.log

**Comment by mbilker** [comment] 2015-11-17 15:48
Could you post the log? It does not contain any passwords, but it will contain the error.

**Comment by omerozturk0** [comment] 2015-11-17 15:54
its my log file
[log.txt](https://github.com/nylas/N1/files/36876/log.txt)

**Comment by mbilker** [comment] 2015-11-17 15:56
Hmm. I don't see the error in the log. Could you get the filename, then trigger the crash and upload the log here.

If that log is from a crash, then the error isn't logged which concerns me.

**Comment by omerozturk0** [comment] 2015-11-17 19:30
im done...
[log.txt](https://github.com/nylas/N1/files/37102/log.txt)

**Comment by mbilker** [comment] 2015-11-18 01:06
I don't see an error in the log. That is very odd. How big is the attachment?

**Comment by omerozturk0** [comment] 2015-11-18 01:12
6 large pixelled images. Its file size 15.6mb. I have too many mails like this but i get error with this. I checked it gmail but there is running smoothly and i can see smoothly attachments there.

**Comment by mbilker** [comment] 2015-11-18 01:17
I wonder if Node crashed.

**Comment by mbilker** [comment] 2015-11-18 01:17
What OS are you on?

**Comment by omerozturk0** [comment] 2015-11-18 01:17
windows 10

**Comment by omerozturk0** [comment] 2015-11-18 01:19
not error report. Program restart when i trying open that's mail attachments

**Comment by mbilker** [comment] 2015-11-18 01:22
Yep. Node crash.

**Comment by mbilker** [comment] 2015-11-18 01:22
I don't know how to fix that issue. I am sorry.

**Comment by omerozturk0** [comment] 2015-11-18 01:25
Thanks for helps :+1:

**Comment by bengotow** [comment] 2015-11-21 02:17
Hey @omerozturk0 — it looks like this might be related to https://github.com/atom/electron/issues/1562.

How large is that image? I'll see if I can reproduce.

**Comment by omerozturk0** [comment] 2015-11-21 12:56
6 large pixelled images. Its file size 15.6mb.

**Comment by bengotow** [comment] 2015-11-23 18:42
Thanks—it looks like this is an upstream bug with Electron on Windows. In the meantime, we will add a filesize check... we really shouldn't be trying to display 15MB images without a more sophisticated way of generating previews.

**Comment by omerozturk0** [comment] 2015-11-23 23:28
thanks for interesting this topic.

**Comment by bengotow** [comment] 2015-11-25 00:29
It looks like this has been fixed in Electron upstream, and I've limited the max size of images we display inline to 5MB in `bd2dfef7ceb56f2de97f3ade43adfcdfb97fdf6f`

**Closed by bengotow** 2015-11-25 00:29 UTC
Labels: bug
