### ISSUE TITLE
Folders appearing in N1 that are not on server!

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2616] opened 2016-07-13 21:38 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Mac OSX
...

##### What version of N1 are you using?
4.45
...

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by oldhickory30** [comment] 2016-07-13 21:40
I'm still having an issue where I have a folder appearing in N1 however it is not on the server. Any suggestion how to remove it. When I try it generates an error and can't remove!

**Comment by jackiehluo** [comment] 2016-07-13 21:43
Duplicate of your other issue, #2475! We'll look into it.

**Closed by jackiehluo** 2016-07-13 21:43 UTC
