### ISSUE TITLE
GUI freezes on OS X Yosemite

### ISSUE THREAD

**Issue by charlie-wasp** [nylas/N1#1056] opened 2016-01-17 07:50 UTC
Hello,

I've ran into problem - N1 suddenly freezes and doesn't react on anything: I can't open letters, can't open mailboxes, delete, mark unread and etc. buttons don't work too, however I can scroll through my mail :) And I can write new mail too.

When I said "suddenly" I mean literally that, I don't know which of my actions cause it.

Did it happened to someone else?

**Comment by jamms-github** [comment] 2016-03-03 17:54
I am on El Capitan, it freezes and become unresponsive as well.
1.) I launch the application from "Applications" folder.
2.) The application opens as expected.  After a pause it begins syncing my previously added gmail account.
3.) The "spinning indicator" by the "Syncing your mailbox..." message freezes. GUI becomes unresponsive
4.)  After some time an "N1 is not responding" popup presents a choice to "Keep Waiting" or "Close"
I will include 2 successive crash logs generated by OSX "force close" error report to apple feature as well as a screenshot of the result from first "crash"
![screen shot 2016-03-03 at 11 12 49 am](https://cloud.githubusercontent.com/assets/17621084/13503692/751c919c-e136-11e5-8f66-0e373fa30c39.png)
[n1_crash.log.txt](https://github.com/nylas/N1/files/157345/n1_crash.log.txt)
[n1_crash_01.log.txt](https://github.com/nylas/N1/files/157346/n1_crash_01.log.txt)

**Comment by bengotow** [comment] 2016-05-03 01:03
I think the underlying issue here was caused by 765d9f30fc5be75b97e3254d37a6b57fbc341582 and should be fixed in the next release.

**Comment by jackiehluo** [comment] 2016-07-29 01:09
Hey! Closing this issue for now because it should be fixed—let us know if it's not.

**Closed by jackiehluo** 2016-07-29 01:09 UTC
Labels: needs-steps-to-reproduce, os-x
