### ISSUE TITLE
Popover window stuck after sharing thread

### ISSUE THREAD

**Issue by nblackburn** [nylas/N1#2899] opened 2016-10-04 15:27 UTC
The popover window when sharing a thread is not removed after clicking the "Share this thread" checkbox.

---

##### What operating system are you using?

OSX El Capitan (_10.11.5_)

##### What version of N1 are you using?

Version 0.4.56-816edde (_0.4.56-816edde_)

##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

**Comment by bengotow** [comment] 2016-10-04 17:16
Hey! I think when you click the checkbox, you still (usually) need to copy the URL from the box below, so this is working as intended. (Right now, you just have to click outside the popover when you're done copying the URL.) Maybe we should change this!

**Comment by nblackburn** [comment] 2016-10-04 17:36
@bengotow I didn't explain this in the best way because i was in a rush. Basically what happens is once you have checked that box and clicked outside of the popover, it should be removed but currently isn't.

**Comment by jstejada** [comment] 2016-10-04 18:11
hey @nblackburn , this should be fixed in the next release!

**Comment by bengotow** [comment] 2016-10-25 17:37
This has been fixed in 0.4.59, which we shipped earlier today. Enjoy!

**Closed by bengotow** 2016-10-25 17:37 UTC
Labels: done-pending-release
