### ISSUE TITLE
Programing Panel Appears

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2664] opened 2016-07-23 06:33 UTC
##### Are there any related issues?

...

##### What operating system are you using?
...OSX 10.11.6

##### What version of N1 are you using?
...0.4.45-7637265)
--

**Bug?**
##### Do you have any third-party plugins installed?
Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
 No
...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? No
...

**Comment by oldhickory30** [comment] 2016-07-23 06:37
While working through a message the developer panel appears for no reason. 
This is happing more frequently
![panelerror](https://cloud.githubusercontent.com/assets/16170272/17076351/9bb6ec84-506d-11e6-86a4-5f723c69a478.jpg)
, very frustrating!

**Comment by grinich** [comment] 2016-07-23 20:02
dupe of 2666

**Closed by grinich** 2016-07-23 20:02 UTC
