### ISSUE TITLE
Is "Process all Mail" bugged?

### ISSUE THREAD

**Issue by eyalsk** [nylas/N1#1521] opened 2016-03-01 16:14 UTC
Hello,

I tried to use it in previous releases and also the most recent release (0.4.10) and it seems like it's not really following the rules but making a mess.

The mails are not really where they should be! I have to use outlook to sort it out correctly.

**Comment by bengotow** [comment] 2016-03-01 18:45
Hi @eyalsk — can you elaborate on what seems to be wrong with the mail rules? Without more info we probably won't be able to fix this.

**Comment by eyalsk** [comment] 2016-03-01 19:25
@bengotow sure! 

**Here I'm defining a general rule:**

![rules3](https://cloud.githubusercontent.com/assets/3756641/13438169/851f35be-dff0-11e5-854a-bf3a1556dc42.png)

**Here I'm defining a more specific rule with the same domain and put it below the above rule in the list:**

![rules2](https://cloud.githubusercontent.com/assets/3756641/13438203/b23465e2-dff0-11e5-89cd-1505583b01ed.png)

_What I expected to happen is for the program to process the first rule and only then process the second one._

**Now the results I'm getting is as follow:**

![mail2](https://cloud.githubusercontent.com/assets/3756641/13438539/24adcd7e-dff2-11e5-9904-e1418931d715.png)

![mail3](https://cloud.githubusercontent.com/assets/3756641/13438544/272f3cf4-dff2-11e5-892e-62acfac283e4.png)

**Now, look at this rule:**

![rules4](https://cloud.githubusercontent.com/assets/3756641/13438669/a93e0626-dff2-11e5-83ae-4f6a17df2e17.png)

**The above rule has nothing to do with the domain @openu.ac.il and yet mails that aren't belong there do appear there as shown below.**

![mail1](https://cloud.githubusercontent.com/assets/3756641/13438533/1ccb5cfc-dff2-11e5-8896-fdcccdf4d941.png)

**Finally, All mails from "Lior.Kamma@openu.ac.il" should appear in the folder OpenU Ashnav.**

**Comment by eyalsk** [comment] 2016-03-04 13:51
@bengotow are you looking into it?

**Comment by eyalsk** [comment] 2016-03-10 11:58
@bengotow what's going on? why it's still tagged with needs-steps-to-reproduce? do you need more information?

**Comment by eyalsk** [comment] 2016-03-10 23:30
Well, thank you for a wonderful client but I'm going back to outlook! I have many mails and to manage them I use rules, I use them heavily and unfortunately N1 doesn't handle my cases as good as outlook simply because when you click the sync button it's making a mess instead of actually sync'ing it.

I'll probably watch it and wait for this to be fixed because I really love the product, I think it's amazing.

**Comment by bengotow** [comment] 2016-04-14 20:47
Hey! Thanks for reporting this and posting more info! We fixed one critical issue with "Process All Mail" in 0.4.25, but it seems like this is a different issue. I'll see if we can reproduce this now that we have all the information. Thanks!

**Comment by bengotow** [comment] 2016-05-31 23:42
Hey! Looks like this should be resolved by 856334c08890de3a4e2d8004494f6c66f944c2ed and b160f6d181a8a7e0a21bc97ee485a674f7b889d8.

**Comment by eyalsk** [comment] 2016-06-01 02:41
That's wonderful! I'll try it again when I'll have time, took long time to fix it but nonetheless, thank you! :)

**Comment by bengotow** [comment] 2016-06-14 23:31
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!

**Closed by bengotow** 2016-06-14 23:31 UTC
Labels: bug, done-pending-release
