### ISSUE TITLE
Add new labels from mail rules page

### ISSUE THREAD

**Issue by OJFord** [nylas/N1#3160] opened 2017-01-16 20:30 UTC
mac OS 10.12.2; N1 0.4.402

**Feature Request**
##### Does this feature exist in another mail client or tool you use?

Gmail filters can be created to apply a new label, created at the point of creating the filter.

In N1, one has to leave settings entirely, add the label in the side bar, go back into settings, back into mail rules, select the Gmail account again, find the rule again, and then add the action.

**Comment by emorikawa** [comment] 2017-01-17 16:34
Duplicate of https://github.com/nylas/N1/issues/3160

**Closed by emorikawa** 2017-01-17 16:34 UTC

**Comment by OJFord** [comment] 2017-01-17 16:42
@emorikawa This is #3160... 😆

**Comment by OJFord** [comment] 2017-01-17 18:43
Oh - I assume you meant #2954 - I didn't see that previously.
