### ISSUE TITLE
Invert mail view order

### ISSUE THREAD

**Issue by mickaellecolazet** [nylas/N1#3174] opened 2017-01-17 16:16 UTC
Hello, 

It would be great if it were possible to invert the order of viewing of the mail discussions.
Not from le oldest to the newest from top to bottom, but inverse.

Thanx.
Regards.

**Comment by emorikawa** [comment] 2017-01-17 16:21
Agreed! Dupe of https://github.com/nylas/N1/issues/1071

**Closed by emorikawa** 2017-01-17 16:21 UTC
Labels: enhancement-request
