### ISSUE TITLE
"Dependency is not satisfiable: libgcrypt11" when installing deb package on ubuntu 15.10

### ISSUE THREAD

**Issue by kornosaurus** [nylas/N1#156] opened 2015-10-23 09:28 UTC
I get this error trying to install N1:
![Error message](https://cloud.githubusercontent.com/assets/10253840/10688980/56ff0a8a-7978-11e5-8d23-de1c0dad1800.png)

On fresh install of ubuntu 15.10

**Comment by nbostrom** [comment] 2015-10-23 10:06
I solved this by first installing libgcrypt11 from an older ubuntu version first:

32bit: https://launchpad.net/ubuntu/+archive/primary/+files/libgcrypt11_1.5.3-2ubuntu4.2_i386.deb
64bit: https://launchpad.net/ubuntu/+archive/primary/+files/libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb

Ubuntu is transitioning from libgcrypt11 to libgcrypt20 and have set up a linked package during the transition. The nylas package doesn't seem to understand the link though (my understanding of deb packages is minimal). I don't know if this is an Ubuntu bug or a bug in the N1 deb package.

**Comment by kornosaurus** [comment] 2015-10-23 10:08
This fixed it for me too..

**Comment by kornosaurus** [comment] 2015-10-23 14:57
This seems to be a electron issue rather then N1.. Closing

**Comment by clobrano** [comment] 2015-10-27 08:18
This affects also Ubuntu 15.04.
May I ask you why you close this ticket? In my opinion N1 should not depend on obsolete version of libgcrypt. A real solution should be to compile N1 against libgcrypt newer version.

**Comment by renantardelli** [comment] 2015-11-01 12:32
clobrano is right from my point of view
Ubuntu suggest to contact software maintainer rather then messing with security packages, but this is not only happening to N1, Spotify and others are having same issue...

**Comment by kornosaurus** [comment] 2015-11-04 08:01
Ill reopen this issue.. from my understanding this was something related to electron so it was affecting all electron applications.. But I can't remember where i saw it, neither can I find it.. I must have been dreaming!

**Comment by thelfensdrfer** [comment] 2015-11-13 09:18
Duplicate of #55

**Comment by bengotow** [comment] 2015-11-13 19:27
Closing this as a duplicate of https://github.com/nylas/N1/issues/55—we're working on a fix for this and should have it resolved soon, but you can track the conversation there.

**Closed by bengotow** 2015-11-13 19:27 UTC

**Comment by bharadwaj509** [comment] 2016-05-17 17:52
I installed "libgcrypt11" and able to install brackets software... But is there a way to change the dependency of brackets to libgcrypt20....

**Comment by Humairah-Mujawar** [comment] 2016-10-24 11:15
I installed "libgcrypt11" and now able to install staruml software. Thanks

**Comment by DracsNightOut** [comment] 2017-01-14 21:26
bharadwaj509 I installed "libgcrypt11" and was unable to install brackets. Did you ever find out if it is possible to change the dependency to libgcrypt20?

**Comment by anastiel** [comment] 2017-04-22 21:40
thanks so much
