### ISSUE TITLE
GMAIL: "All messages" has emails with label "trash"

### ISSUE THREAD

**Issue by ZaidoR1** [nylas/N1#1037] opened 2016-01-15 11:18 UTC

**Comment by mbilker** [comment] 2016-01-15 17:27
These messages are part of the "All Mail" IMAP Folder, which is Gmail's gigantic folder of every message under IMAP.

**Comment by ZaidoR1** [comment] 2016-01-16 11:40
yes, but email with label "trash" (email in trash folder) are not shown in "all messages"

**Comment by grinich** [comment] 2016-01-25 23:25
dupe of #1135

**Closed by grinich** 2016-01-25 23:25 UTC
