### ISSUE TITLE
Restart and Install Update Not Working

### ISSUE THREAD

**Issue by tgaeta** [nylas/N1#569] opened 2015-12-04 15:21 UTC
Clicking install update closes the window but doesn't appear to kill the process and update the app. When I reopen the app, the notice to update still persists.

##### OSX Yosemite 10.10.5 (14F1021)

![bug](https://cloud.githubusercontent.com/assets/9040988/11593139/9cf682ca-9a70-11e5-87e1-b4b65b9045e4.gif)

**Comment by gcleveland** [comment] 2015-12-04 16:07
Yes I have the same issue. Os X 10.11.2 beta 5

**Comment by qbunt** [comment] 2015-12-04 20:02
+1 on 10.9.5 for me.

**Comment by mbilker** [comment] 2015-12-04 22:12
Could you guys open the DevTools and pull the Log File name out of the Console tab. It should be the first logged message in the Console tab.

**Comment by bengotow** [comment] 2015-12-04 22:48
Hey folks—thanks for reporting this. This is really interesting. Can you check `Console.app` just after pressing the Install button and see if there are any logs listed there? Offhand, it looks like the app is not quitting gracefully, so the install process is never starting.

**Comment by tgaeta** [comment] 2015-12-05 00:27
That was the case. After pressing install and then force quitting the app
it upgraded. Sorry, didn't get the log.

**Comment by bengotow** [comment] 2015-12-29 22:26
Hey folks—this was caused by a bug that blocked the app from exiting and has been resolved. Will be fixed in the next update.

**Closed by bengotow** 2015-12-29 22:26 UTC
Labels: bug

**Comment by tgaeta** [comment] 2015-12-29 22:28
:+1:

**Comment by rushter777** [comment] 2016-02-24 14:03
I am having this issue also. I am not sure how you were able to press install and then hit force quit because as soon as I hit install it closes and does not appear on my Force Quit list. I also just force quit the app and then tried to update but no change. Please help me fix this.

**Comment by skeltont** [comment] 2016-02-26 17:21
Yeah I'm still having this issue as well. No matter if I click the update button or go into the menu to install and restart it will still just close and do nothing.

**Comment by conchan** [comment] 2016-03-15 13:54
:+1: Still having this issue as well

**Comment by gcleveland** [comment] 2016-03-15 14:11
I found that simply deleting the app and re-installing didn't work. I had to 'view hidden files' in finder, and delete the system library file. Then re-install the latest version. That fixed it for me. 
Alternatively you could use one of those app uninstall utilities which will do the clean up for you. 
Grant

**Comment by rushter777** [comment] 2016-03-17 01:28
Could you be a little more specific as to the location of the file to delete?

> On Mar 15 2016, at 11:11 pm, Grant Cleveland
&lt;notifications@github.com&gt; wrote:  
I found that simply deleting the app and re-installing didn't work. I had to
'view hidden files' in finder, and delete the system library file. Then re-
install the latest version. That fixed it for me.  
Alternatively you could use one of those app uninstall utilities which will do
the clean up for you.  
Grant  
  
  
&gt; On 15 Mar 2016, at 13:54, Connie Chan &lt;notifications@github.com&gt;
wrote:  
&gt;  
&gt; Still having this issue as well  
&gt;  
&gt; —  
&gt; You are receiving this because you commented.  
&gt; Reply to this email directly or view it on GitHub:  
&gt; https://github.com/nylas/N1/issues/569#issuecomment-196830223  
&gt;  

>

> —  
You are receiving this because you commented.  
Reply to this email directly or view it on GitHub:  
<https://github.com/nylas/N1/issues/569#issuecomment-196838572>![](https://git
hub.com/notifications/beacon/AQpTO6hk8TFk-
WGrYYsk8D19TMbiNsnoks5ptr4dgaJpZM4Gu7lP.gif)

**Comment by gcleveland** [comment] 2016-03-17 09:35
In finder, select your desktop.
Then in the window menu click ‘Go>Enclosing Folder’.
That should give you access to the applications library folder. Or you can just do a search for ‘N1’ and have a hunt around.
I can’t be more specific than that because I have already deleted mine.

Otherwise look for an app like Cleanmymac or similar.

**Comment by mimoo** [comment] 2016-05-04 19:10
yup, everytime I click to update the app, it closes, relaunches, and still show me the update banner

**Comment by mbilker** [comment] 2016-05-05 01:19
@mimoo They may not have updated the autoupdater on the backend to show the latest version. Please don't comment on this 2 month old issue.
