### ISSUE TITLE
Error while starting (Ubuntu 15.10)

### ISSUE THREAD

**Issue by sicofante** [nylas/N1#505] opened 2015-11-29 07:10 UTC
This is all I get when launching N1:

![kazam_screenshot_00000](https://cloud.githubusercontent.com/assets/6874245/11455809/a0f6102e-9670-11e5-8413-f53fe5690c08.png)

**Comment by jstejada** [comment] 2015-11-29 09:25
hi @sicofante , thanks for reporting this. I'm closing as a dupe of #492

**Closed by jstejada** 2015-11-29 09:25 UTC
