### ISSUE TITLE
Cannot type Japanese in the search field

### ISSUE THREAD

**Issue by tetsuok** [nylas/N1#261] opened 2015-10-29 09:13 UTC
On OS X, I cannot type Japanese in the search field. I can type only vowels (i.e., あ, い, う, え, お).
This is a **serious** issue especially for Japanese users.  Users cannot search emails including Japanese words.

For example, suppose I want to search for グーグル (meaning: Google) in the field. When I type "gu-guru" from Japanese keyboard, user should get "ぐーぐる" in Hiragana characters, but actually I got "gうーgうrう". This issue does not happen in the composewindows

### Reproducing Steps
1. Install the version of 0.3.20-6bbe930
2. Add Japanese keyboard from System Preferneces
3. Launch Nylas N
4. Click the search field
5. Switch to Japanese keyboard
6. Type gu-guru

### Version
0.3.20-6bbe930 (0.3.20-6bbe930)

### OS
 Mac OS X (15B42)

**Comment by brettgerry** [comment] 2015-11-17 20:12
Related, there appears to be a similar issue with subsequent lines after the first one in composer:

From a customer:
The first row I can write it normally but from the second row the input have a problem 
It do like 
ｍめめーめーｒめーるメール 
to write 
メール (me-ru)

**Comment by emorikawa** [comment] 2015-11-23 16:33
The bug in the search bar was fixed by 2e618d4 and will go out in the next release (0.3.24). The issue was caused by improperly handling keyboard events from inputs.

**Closed by emorikawa** 2015-11-23 16:33 UTC
Labels: i18n

**Comment by tetsuok** [comment] 2015-11-24 09:59
Awesome! I don't see this issue in `Version 0.3.23-94e0cb9 (0.3.23-94e0cb9)`
