### ISSUE TITLE
Show address on linked strings

### ISSUE THREAD

**Issue by jorosmtz** [nylas/N1#479] opened 2015-11-26 01:25 UTC
When the mouse is over the links into the email's body, it is great if the address was shown in a hint.

**Comment by bengotow** [comment] 2015-11-26 01:54
Hey @jorosmtz — I'm going to close this as a duplicate of #335, but I'll see if we can get this in soon!

**Closed by bengotow** 2015-11-26 01:54 UTC

**Comment by jorosmtz** [comment] 2015-11-26 02:00
Thank you Ben.

> On Nov 25 2015, at 6:54 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hey [@jorosmtz](https://github.com/jorosmtz) — I'm going to close this as a
duplicate of [#335](https://github.com/nylas/N1/issues/335 "Hovering over
links in email should show URL" ), but I'll see if we can get this in soon!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/479#issuecomment-159778704).![](https://github.com/notifications/beac
on/AOrQ8uiBbUeM476cATJe9iQNiP5KO_Opks5pJl3RgaJpZM4GpqCS.gif)
