### ISSUE TITLE
N1 restart loop -- loops between the loding screen and the main mail view screen

### ISSUE THREAD

**Issue by CabbageHead-360** [nylas/N1#2036] opened 2016-04-23 08:08 UTC
##### Are there any related issues?

...

##### What operating system are you using?
I am using Arch Linux
...

##### What version of N1 are you using?
0.4.25-a22631a is my version
...

I installed my N1 by the following command and it installed without any errors:
pacaur -S n1

I logged out and logged in and now I get this error while launching N1:
Streaming log data to /tmp/Nylas-N1-17803.log
App load time: 155ms
ErrorReporter: Shipping Logs. Exception occurred
/usr/share/nylas/resources/app.asar/src/nylas-private-ship-logs-task
/usr/share/nylas/resources/app.asar/src/task.js:39
        userAgent: navigator.userAgent
                   ^

ReferenceError: navigator is not defined
    at new Task (/usr/share/nylas/resources/app.asar/src/task.js:39:20)
    at Function.module.exports.Task.once (/usr/share/nylas/resources/app.asar/src/task.js:17:14)
    at ErrorReporter.module.exports.ErrorReporter.runShipLogsTask (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:114:17)
    at ErrorReporter.module.exports.ErrorReporter.shipLogs (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:80:14)
    at ErrorReporter.module.exports.ErrorReporter.reportError (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:65:10)
    at ErrorLogger.module.exports.ErrorLogger._notifyExtensions (/usr/share/nylas/resources/app.asar/src/error-logger.js:220:26)
    at ErrorLogger.module.exports.ErrorLogger.reportError (/usr/share/nylas/resources/app.asar/src/error-logger.js:61:10)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:247:26)

--

**Bug?**
##### Do you have any third-party plugins installed?
I do not have any 3rd party plugins. I can't even get it to open
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, I don't think the issue is related to any specific email provider 
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

{"host":"HAL-9000","timestamp":"2016-04-23T08:17:26.926Z","payload":"App load time: 155ms\n"}
This is everything in the latest logfile 
...

**Comment by bencevans** [comment] 2016-04-24 14:55
I'm finding the same since using the automatic upgrade on a Windows box.

**Comment by adeloscope** [comment] 2016-04-25 02:11
Similar on mac.  It oscillates between a screen that says "Please wait while we prepare new features" and the mail screen which is in a pre-populated state.

**Comment by Plsr** [comment] 2016-04-25 06:47
I am too experiencing this on Mac OS X 10.11.4 with N1 0.4.25-a22631a. 

I downloaded the compiled version from https://nylas.com/. I had other instances of N1 installed on this machine in the past and can (briefly) see an error message for one of my mail accounts in the main view (not sure if this is related to the issue at hand).

**Comment by CabbageHead-360** [comment] 2016-04-25 09:15
Wow. It's good to know that this is a common issue. Well, I tried to install it on Ubuntu, works like a charm. Going to try to use it on openSUSE just to see if this problem is isolated to Arch in Linux. I don't know much about mac though :/

**Comment by Plsr** [comment] 2016-04-25 10:30
Just talked to a friend of mine who is running on the same versions of OS X and N1 and does not have any problems at all.

I'd like to contribute more specific information but I'm not sure what helps here. I don't have any error logs in `/tmp`.

Console.app keeps printing `lsd: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist` when I try to start N1 which seems to be a known bug (see [this thread](https://discussions.apple.com/thread/7270354?tstart=0)).
I don't think thats the cause of the error though, my friend doesn't have the file as well and he has no problems.

**Comment by AngelMunoz** [comment] 2016-04-25 15:15
hey guys, This is happening to me on Windows 10 also with the lattest version from the website I guess 0.4.25.

What I did is to remove the `C:\Users\<USER>\.nylas` folder, I had to add back my accounts but is working now, perhaps a problem with **config.cson** or other files up there?

**Comment by Plsr** [comment] 2016-04-26 06:30
I can confirm the fix of @AngelMunoz working on OS X.

**Comment by bengotow** [comment] 2016-04-26 20:37
Hey folks thanks for reporting this. This is very strange—I think it's most likely that N1 was unable to open / create `~/.nylas/edgehill.db`, which is the SQLite3 database file used by the app. We'll do some investigation and see if any logs have come in.

**Comment by CabbageHead-360** [comment] 2016-04-26 20:48
@AngelMunoz 's fix does not work for Arch sadly. @bengotow Thank you for looking into this

**Comment by bengotow** [comment] 2016-05-03 16:13
Hey folks! We talked about this internally and I think the problem was a sync `cursor` stored in the config.cson file which the server didn't recognize and rejected without resetting. This should be fixed in `0.4.32`. Can you try it out and let me know if the issue persists?

**Comment by esttorhe** [comment] 2016-05-03 16:39
I just installed `Nylas` via cask
```console
brew cask install nylas-n1
```

And I'm experiencing the same behavior. Downloaded `.dmg` from the website worked correctly though.

**Comment by bencevans** [comment] 2016-05-07 12:33
Installed `0.4.33` which fixed the issue.

**Comment by esttorhe** [comment] 2016-05-10 17:07
I can confirm that installing via `cask` gives me `0.4.33` which fixes the issue 🙇

**Comment by jstejada** [comment] 2016-05-12 22:57
this issue was partially fixed with, but will prevent correct sync if you still had an invalid cursor. This will be properly fixed in the next patch release which should go out this week. Thanks and sorry for the trouble.

**Comment by jstejada** [comment] 2016-05-17 02:27
this should be fixed in v0.4.38. let me know if anyone is still experiencing this

**Comment by jstejada** [comment] 2016-05-17 02:38
This should be fixed in v0.4.38.  If you are still having issues, you can remove any cursor fields you have inside your config.json and this should fix the issue. The cursor field should be located here in the file:

...
nylas:
  <accountId>:
    cursor: "..."
...
Or alternatively you can completely remove your `~/.nylas` folder and re add your accounts. Let me know if anyone is still experiencing this and in which version.

Thanks!

**Comment by oojacoboo** [comment] 2016-05-17 03:03
Thanks @jstejada that did the trick.  However, not before clearing out the preferences in ~/.nylas.  Didn't know nylas was storing prefs in the home folder :/

**Closed** 2016-05-19 23:35 UTC
Labels: done-pending-release
