### ISSUE TITLE
Rule for incoming mail doesn't archive

### ISSUE THREAD

**Issue by eapearson** [nylas/N1#949] opened 2016-01-10 18:44 UTC
I have a rule that is supposed to remove alerts from my inbox and label them as Alerts. It accomplishes this with a From filter on exact match for the sender email address, and by applying the Alerts label and then the Archive action. The filter works fine when the Process Al Mail button is used, but arriving mail only receives the Alerts label and not the Archive action. I've tried the rule actions in both orders (Archive then label, label then Archive) to see if perhaps incoming mail was only getting the first action applied, but there was no difference. So I suspect that the Archive action is for some reason not being applied to incoming mail.

**Comment by bengotow** [comment] 2016-01-12 23:55
Hi @eapearson — thanks for filing this and providing enough detail to reproduce. This is definitely possible—I'll dig in and let you know if we get this resolved.

**Comment by eapearson** [comment] 2016-01-13 18:23
Hey @bengotow, thanks, the latest update (now on Version 0.3.43-b95f1f7 (0.3.43-b95f1f7)) seems to have fixed this. The messages are indeed archived, and are tagged correctly, however they still appear in the notifications, which in this case is not what I want, although technically it is correct (since Notifications are defined as applying to new messages.)
For this use case -- service alerts -- of which I need to receive all, but only am interested in a few, it is still a lot of extra noise. It would be neat to be able to have notification on/off be a rule action. E.g. maybe I want notifications off in general, but rules for important categories of messages to trigger notification; or perhaps I generally want notifications, but rules to exclude alerts, office-wide newsletters, etc.
Thanks!

**Comment by eapearson** [comment] 2016-01-13 22:13
I was premature -- the original issue still exists. It may have been that the other mail app (Apple Mail) was not fully shut down when N1 opened up, and performed the filtering while N1 was showing the notifications. Weird.

**Comment by ddelrio1986** [comment] 2016-05-20 14:31
This is also happening to me. Sometimes the message will get archived and sometimes it stays in my inbox. It always is properly marked as read and the label is always applied. Just sometimes the archive doesn't work.

**Comment by eapearson** [comment] 2016-05-20 16:09
This is one of the two main reasons I don't use N1 as my daily email client. N1 will be fine for a while, and then a swarm of alerts will overwhelm my inbox, so I'll just close it and open Apple Mail where the rules take care of that stuff reliably.

**Comment by bengotow** [comment] 2016-05-31 23:44
Hey folks - this should be fixed by 856334c08890de3a4e2d8004494f6c66f944c2ed. It turns out there was a pretty serious issue with multiple mail rules, or mail rule actions firing for the same message at the exact same time. Stay tuned for the next release!

**Comment by bengotow** [comment] 2016-06-14 23:29
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!

**Closed by bengotow** 2016-06-14 23:29 UTC
Labels: bug, done-pending-release
