### ISSUE TITLE
Changes Made in N1 Do Not Sync Back to Gmail

### ISSUE THREAD

**Issue by stefaniwhylie** [nylas/N1#2903] opened 2016-10-05 05:06 UTC
My Gmail account does not seem to be syncing correctly with N1.  I receive incoming emails with no problems, but any changes made does not sync back to my Gmail account.  Changes are reflected in Nylas, just not Gmail (this includes archiving, snoozing, even just marking it as read). 

Right now the issue only exists in my personal Gmail account, not Google Apps accounts. 

I did see other issues reported with Sync issues, but they seemed different than this, so figured I'd create a new issue. 

--
OSX 10.11.6
N1 Version 0.4.56-816edde (0.4.56-816edde)
No third-party plugins

**Comment by rdegges** [comment] 2016-10-05 05:20
This also affects me right now. Was about to file this.

Archiving in nylas has no effect on gmail.

Sending mail from nylas doesn't show sent mail in gmail.

etc.

**Comment by retrorism** [comment] 2016-10-05 11:30
The issue seems to affect not only Gmail account: my Zoho IMAP account also isn't synced properly. Can't make much sense of the log yet, I'm afraid, so I cannot give any further details.

OSX 10.11 / 10.12
N1 version 0.4.56-816edde
no extra plugins.

**Comment by drakythe** [comment] 2016-10-05 19:40
Having the same issue, was kind of a shock to sync my iPhone after clearing out mail via Nylas and discovering I had 100+ unread emails. I logged into gmail through a browser and verified all the mails are still marked as unread.

OSX 10.11.6
N1 Version 0.4.56-816edde (0.4.56-816edde)
No extra plugins

**Comment by emadow** [comment] 2016-10-06 18:00
Having the same issue as well. Forced to use gmail interface in the interim until a solution has been deployed—otherwise using email on my phone is miserable.

OSX 10.12
0.4.56-816edde (0.4.56-816edde)

**Comment by RebelandSlaughter** [comment] 2016-10-07 10:26
Having the same issue - syncing not reflected on GMail

OSX 10.12
Version 0.4.56-816edde (0.4.56-816edde)

**Comment by ChainsawBaby** [comment] 2016-10-09 14:27
Had the same issue. Removed my account and added it again, sync now works.
*Still going through 400 emails that hadn't been synced*

**Comment by stefaniwhylie** [comment] 2016-10-09 22:16
I tried that, hoping that it would work, but no luck.  

After discovering N1, I really dislike using web Gmail, so much so that I've basically just been using "newer_than:24h label:inbox" to search through my inbox each morning in N1 to see if there's anything that needs my attention (since messages still come through), and haven't really archived anything.  Thankfully work email still works.

Patiently waiting for some sort of fix.  Did removing and re-adding the account work for anyone else?

**Comment by rdegges** [comment] 2016-10-10 00:42
I just removed / re-added my accounts, but still having issues :( I can't archive mail in Nylas and have it carry over to gmail, for instance.

I hope the team prioritizes this fix. Literally makes the client unusable for people who need to use non-nylas clients on mobile, etc.

**Comment by hallamoore** [comment] 2016-10-10 18:02
Another incidence: https://nylas.zendesk.com/agent/tickets/6461

**Comment by emadow** [comment] 2016-10-10 18:06
removing/re-adding accounts did not work for me. tried a couple of times.

really love nylas—this is an _incredible_ email client. but this is a showstopper for me at the moment

**Comment by jstejada** [comment] 2016-10-10 18:51
Another incidence: https://nylas.zendesk.com/agent/tickets/6568

**Comment by jstejada** [comment] 2016-10-10 18:51
Another incidence: https://nylas.zendesk.com/agent/tickets/6584

**Comment by jstejada** [comment] 2016-10-10 18:56
Another incidence: https://nylas.zendesk.com/agent/tickets/6555

**Comment by retrorism** [comment] 2016-10-12 10:45
No luck removing re-adding accounts here either, sadly.

**Comment by emadow** [comment] 2016-10-17 21:18
Checking in -- any update on this @jstejada @hallamoore @emorikawa @bengotow

**Comment by emadow** [comment] 2016-10-19 18:26
😱

**Comment by jstejada** [comment] 2016-10-19 21:45
Hi all. This seems to have been due to an issue processing actions that occurred about 2 weeks ago and which should be resolved by now.
I just checked most of the accounts that were having issues and they don't seem to have any recent failed actions. (@emadow has confirmed that it is working for him now)

If anyone is still having trouble syncing their actions back to gmail, please feel free to comment here or email support@nylas.com. Going to close this issue for now.

Thanks for your patience!

**Comment by emadow** [comment] 2016-10-19 21:46
thanks @jstejada !!

**Closed by jstejada** 2016-10-19 21:45 UTC
Labels: bug, mail-sync

**Comment by rdegges** [comment] 2016-10-20 01:08
Yey!! Thanks for fixing this. Back to using Nylas <3

**Comment by emadow** [comment] 2017-01-09 17:30
@jstejada looks like this issue is happening again :(
