### ISSUE TITLE
Deleted Gmail label remains in N1

### ISSUE THREAD

**Issue by axllent** [nylas/N1#333] opened 2015-11-01 09:04 UTC
After a label gets deleted in Gmail, the label (with original emails prior to label deletion) remains in N1.

**Comment by sethual** [comment] 2015-11-02 02:23
Yeah have the same problem. Even when I deleted the account and relinked.

**Comment by mitjafelicijan** [comment] 2015-11-03 12:06
+1

**Comment by gpleiss** [comment] 2015-11-11 20:44
Same

**Comment by spang** [comment] 2015-11-11 22:21
hey folks, thanks for the report! This is a known issue which we are working on resolving in the sync engine. (It's trickier than you'd think, because in Gmail IMAP, users can disable specific labels from appearing over IMAP, so we can't just use our regular folder list syncing code to determine that a label has been deleted, as it may have just been disabled in IMAP.)

**Comment by dkouvdis** [comment] 2015-11-25 10:56
I have looked into the Gmail labels API, I understand what you (@spang) are saying. I dont have an advanced coding experience, I just want to point out a suggestion.

I am having the same issue, N1 is not reflecting the labels list I have over the API - I suggest creating a button somewhere in the preference, it should execute a specific job. Temporarily disable the account for ~30-60 seconds, request the labels list api, populating a fresh list of labels without modifying emails labels. 

It just that I dont understand, I removed all the cache in Application Support folder and reinstalled N1 to start fresh but it still persists. 

Further note: I guess the issue is coming from Nylas Sync Engine. Oh well

**Comment by bengotow** [comment] 2015-12-01 22:20
Hey folks—this has been fixed in the sync engine. Gmail label deletes should be properly reflected in N1 now. Enjoy N1!

**Closed by bengotow** 2015-12-01 22:20 UTC
