### ISSUE TITLE
Make Snoozes mappable to Key Bindings

### ISSUE THREAD

**Issue by manicmarvin** [nylas/N1#2347] opened 2016-05-30 11:29 UTC
**Feature Request**

I think a key-binding for the snooze item function would be super, such as 

core:snooze-item that drops down the snooze menu/options 
or
customizable key-bindings for today, tomorrow, weekend, and custom.

##### This feature _does_ exist in another mail client I use.
Polymail.
Also, mail pilot. 

This issue has already been raised, but for some reason closed without a visible resolution or plan of action. See #1516.

...

**Comment by kriskhaira** [comment] 2016-05-30 12:17
> This issue has already been raised, but for some reason closed without a visible resolution or plan of action. See #1516.

@manicmarvin You missed the first reply in that issue. That issue along with this one is a duplicate of #1424, which is still open.

**Comment by jstejada** [comment] 2016-06-01 00:53
hey @manicmarvin, indeed this issue is a duplicate of #1424, so I'm going to merge it in.

**Closed by jstejada** 2016-06-01 00:53 UTC
