### ISSUE TITLE
Unread Email Under Account...But No Unread Emails!

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#1379] opened 2016-02-19 19:00 UTC
Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- [ ] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

- [ ] What operating system are you using?

- [ ] What version of N1 are you using?

**Bug?**
- [ ] Do you have any third-party plugins installed?

- [ ] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

- [ ] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.

**Feature Request?**
- [ ] Does this feature exist in another mail client or tool you use?

**Comment by bengotow** [comment] 2016-02-19 19:33
Closing as duplicate.

**Closed by bengotow** 2016-02-19 19:33 UTC

**Comment by jstejada** [comment] 2016-03-02 17:30
dupe of #759
