### ISSUE TITLE
All accounts in one inbox

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#690] opened 2015-12-12 02:59 UTC
An inbox in which you can read all your emails so no need to be switching among all your accounts, but read all of them at once

![screen shot 2015-12-12 at 2 58 28](https://cloud.githubusercontent.com/assets/2094957/11759818/4269652c-a07c-11e5-9176-35ef996a5163.png)

You can add many account´s but there´s not an "all inbox view".

**Comment by bengotow** [comment] 2015-12-12 03:14
Hey—thanks @tinybigstudio, this is called "unified inbox", gonna close this as a duplicate of #537

**Closed by bengotow** 2015-12-12 03:14 UTC
