### ISSUE TITLE
Degree ° symbol added to the end of links

### ISSUE THREAD

**Issue by natemhanson** [nylas/N1#2091] opened 2016-04-29 16:46 UTC
When I add links to an email, I look at the sent email in my sent folder and each link has a degree symbol (i.e. °) added to the end of them (see image). When I look at the email in the sent folder on Gmail web, it doesn't have the degree symbol.

![degree](https://cloud.githubusercontent.com/assets/6539048/14922946/3c83faba-0def-11e6-9417-f4fcbd11c630.png)

(On OS X 10.11.4, using N1 0.4.25-a22631a, with link tracking enabled.)

**Comment by bengotow** [comment] 2016-04-29 22:38
Hey! This is part of N1's link tracking feature. When the recipient clicks the link, that dot will turn blue.

I'll see if we can improve messaging around this soon.

**Comment by natemhanson** [comment] 2016-04-29 22:58
Oh, I see. Yeah, I think perhaps making a small graphic would be better than
what looks like a character. Also, maybe not the same color as the link.
Perhaps a red square when unclick and a green square (with a check?) when
clicked.![](https://link.nylas.com/open/q4b5oatxekgflq4i2uxnb7xm/local-
3a5ad50a-5659)

On Apr 29 2016, at 3:38 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey! This is part of N1's link tracking feature. When the recipient clicks
the link, that dot will turn blue.

>

> I'll see if we can improve messaging around this soon.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/2091#issuecomment-215899760)![](https://github.com/notifications/beac
on/AGPHKCkahVXzYBvYZdjeEHxbYIdFHI7hks5p8oh8gaJpZM4IS_Gj.gif)

**Comment by bengotow** [comment] 2016-05-03 00:57
In the next release, we're going to change the color and make the underline not include the º. In the future we'll look at changing this out for a different image as well.

![image](https://cloud.githubusercontent.com/assets/1037212/14972298/470ce4fe-108f-11e6-8ea4-e22158383c84.png)

**Comment by manicmarvin** [comment] 2016-05-04 17:14
Visually, the link tracking dotº  sits too close to the link and the line-height. ~~I realise this is because you're using a standard `utf-8` character.~~ Scratch that. I see you're using an image! (Derived from the `UTF-8` character, but an image anyway.) 

In which case, do you think a little CSS manipulation moving the dot a little farther out and higher would make this more evident? (Making the dot larger as well might help.)

I just increased the `padding` from `0 2px 1.5em 2px` to `0 2px 2.1em 4px`. I think it was clearer, UX test anyone?

`<img class="link-tracking-dot" title="Number of clicks: 6 | http://demo.themeum.com/starter/" src="nylas://link-tracking/assets/ic-tracking-visited@2x.png" style="padding-bottom: 2.1em; padding-left: 4px; padding-right: 2px; vertical-align: text-bottom; zoom: 0.55;">`

**Comment by grinich** [comment] 2016-05-10 22:14
@manicmarvin can you post a screenshot of what that looks like?

**Comment by manicmarvin** [comment] 2016-06-15 13:12
Sorry, I missed this entirely.

Now made teh following changes:

~~~CSS
    margin-bottom: 1em;
    margin-left: 4px;
    margin-right: 1px;
    vertical-align: text-bottom;
    width: 7px;
~~~

And it looks like the attached. You can see both the original in "here" and the modified on in "wordpress documentation".

Hope it helps. 
<img width="533" alt="screen shot 2016-06-15 at 6 41 09 pm" src="https://cloud.githubusercontent.com/assets/10953704/16080960/e1d1185a-3328-11e6-8ff4-8bfad4a28bea.png">

**Comment by jackiehluo** [comment] 2016-10-01 20:16
Closing this issue for now, since the link-tracking dots are expected behavior—we may revisit the UI around that at some point in the future!

**Closed by jackiehluo** 2016-10-01 20:16 UTC
Labels: discussion-around-behavior
