### ISSUE TITLE
GMail mark-as-(un)important action doesn't work

### ISSUE THREAD

**Issue by laughedelic** [nylas/N1#1331] opened 2016-02-13 03:05 UTC
Neither chosen GMail shortcuts work, nor the custom ones:

```cson
'body':
  'i': 'application:mark-important'
  'I': 'application:mark-unimportant'
```

**Comment by mbilker** [comment] 2016-02-15 22:29
From [here](https://github.com/nylas/N1/blob/03a33e5270a16b88ea44d34b457292d79e897eae/internal_packages/thread-list/lib/thread-list.cjsx#L157), are the messages you are trying to mark as unimportant across multiple accounts?

**Comment by laughedelic** [comment] 2016-02-15 22:41
@mbilker I have only one gmail account in N1, but this account aggregates other accounts (through gmail aliases). Anyway, this doesn't work on _any_ messages.

**Comment by bengotow** [comment] 2016-02-16 17:59
Hey folks—I can confirm this is a bug. It looks like those commands fire, but are throwing an exception. I'll get this fixed in the next release.

**Closed by bengotow** 2016-02-16 17:59 UTC

**Comment by krzkrzkrz** [comment] 2016-02-18 18:15
Seeing this as well. Hoping for the fix soon
