### ISSUE TITLE
When searching for labels keyboard shortcuts are triggering

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#2307] opened 2016-05-23 21:18 UTC
If you open the label picker and start typing before the popout has finished and the input field focused, then the keys will be interpreted as keyboard shortcuts.

To replicate, pretend you're searching for the label "companies". Enable Gmail shortcuts, then hit "l" immediately followed by "c". This will pop open a new composer before the label has focused.

0.4.40

**Comment by jackiehluo** [comment] 2016-10-01 07:04
Closing this issue—I think it's fixed now? I can't reproduce!

**Closed by jackiehluo** 2016-10-01 07:04 UTC
Labels: bug
