### ISSUE TITLE
Unread Counts across multiple Mailboxes

### ISSUE THREAD

**Issue by reptoxx** [nylas/N1#841] opened 2015-12-26 20:02 UTC
Hey,

everytime i get a message i have to search for the right Mailbox, where the new mail is contained.
For me, their has to be some kind of notification where the message is.
I added an Example: How i could imagine to solve this problem.

Regards
ReptoxX
![feature](https://cloud.githubusercontent.com/assets/13363890/12007769/dc0f0784-ac13-11e5-9453-5b5d7b1cbcc4.png)

**Comment by mbilker** [comment] 2015-12-26 21:53
Hey @reptoxx! Thanks for the request, but this is a duplicate of #468.

**Closed by mbilker** 2015-12-26 21:53 UTC
