### ISSUE TITLE
message body is truncated if long text in table

### ISSUE THREAD

**Issue by raknerak** [nylas/N1#1102] opened 2016-01-22 09:45 UTC
I can not view the full message body if the table size is big. I attached following snapshots for the message body from outlook and n1 to compare them for you. 
![outlook_messagebody](https://cloud.githubusercontent.com/assets/7880734/12507311/ab88b412-c0fd-11e5-8408-910d5d7aa919.png)
![n1_messagebody](https://cloud.githubusercontent.com/assets/7880734/12507312/ab8bb4a0-c0fd-11e5-9dce-656f3b60f406.png)

**Comment by emorikawa** [comment] 2016-01-29 01:44
@raknerak It looks like other messages are getting truncated. I'm going to close this as a duplicate of #425

**Closed by emorikawa** 2016-01-29 01:44 UTC
