### ISSUE TITLE
Tray icon rendered incorrectly in dark mode on OS X

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#1396] opened 2016-02-22 17:35 UTC
This seems to be a regression of issue #429 which was already fixed 

<img width="448" alt="screen shot 2016-02-22 at 9 31 19 am" src="https://cloud.githubusercontent.com/assets/1271509/13226596/14db4c7a-d947-11e5-8901-05c721d3c0f1.png">

**Comment by mbilker** [comment] 2016-02-25 15:46
Dupe of #588

**Comment by mbilker** [comment] 2016-02-25 15:47
Except that #588 is for Linux, but same issue for all platforms.

**Closed** 2016-02-25 15:47 UTC
