### ISSUE TITLE
Enable El Capitan's Split Screen Mode on Nylas N1 for OSX

### ISSUE THREAD

**Issue by agustifernandez** [nylas/N1#1078] opened 2016-01-20 00:38 UTC
Hi, I noticed It wasn't available trying to use safari alognside nylas, maybe it would be easier if I make a plugin in order to have a webkit view inside nylas.

Any ideas? is this on the Roadmap?

**Comment by mbilker** [comment] 2016-01-20 02:27
Dupe of #313

**Closed by mbilker** 2016-01-20 02:27 UTC
