### ISSUE TITLE
N1 into tray Linux Mint Mate 17.2

### ISSUE THREAD

**Issue by Foxly1990** [nylas/N1#221] opened 2015-10-27 13:19 UTC
Hello! Thanks for N1. How can I minimize application to tray in Linux Mint Mate 17.2? Where i can read about this?

**Comment by 0v3rth3d4wn** [comment] 2015-10-27 16:01
If you could +1 this thread it would be great! We are asking for the same thing - https://github.com/nylas/N1/issues/217

**Comment by bengotow** [comment] 2015-10-28 19:28
Hey @Foxly1990 —thanks for filing this. I'm going to close it as a duplicate of #217. We should be able to use the Electron Tray API (https://github.com/atom/electron/blob/master/docs/api/tray.md) to support both linux and Win32 system trays.

**Closed by bengotow** 2015-10-28 19:28 UTC

**Comment by Foxly1990** [comment] 2015-10-29 09:40
Ok, thanks for the response
