### ISSUE TITLE
Gmail sync doesnt work for me

### ISSUE THREAD

**Issue by nhumrich** [nylas/N1#172] opened 2015-10-24 03:17 UTC
Added my gmail account today. All my labels, folders, and filters showed up on the left side menu, but I cant see any emails. Absolutely zero show up, no matter what folder I select.

It looks like the initial sync might have been interrupted, now I cant figure out how to start the sync back up. It doesnt look like any network calls are being made at all, even if I wait for 5 minutes, no calls show up in the developer tools network console.

How is syncing supposed to work?

**Comment by khanshakeeb** [comment] 2015-10-25 14:24
Hi,

Same problem for me as well; my label shows but email not sync and I am looking for some option where I can sync my emails but I guess there is no such option exists.

Thanks

**Comment by joewilliams** [comment] 2015-10-27 22:38
Same here, lots of emails in `All Mail` for me but nothing in any labels/folders, nothing in starred except for mail that just arrived (nothing starred previous to using N1).

**Comment by bengotow** [comment] 2015-12-10 03:34
Hey folks—it looks like this was caused by an infrastructure issue we were having in October. Should be fixed now. Enjoy!

**Closed by bengotow** 2015-12-10 03:34 UTC
Labels: mail-sync
