### ISSUE TITLE
Important tag

### ISSUE THREAD

**Issue by dkouvdis** [nylas/N1#1225] opened 2016-02-07 23:18 UTC
Hi.

Since the today's update (current version v0.4.5), I have this annoying important tag that I cannot remove. I tried switching on/off in the preference. Still there, see attachment

![screenshot 2016-02-07 23 16 55](https://cloud.githubusercontent.com/assets/2727196/12876095/20ddf90c-cdf1-11e5-87d3-54c30953accd.png)

**Comment by mbilker** [comment] 2016-02-08 00:30
Thanks for the report @dkouvdis. What mail provider are you using for the account?

This is possible if you added a Gmail account as an IMAP account.

**Comment by dkouvdis** [comment] 2016-02-08 08:08
I am using the Gmail mail provider.

No, I added it by selecting Gmail (many months ago). I also just tried removing it and re-adding it back, still there.

Please note, a real **important tag** would be capitalised. Those tags are not.

**Comment by czpukmen** [comment] 2016-02-08 09:48
I have the same issue. http://gyazo.weappy.co/98c5cb.png

**Comment by bengotow** [comment] 2016-02-08 18:40
Hey folks—wow, this is an interesting one. Do you see these additional important tags as folders in other mail clients, or as a label in Gmail? I wonder if something caused an additional `important` label to be created? The one created by Gmail should definitely be capitalized.

Could you do me a favor and open the main window of N1, press Cmd-Option-I to open the developer tools, and post the output of running this command in the console at the bottom?

```
JSON.stringify($n.CategoryStore.categories().filter(function(c){return (c.displayName && c.displayName.toLowerCase().indexOf('important') != -1); }))
```

This should return enough information that we can diagnose what's going on.

**Comment by dkouvdis** [comment] 2016-02-08 22:10
No, nothing. Only on N1

I also did some debugging on gmail settings, playing with important label, changing labels to see if it changes anything but it doesn't.

Here's my output
```
"[{"client_id":"local-da8d7e22-babc","server_id":"2wwojbqt9i720aj22yrkdpv88","object":"folder","account_id":"292gzaesfwob1hk46eh3e7exz","name":null,"display_name":"Important","id":"2wwojbqt9i720aj22yrkdpv88"}]"
```

**Comment by patrickheeney** [comment] 2016-02-08 23:22
I have the same issue, however the output is `"[]"` for me. My inbox looks the same as OPs.

**Comment by patrickheeney** [comment] 2016-02-10 23:12
@bengotow Is there another command I can run to help debug this issue since it returns a blank array for me?

**Comment by eapearson** [comment] 2016-02-25 01:33
I'm seeing this too, and the output of the command is also an empty array. I typically use Apple Mail, dipping into N1 to see if it can take over yet, and rarely gmail web interface. I was looking at the gmail web interface to see if importance markers were turning up ... and they were, on every single message. How is that for intelligent, all of my work emails in my work email account are important. Then again, so was everything else. I turned that off Inbox > Importance Markers > Show markers in the g web client and there was no change in N1, then I turned off "Don't use my past actions to predict...", and that caused no change in N1 either. And then I tried adding and removing the email account as gmail, and then as map. Finally when adding as imap the "important" label is gone. On the other hand it is taking forever to sync up my account.

**Comment by patrickheeney** [comment] 2016-02-25 16:48
@bengotow I did some debugging in chrome. The nylas api returns the [lower case important tag](https://github.com/nylas/N1/blob/0217e5a509ac9c475649b775d784311f33a8ab07/src/flux/models/thread.coffee#L134) which is returned as a thread category. The important label then gets filtered out for the [message list](https://github.com/nylas/N1/blob/d80edbf7f373f56e490394a3eaa79eeeaa09af6c/internal_packages/message-list/lib/message-list.cjsx#L250), but not for the [thread list](https://github.com/nylas/N1/blob/03a33e5270a16b88ea44d34b457292d79e897eae/internal_packages/thread-list/lib/thread-list-columns.cjsx#L77)

I don't know a lot of coffee-script, so proposing this here before a PR:

```
      labels = thread.sortedCategories()
      labels = _.reject labels, (l) -> l.name is 'important'

      for label in labels
        continue if label.id in ignoredIds
        c3LabelComponentCache[label.id] ?= <MailLabel label={label} key={label.id} />
        labels.push c3LabelComponentCache[label.id]
```

This fixed it in my testing. Sound good for the PR?

**Comment by larrymcj** [comment] 2016-03-12 01:14
Count me in with having this irritating issue as well. It's definitely not the Gmail Important tag...and I can't determine any reason for it showing up on some messages and not others. It's easy to remove the tag by opening the message and clicking the "X" on the yellow tag, but we shouldn't have to do that. This is a major annoyance.

**Comment by patrickheeney** [comment] 2016-03-14 16:38
Is anyone else seeing the `Sent Mail` label showing up now in the message view along with the `important`? Once I updated to the latest version, I now have all these extra labels.

**Comment by larrymcj** [comment] 2016-03-14 17:48
Patrick: yes I see exactly what you're seeing. I had to just stop using N1 for awhile until these tag issues are resolved. I have always seen the "important" tags but now seeing also the "sent" tag.

**Comment by jstejada** [comment] 2016-03-14 18:08
hi @larrymcj , the sent tag definitely shouldn't be there, we just pushed a fix: https://github.com/nylas/N1/issues/1671

regarding the important tag issue, we are looking at the underlying backend issue. cc @khamidou 

Thanks!

**Comment by larrymcj** [comment] 2016-03-14 18:15
Thanks so much for the update, Juan!

**Comment by middle8media** [comment] 2016-04-26 17:13
I am experiencing this as well, Thanks @jstejada

**Comment by natemhanson** [comment] 2016-04-29 16:50
I have this as well. OS X 10.11.4, N1 version 0.4.25-a22631a.

**Comment by larrymcj** [comment] 2016-04-29 23:44
This, and the fact N1 doesn't properly sync with Gmail, still preclude me from using it...let alone paying for it. I would happily pay for it, if these two problems were solved.

**Comment by patrickheeney** [comment] 2016-04-29 23:50
@larrymcj I actually submitted a pull request to temporarily fix this only for it to be ignored. I also spoke directly with N1 to debug this further and received no response (other then they are "looking into it" for the past few months). I have since moved onto other email clients that are more stable and welcome contributions.

**Comment by larrymcj** [comment] 2016-04-29 23:59
@patrickheeney It seems like this issue is simply being ignored, but I know for a fact many other users have it. Not sure how they think they can sell an email client with a problem like this. Additionally, I've installed every version of N1 ever released and it never syncs properly with my Google Apps Gmail account. Again, how can they expect to be paid for an email app with serious problems? The part I hate is that N1 is the only client out there with a super clean UI and I'd love to use it...but I just can't.

**Comment by patrickheeney** [comment] 2016-04-30 00:09
@larrymcj I hear you and completely agree. I was looking to be part of the community working on N1, but with the recent switch to Pro and the general unresponsiveness to everything, I have to go elsewhere. It is really unfortunate.

**Comment by nickell** [comment] 2016-04-30 00:16
@patrickheeney you said you moved on to other email clients, do you have any suggestions? N1 has my favorite UI but is unusable for the reasons you guys have already discussed. I'm back to using gmail in the browser because I like the keyboard shortcuts, I've even tried mutt and alpine but couldn't devote enough time to make them effective for me.

**Comment by larrymcj** [comment] 2016-04-30 00:21
I suspect it's much more of a letdown to developers than users...especially when you really want to be part of an open source community. As a user I'm back with Mailplane, which is merely a Safari based app for Mac that just presents the actual Gmail UI and adds a few nice things. It also gives me the ability to tab Google Contacts along with Gmail UI, and Inbox by Gmail UI for easy access to either.

**Comment by patrickheeney** [comment] 2016-04-30 00:30
Product hunt has some collections for discovering new email apps. Nothing as "open source" and flexible as N1 that I saw. We should probably not discuss competitors here and leave this issue discussion clean for when Nylas gets around to it. Hopefully someone from N1 will get to this eventually so we can try and use it as our primary email clients.

**Comment by larrymcj** [comment] 2016-04-30 00:33
Agree. I've edited my previous comment.

**Comment by nickell** [comment] 2016-04-30 00:36
Good point, here's hoping they get back to it!

**Comment by ginfuru** [comment] 2016-05-05 21:29
I have this same issue... but here is a `gif` of the behavior when i remove the important label. 
![screen_capture_on_2016-05-05_at_17-20-23](https://cloud.githubusercontent.com/assets/402910/15057833/e0c9a5b0-12e6-11e6-99af-21a7f99ff955.gif)

**Comment by khamidou** [comment] 2016-05-06 23:50
Hi @ginfuru @nickell @larrymcj @patrickheeney @natemhanson @eapearson @dkouvdis ,

I'm an engineer at Nylas. Sorry about what may appear as being unresponsive --- we deeply care about N1 and our customers but we have a lot of issues to triage and bugs to fix. 

We're now focusing on resolving those annoying sync issues and as part of this, I'm going to work on this issue in the next few weeks. Could you send an email to `karim@nylas.com` with the addresses for which you're seeing this bug? It would make debugging way easier!

Cheers,

k

**Comment by cdysthe** [comment] 2016-06-07 01:35
This is a major annoyance so I was wondering is if the fix will be posted here as soon as it's available?

**Comment by hallamoore** [comment] 2016-07-26 00:34
Hi everyone,

After lots of digging, it appears that this is caused by having an unchecked "Show in IMAP" option for your Important label in Gmail. A quick fix would be to simply check that box, but we also have a patch on our end that should be released in a few days.

Thanks for your patience!
Halla

**Comment by jackiehluo** [comment] 2016-07-28 23:39
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!

**Closed by jackiehluo** 2016-07-28 23:39 UTC
Labels: bug, done-pending-release, mail-sync
