### ISSUE TITLE
Not working with windows 10 proxy

### ISSUE THREAD

**Issue by deepakpunjabi** [nylas/N1#1565] opened 2016-03-04 10:11 UTC
Nylas N1 doesn't seem to work with windows 10 under proxy at this moment.
I have configured proxy in windows 10 via both GUI and netsh winhttp set proxy.

OS - windows 10
Nylas N1 version - 0.4.10
no plugins installed

![nylas n1](https://cloud.githubusercontent.com/assets/17640076/13524140/836629c2-e21f-11e5-9928-cd08045ebb6a.PNG)

**Comment by emorikawa** [comment] 2016-03-04 14:47
@deepakpunjabi What error are you getting? If you open up the hamburger menu -> Developer -> Open Activity Window you can see the API requests going out and the error codes they're returning.

**Comment by mbilker** [comment] 2016-03-04 15:18
The backend code still uses `node-request` which is why it does not respect proxy settings.

Source: [here](https://github.com/nylas/N1/blob/master/src/flux/nylas-api.coffee#L82)

**Comment by mbilker** [comment] 2016-03-04 15:19
Dupe of #104

**Closed by mbilker** 2016-03-04 15:19 UTC
