### ISSUE TITLE
Gmail sync not working properly on Windows

### ISSUE THREAD

**Issue by sergiocastell** [nylas/N1#268] opened 2015-10-29 11:46 UTC
The mail synced fine the first time, but after that, none of my new mails arrive in the Inbox.
The account has a 2-factor auth, but since I grant all permissions in the login, it should be working fine, right? In the left low corner it always says there's been a sync error, and that I can try again, but it always returns to the error.

N1 0.3.20, running on Windows 10. LOG: http://pastebin.com/KD6AKmLW

**Comment by sergiocastell** [comment] 2015-10-29 12:59
Found the issue! Too many contacts? 
![73ff63510277a2f6fab5237ab63f626c](https://cloud.githubusercontent.com/assets/3966313/10818896/368babb0-7e45-11e5-88b6-7180ec93549e.png)

**Comment by bengotow** [comment] 2015-11-10 02:02
Hi @sergiocastell — thanks for filing this. It looks like this was caused by the load on our servers a couple weeks ago causing API timeouts. Should be fixed now—thanks.

**Closed by bengotow** 2015-11-10 02:02 UTC
