### ISSUE TITLE
Send new messages from selected mailbox not working

### ISSUE THREAD

**Issue by jamiewilson** [nylas/N1#1354] opened 2016-02-16 23:11 UTC
I have the option `Send new messages from: Account of selected mailbox` enabled but the sender always defaults to the first account that I added to N1. Please let me know if there's any other information that might be helpful.

**Comment by jstejada** [comment] 2016-02-16 23:18
hey @jamiewilson, thanks for reporting this. have you added an alias by any chance?

**Comment by jamiewilson** [comment] 2016-02-16 23:21
Yup. Was just about to add that to this issue actually :)

**Comment by jstejada** [comment] 2016-02-16 23:26
ok, I think this is a dupe of https://github.com/nylas/N1/issues/1235, but I haven't been able to reproduce. You can fix it updating your config.cson, but before you do that could you tell me what steps you took to reach this state? In what order did you add the accounts and the alias? Did you modify any of the options? (`Send new messages from`, or `Default Alias for account`)?

**Comment by jamiewilson** [comment] 2016-02-16 23:30
@jstejada Hey, so I had one account with an alias. I believe I added that account and it's alias before adding the other two. I have toggled the various options for `send new messages from:`. I also removed the alias, and but it still shows up as the default for the non-aliased account. Strange. But feel free to close this as duplicate. I can add to the other thread if I figure anything out. Thanks for the quick response!

**Comment by jstejada** [comment] 2016-02-16 23:54
ok thanks! I'm going to keep this open because it's not really fixed. Manually removing `default_alias` from the incorrect account will fix the issue for now. You should be able to re add your alias. Let me know if you can reproduce the issue again

**Closed** 2016-02-17 02:08 UTC

**Comment by jstejada** [comment] 2016-02-17 02:10
hey @jamiewilson I was able to reproduce the bug, it should be fixed in an upcoming release. Thanks!

**Comment by jamiewilson** [comment] 2016-02-17 15:06
Thank you! :clap:

**Comment by oddjobz** [comment] 2016-02-20 17:46
Ok, +1, moreover, there is no error saying the message isn't sent, and the message does not appear in sent, it just evaporates!
