### ISSUE TITLE
Combined Inbox view?

### ISSUE THREAD

**Issue by brianjking** [nylas/N1#472] opened 2015-11-25 15:40 UTC
Is there a way to view multiple email accounts inboxes in a single view? If not, I hope this is coming! 

Thanks!

**Comment by rdewolff** [comment] 2015-11-25 16:06
+1!

**Comment by jstejada** [comment] 2015-11-25 18:15
hey @brianjking , thanks for contribuitng! "Unified inbox" is definitely on the roadmap. We've created a card for it on our open source Trello board, and you can track it there. Feel free to upvote it there if you've got a Trello account: http://trello.com/b/hxsqB6vx/n1-open-source-roadmap. Closing as a duplicate of #123

**Closed by jstejada** 2015-11-25 18:15 UTC

**Comment by brianjking** [comment] 2015-11-25 19:19
@rdewolff Just upvoted, couldn't find the card initially so here's the link in case you want to help out too by submitting a vote! https://trello.com/c/5pIfWaN3

Thanks @jstejada

**Comment by rdewolff** [comment] 2015-11-25 21:09
Thanks guys!
