### ISSUE TITLE
Archive keyboard shortcut not working on Windows and Linux

### ISSUE THREAD

**Issue by rakeshdas1** [nylas/N1#1374] opened 2016-02-19 03:03 UTC
I am using the GMail keyboard shortcuts layout and the only keyboard shortcut that is not working for me is to Archive my mail, which should be binded to the `e` key. I have tested this on both my Arch Linux and Windows machines, running the latest version of N1 (Version 0.4.5). I also have tried temporarily switching to a different keyboard shortcut layout such as the one for Inbox, where the archive shortcut does not work either, and tried to switch back to the GMail keyboard shortcut layout but no dice. Does anyone have a solution to this issue?

**Comment by bengotow** [comment] 2016-02-19 18:30
Hi @rakeshdas1 — are you using an account that has an archive folder? I believe the archive shortcuts don't do anything unless you have an Archive folder or are using a Gmail account.

**Comment by rakeshdas1** [comment] 2016-02-20 03:28
@bengotow I have tested on 3 gmail accounts and all 3 have the same result of not being able to archive. The only way I can archive the mail is by manually dragging the email to the label. I have also tested this functionality with a non-GMail IMAP account and that account does not apply to this issue because I can just move emails in that account into their respective folders via the `l` key shortcut, since archiving is not a thing in that account.

**Comment by rakeshdas1** [comment] 2016-02-20 03:35
@bengotow Wait...maybe because I have both the non-GMail account and the regular GMail accounts in the combined view? I'll test that out and report back.

**Comment by rakeshdas1** [comment] 2016-02-26 02:25
@bengotow Confirmed, even on the latest version (0.4.9), if you have a regular IMAP account hooked up, as well as one or more GMail accounts, and you are in the _all accounts_ inbox view, you can apply labels to your GMail emails, but you cannot archive them afterwards via the archive keyboard shortcut, which is the `e` key. The only way to archive your email thereafter is by going into the individual inbox views for GMail and then archiving them via the keyboard shortcut.

**Comment by fviz** [comment] 2016-03-01 21:28
I'm facing the same issue here. This is annoying, I shouldn't have to open the specific account inbox just so I can archive an email.

**Comment by jstejada** [comment] 2016-03-01 22:20
Hi everyone, I believe this is a duplicate of #1460 (merging it in), and will be addressed soon.

**Closed by jstejada** 2016-03-01 22:20 UTC
