### ISSUE TITLE
Nylas manage accounts unusable

### ISSUE THREAD

**Issue by 0xFireball** [nylas/N1#1758] opened 2016-03-16 04:54 UTC
I am using Windows 10 build 10586, with Nylas N1 v0.4.14

I have no plugins installed, and I have six accounts set up, two GMail, two Outlook, and two Exchange. This issue has existed since I closed N1 for the first time, until I closed it (I mean fully closed it, as in killing the process not just hitting the X)

Here's my stack trace when I try to open "Accounts" in Preferences.

<pre>
TypeError: Cannot read property 'split' of undefined
    at PreferencesAccountDetails.render (preferences-account-details.jsx:170)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:789)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:816)
    at [object Object].wrapper [as _renderValidatedComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:237)
    at [object Object].wrapper [as mountComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at Object.ReactReconciler.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:38)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:192)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:289)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:199)
    at Object.ReactReconciler.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:38)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:247)
    at [object Object].wrapper [as mountComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at Object.ReactReconciler.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:38)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:192)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:289)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:199)
    at Object.ReactReconciler.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:38)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:247)
    at [object Object].wrapper [as mountComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at Object.ReactReconciler.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:38)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:247)
    at [object Object].wrapper [as mountComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at Object.ReactReconciler.mountComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:38)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:764)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:506)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at Object.ReactChildReconciler.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:83)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:277)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:251)
    at ReactDOMComponent.Mixin._updateDOMChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:470)
    at ReactDOMComponent.Mixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:319)
    at ReactDOMComponent.Mixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:303)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:748)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:506)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at Object.ReactChildReconciler.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:83)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:277)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:251)
    at ReactDOMComponent.Mixin._updateDOMChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:470)
    at ReactDOMComponent.Mixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:319)
    at ReactDOMComponent.Mixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:303)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:748)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:506)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at Object.ReactChildReconciler.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:83)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:277)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:251)
    at ReactDOMComponent.Mixin._updateDOMChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:470)
    at ReactDOMComponent.Mixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:319)
    at ReactDOMComponent.Mixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:303)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:748)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:506)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:748)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:506)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at Object.ReactChildReconciler.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:83)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:277)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:251)
    at ReactDOMComponent.Mixin._updateDOMChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:470)
    at ReactDOMComponent.Mixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:319)
    at ReactDOMComponent.Mixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:303)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:748)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:506)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:748)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:506)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at Object.ReactChildReconciler.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:83)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:277)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:251)
    at ReactDOMComponent.Mixin._updateDOMChildren (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:470)
    at ReactDOMComponent.Mixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:319)
    at ReactDOMComponent.Mixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:303)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:748)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:506)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:748)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:506)
    at Object.ReactReconciler.receiveComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:97)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:748)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:726)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:642)
    at [object Object].wrapper [as updateComponent] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:539)
    at Object.ReactReconciler.performUpdateIfNecessary (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:115)
    at runBatchedUpdates (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:151)
    at ReactReconcileTransaction.Mixin.perform (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\Trans…:134)
    at ReactUpdatesFlushTransaction.Mixin.perform (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\Trans…:134)
    at ReactUpdatesFlushTransaction.assign.perform (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:95)
    at Object.flushBatchedUpdates (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:175)
    at Object.wrapper [as flushBatchedUpdates] (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:70)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\Trans…:207)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\Trans…:148)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:66)
    at Object.batchedUpdates (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:110)
    at ReactEventListener.dispatchEvent (C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\node_modules\react\lib\React…:174)module.exports.NylasEnvConstructor.reportError @ C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\src\nylas-env.js:318(anonymous function) @ C:\Users\Fire Ball\AppData\Local\nylas\app-0.4.14\resources\app.asar\src\nylas-env.js:267
preferences-account-details.jsx:170 Uncaught TypeError: Cannot read property 'split' of undefined
</pre>

**Comment by mbilker** [comment] 2016-03-16 16:34
Thanks for the report @0xFireball ! This issue is caused by the preferences page trying to check for aliases and display them. The code segment responsible is:
```javascript
    const {account} = this.state;
    const aliasPlaceholder = this._makeAlias(
      `alias@${account.emailAddress.split('@')[1]}`
    );
```

Unfortunately, the method does not ensure `account` or `account.emailAddress` are non-null values.

**Comment by 0xFireball** [comment] 2016-03-16 16:58
How do I fix this, if possible?
I ended up with duplicate accounts after trying to add the accounts again to see if that would make a difference. Unfortunately, it is still broken, and I cannot switch accounts even if I add new ones. Is there a way I can completely reset the preferences for N1, like resetting it to "factory state"? Uninstalling did not clear my preferences. Is there a way I can completely reset N1?

**Comment by bengotow** [comment] 2016-03-16 17:06
Hey @0xFireball — that's no good at all. It's really strange, but it sounds like the contents of `~/AppData/Local/nylas/` have been corrupted. Can you take a look at the `config.cson` file in that folder (in Notepad) and see if your accounts are listed in there? It sounds like it must have either duplicate items or something else wrong. Would be really interesting to know what exactly got screwed up!

**Comment by 0xFireball** [comment] 2016-03-16 20:16
All right, thanks! I'll have a look and let you know soon!

**Comment by 0xFireball** [comment] 2016-03-17 01:14
I changed the emails and removed personally identifying information, but here is `config.cson`
It doesn't look messed up to me. What do you think?

<pre>
"*":
  core:
    disabledPackages: [
      "quick-schedule"
      "message-view-on-github"
      "personal-level-indicators"
      "phishing-detection"
    ]
    disabledPackagesInitialized: true
    workspace:
      mode: "split"
      hiddenLocations: {}
    keymapTemplate: "Outlook"
    themes: [
      "ui-light"
      "ui-dark"
    ]
  updateIdentity: "0ed86044-e58b-4f2b-885e-afcd6679c255"
  env: "production"
  nylas:
    accounts: [
      {
        client_id: "local-6153880a-4b12"
        object: "account"
        metadata: []
        name: "Fire Ball"
        provider: "gmail"
        label: "Fire.Ball@gmail.com"
        aliases: []
        sync_state: "running"
        id: "local-6153880a-4b12"
      }
      {
        client_id: "local-53290645-a687"
        object: "account"
        metadata: []
        name: "Fire Ball"
        provider: "eas"
        label: "Ball.Fire@outlook.com"
        aliases: []
        sync_state: "running"
        id: "local-53290645-a687"
      }
      {
        client_id: "local-79bb9e2a-9389"
        object: "account"
        metadata: []
        name: "Fire Ball"
        provider: "icloud"
        label: "Fire.Ball@icloud.com"
        aliases: []
        sync_state: "running"
        id: "local-79bb9e2a-9389"
      }
      {
        client_id: "local-06616c45-6567"
        object: "account"
        metadata: []
        name: "Fire Ball"
        provider: "gmail"
        label: "BallFire@gmail.com"
        aliases: []
        sync_state: "running"
        id: "local-06616c45-6567"
      }
      {
        client_id: "local-da0bce9f-7e4e"
        object: "account"
        metadata: []
        name: "Fire Ball"
        provider: "gmail"
        label: "BallFire@example.com"
        aliases: []
        sync_state: "running"
        id: "local-da0bce9f-7e4e"
      }
      {
        client_id: "local-d25cae47-8661"
        object: "account"
        metadata: []
        name: "Something someone"
        provider: "gmail"
        label: "someone@example.com"
        aliases: []
        sync_state: "running"
        id: "local-d25cae47-8661"
      }
      {
        client_id: "local-73a093b8-e8df"
        server_id: "5a8yucemg2fxgx6d12kl50ykc"
        object: "account"
        account_id: "5a8yucemg2fxgx6d12kl50ykc"
        metadata: []
        name: "Something someone"
        provider: "gmail"
        email_address: "someone@example.com"
        organization_unit: "label"
        label: "someone.someone@example.com"
        aliases: []
        sync_state: "running"
        id: "5a8yucemg2fxgx6d12kl50ykc"
      }
      {
        client_id: "local-f9620bad-96f2"
        server_id: "7yg0oh4tun8lmr0ul42k5rxq5"
        object: "account"
        account_id: "7yg0oh4tun8lmr0ul42k5rxq5"
        metadata: []
        name: "Fire Ball"
        provider: "eas"
        email_address: "Ball.Fire@example.com"
        organization_unit: "folder"
        label: "Ball.Fire@example.com"
        aliases: []
        sync_state: "running"
        id: "7yg0oh4tun8lmr0ul42k5rxq5"
      }
    ]
    accountTokens:
      a15h4mw1acj4jya7bd1so80cc: "nd6IhStS3znwkepN4V3wf0W4tWikiF"
      dfiu8jxvpup3uiuoieoknz9lo: "YzP848O0YSPnUEaiASOQuclYaE3jsa"
      "7yg0oh4tun8lmr0ul42k5rxq5": "Nj7H9mp3wodQPHTRYhla3JiWTd54o2"
      "6m8plj2ahnhd1u5oo67dly455": "MDYoDIj0xJaF1A0t3uIBVkQHE8M7wk"
      "9fye965a9aajmy1vce5kgtxa0": "JMvuq6nrFAQDmxpWszp0zQdaObuQV0"
      "5a8yucemg2fxgx6d12kl50ykc": "D2eOTWpUxEqRH6sx0vTyGf4GBWekfc"
  devMode: true
</pre>

**Comment by 0xFireball** [comment] 2016-03-17 01:15
Let me know if i accidentally included personally identifying or sensitive information so I can remove it!

**Comment by mbilker** [comment] 2016-03-17 02:20
@0xFireball you did leave the worst information in, but I removed it for you.

**Comment by 0xFireball** [comment] 2016-03-17 02:21
What was that information? Just for my own knowledge?
On Mar 16 2016, at 7:20 pm, Matt Bilker <notifications@github.com> wrote:

@0xFireball<https://github.com/0xFireball> you did leave the worst information in, but I removed it for you.

**Comment by mbilker** [comment] 2016-03-17 02:22
@0xFireball the account tokens which are used in the authentication to the Sync Engine. With them, they can access your account without needing the server id because it is given in the responses.

**Comment by CrimsonRay** [comment] 2016-03-18 07:23
Experiencing the same issue on OS X El Capitan 10.11.3, Nylas N1 Version 0.4.14-53cd69b.

This happened when I tried adding a new GMail account, but didn't complete the auth process in browser. I restarted N1 and added the account again, successfully completing the auth process. However, there's now a ghost account of the same address present.

![n1-bug](https://cloud.githubusercontent.com/assets/10459349/13870982/bc4b9ee6-ed1b-11e5-912f-2b8d54222287.png)

I can't switch to the account or remove it. Attempting to access the Accounts pane in Preferences renders the entire N1 client unusable until reload or restart, and throws `Uncaught TypeError: Cannot read property 'split' of undefined` on `preferences-account-details.jsx:170`.

I no longer have this issue; fixed by nuking `~/.nylas` to totally reset N1, but thought you should know.

**Comment by 0xFireball** [comment] 2016-03-20 23:12
After destroying `~/.nylas`, I am happily using N1 again. Thanks!

**Comment by dmfay** [comment] 2016-03-21 18:17
I had the same problem as CrimsonRay and managed to fix it without collateral damage by removing just the ghost account entry (easy to find, it was the one without a `server_id`) under nylas/accounts in `~/.nylas/config.cson`.

**Comment by bengotow** [comment] 2016-07-13 21:00
Hey folks! This should be fixed. Closing due to inactivity.

**Closed by bengotow** 2016-07-13 21:00 UTC
Labels: bug, needs-attention
