### ISSUE TITLE
Subject line loses focus when shift-tabbed into

### ISSUE THREAD

**Issue by phoenixeliot** [nylas/N1#936] opened 2016-01-08 19:42 UTC
Mac OS 10.11.1
N1 Version 0.3.36-e8239a9
Gmail

Steps to reproduce:
1. Start a New Message
2. Click on the body of the email
5. `Shift-tab` into the subject line

Results:
Subject line will be momentarily focused, but then lose focus entirely.

This does NOT occur when tabbing into it from the `to` field, using `tab`.

Changing window focus from the window brings the focus back to the correct location. Because of this I can't see what IS being focused at first in the inspector.

[EDIT: Turns out it was a focus problem, not a selection change. Rewrote the issue.]

**Comment by bengotow** [comment] 2016-04-08 18:19
This was caused by the composer contenteditable re-asserting focus by running `atomicEdit` in it's onBlur hander. This was fixed by making atomicEdit not restore selection if it was not the focused element.

**Comment by bengotow** [comment] 2016-05-03 15:40
Hey folks! This has been shipped in `0.4.32`. Cheers!

**Closed by bengotow** 2016-05-03 15:40 UTC
Labels: bug, done-pending-release
