### ISSUE TITLE
Feature Request: Fine-tune accounts for "all accounts" view

### ISSUE THREAD

**Issue by evanemolo** [nylas/N1#1474] opened 2016-02-27 16:49 UTC
The "all accounts" view is great, however having a preference for picking and choosing which accounts get shown in that view would be helpful. I have email accounts that I intermittently check but don't want to see intermingled with my more important email accounts.

**Comment by bengotow** [comment] 2016-03-12 03:14
Closing as duplicate of #1355 - I total agree we need to build this soon!

**Closed** 2016-03-12 03:14 UTC
Labels: feature-request
