### ISSUE TITLE
A tunnel connection through the proxy could not be established

### ISSUE THREAD

**Issue by 1cosmologist** [nylas/N1#3158] opened 2017-01-13 21:57 UTC
I'm trying to install Nylas N1 for the first time on (1) Xubuntu 16.04, (2) MacOS 10.12.2 
I'm behind an authenticated proxy. Every time i start Nylas N1 v0.4.402 for the first time I get: "A tunnel connection through the proxy could not be established". Attaching the screenshot.
![nylas](https://cloud.githubusercontent.com/assets/11816582/21947090/54ed5f6a-da09-11e6-9753-5a6ee4aa7b9a.jpg)

Any help t solve this problem?

**Comment by emorikawa** [comment] 2017-01-17 16:37
Duplicate of https://github.com/nylas/N1/issues/104

**Closed by emorikawa** 2017-01-17 16:37 UTC
