### ISSUE TITLE
why I have a Trash label?

### ISSUE THREAD

**Issue by unluisco** [nylas/N1#744] opened 2015-12-18 03:03 UTC
In gmail.com I do not have these label

![monosnap 2015-12-17 21-15-54](https://cloud.githubusercontent.com/assets/6332263/11888299/f2ddf54e-a509-11e5-9973-8378307d5e9c.png)

**Comment by mbilker** [comment] 2015-12-18 03:43
Have you used any external applications that store messages in alternate tags?

Some examples of these applications include Mailbox for iOS or Apple Mail.

I know these types of tags showed up after using these applications. I have a `\Trash` tag and `\All` tag in my list.

**Comment by unluisco** [comment] 2015-12-18 20:42
I used Mailbox a few months ago

**Comment by mbilker** [comment] 2015-12-18 20:43
That would probably be a reason why. It is safe to delete.

**Comment by bashok001** [comment] 2015-12-19 01:29
#737 was closed as duplicate of this. So, I am hoping that I can add my comments here.

I didn't use any other clients anywhere in last year or so.

**Comment by mbilker** [comment] 2015-12-19 01:30
@bashok001 hmm. That's odd. I would just delete them then.

**Comment by unluisco** [comment] 2015-12-19 01:32
@mbilker I do not can delete the label

**Comment by mbilker** [comment] 2015-12-19 01:33
@unluisco Hmm. Not even right click and click Delete?

**Comment by unluisco** [comment] 2015-12-19 02:55
@mbilker Nope

![trash](https://cloud.githubusercontent.com/assets/6332263/11910900/fc870658-a5d1-11e5-9dae-960bceca451b.gif)

**Comment by bashok001** [comment] 2015-12-19 02:57
@mbilker No. Can't delete these labels. As I wrote in #737, /All showed up one day. I couldn't delete it. It disappeared when I relogged in next day. Then suddenly /Trash showed up. This one, I can't delete and it stayed beyond restarts for two days now.

**Comment by jstejada** [comment] 2015-12-19 08:37
thanks for the details! -- will look into it

**Comment by bengotow** [comment] 2016-01-06 02:56
Hey folks—thanks for posting. This is a duplicate of https://github.com/nylas/N1/issues/329. Our mail sync team is looking into this and you can follow the discussion there!

**Closed by bengotow** 2016-01-06 02:56 UTC
Labels: bug, mail-sync
