### ISSUE TITLE
I cannot see the checkboxes in the emails (inbox view)

### ISSUE THREAD

**Issue by javierferraz** [nylas/N1#2185] opened 2016-05-10 09:00 UTC
Hello guys, 

I cannot see the **checkboxes in the emails** (I mean the checkboxes that can be used for select several mails at once in the inbox view). It happens with any template I use. 

It only happens in this computer - I have not this proble at home, in another laptop.

Any ideas will be very welcome. 

You have a great product - congrats.

Thanks, regards, 

##### Are there any related issues?
I havent found any related issue.
...

##### What operating system are you using?
Windows 8

##### What version of N1 are you using?
v. 0.4.33

**Bug?**
##### Do you have any third-party plugins installed?
Just the plugins that come with the normal installation. Just the built-in plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Screenshot (default theme) - https://snag.gy/PiOSob.jpg
Another screenshot with Berend Theme - https://snag.gy/GCRDaM.jpg

**Comment by bengotow** [comment] 2016-05-10 16:03
Hey! I think that when you use the "split pane" mode (as opposed to the "list" mode), you can still shift-select threads but the checkboxes aren't shown. I'll see if we can do something about this in the future!

**Comment by robertofarrell** [comment] 2016-07-19 04:54
This really confused me as well.  It would be great to see checkboxes in the two panel mode.

**Comment by jackiehluo** [comment] 2016-10-01 05:50
Closing this issue because it's expected behavior—I don't think we plan on adding checkboxes to two-pane mode because most other mail clients don't!

**Closed by jackiehluo** 2016-10-01 05:50 UTC
