### ISSUE TITLE
Spelling checker

### ISSUE THREAD

**Issue by kios** [nylas/N1#724] opened 2015-12-16 18:00 UTC
In version 0.3.29 the spellchecker worked fine, in 0.3.32 The spell checker does not work anymore, use windows 7, this is a bug? or no longer available, sorry for my bad English

**Comment by mbilker** [comment] 2015-12-16 20:39
Dupe of #670

**Comment by jstejada** [comment] 2015-12-16 23:44
merging into #670 guys

**Closed by jstejada** 2015-12-16 23:44 UTC
