### ISSUE TITLE
Mail rules don't move gmail emails into proper "folder"

### ISSUE THREAD

**Issue by jamesaspence** [nylas/N1#2156] opened 2016-05-06 13:50 UTC
##### Are there any related issues?

AFAIK no related issues. A few searches didn't yield any for me.

##### What operating system are you using?
Mac OSX El Capitan (10.11.4)

##### What version of N1 are you using?
0.4.33-e8f137e

--

**Bug?**
##### Do you have any third-party plugins installed?
None.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail.

I have mail rules set up to, for example, sort my amazon orders into Finances/Receipts. When an email comes in that matches that rule, it applies the label correctly, but it doesn't "move" it out of my inbox - instead, it sits there with the same label. I then have to manually move the email to the label in order to clear my inbox.

**Comment by jamesaspence** [comment] 2016-05-09 15:32
Bump on this? Any word? Do you need more information?

**Comment by behzadsh** [comment] 2016-05-22 08:46
@jamesaspence I have similar problem, just one question to be sure. did you set to archive the mail that match your filters?

The issue I've faced is that, mails that match the filter would archive, and label will set correctly, but not shown in related folder in sidebar. Only accessible in All Mails!

**Comment by bengotow** [comment] 2016-05-31 21:09
Hey @jamesaspence — unfortunately this is currently expected behavior, because the mail rule is "apply label", not "move to label". (In Gmail, both are separate dropdowns). Apply label adds the label, but doesn't remove other labels, like "Inbox". I'll see if we can add the other option in the next release so that both are available!

**Comment by bengotow** [comment] 2016-05-31 23:31
This should be resolved by 856334c08890de3a4e2d8004494f6c66f944c2ed

**Comment by bengotow** [comment] 2016-06-14 23:31
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!

**Closed by bengotow** 2016-06-14 23:31 UTC
Labels: done-pending-release
