### ISSUE TITLE
New Message Indicator

### ISSUE THREAD

**Issue by jcuenod** [nylas/N1#920] opened 2016-01-07 18:01 UTC
Is there some way of showing which email accounts have new messages associated with them?
When I receive a new message but I'm viewing the wrong account, I have to cycle through the accounts I have before finding the one with the actual new message (new and unread are different in my mind).

**Comment by mbilker** [comment] 2016-01-08 02:04
Dupe of #864

**Closed by mbilker** 2016-01-08 02:04 UTC
