### ISSUE TITLE
Build RPM packages for Fedora

### ISSUE THREAD

**Issue by excieve** [nylas/N1#158] opened 2015-10-23 09:59 UTC
I'm trying to build an RPM package for my Fedora 22. So first I executed `script/bootstrap` and it went fine — I can run N1 via N1.sh. But I'd like to have a system package so I executed `script/grunt mkrpm` which failed with:
```
$ script/grunt mkrpm
Running "mkrpm" task
>> cp: cannot stat ‘/tmp/nylas-build/Nylas/*’: No such file or directory
Warning: null Use --force to continue.

Aborted due to warnings.
```
And indeed /tmp/nylas-build/ does not contain a "Nylas" directory.

Is there something I'm not doing correctly?

**Comment by grinich** [comment] 2015-10-23 22:28
closing as dupe of https://github.com/nylas/N1/issues/107

**Closed by grinich** 2015-10-23 22:28 UTC
Labels: platform-linux
