### ISSUE TITLE
Missing "archive" and "move to trash" buttons in Search Results view

### ISSUE THREAD

**Issue by luangch** [nylas/N1#486] opened 2015-11-26 12:34 UTC
The "archive" and "move to trash" buttons is missing when navigate form search result page

<img width="339" alt="screen shot 2558-11-26 at 7 26 30 pm" src="https://cloud.githubusercontent.com/assets/1572632/11423075/f13d6a86-9473-11e5-9c8a-808464d1c2e1.png">
*read email from inbox*

---

<img width="253" alt="screen_shot_2558-11-26_at_7_27_13_pm" src="https://cloud.githubusercontent.com/assets/1572632/11423112/3a01d5e0-9474-11e5-91db-00c4d9f00b41.png">
*read email from search.*

**Comment by luangch** [comment] 2015-11-26 13:13
**Update**

The buttons that should appear in each email list item is gone too.

<img width="231" alt="screen_shot_2558-11-26_at_8_07_30_pm" src="https://cloud.githubusercontent.com/assets/1572632/11423785/f48c7ea6-9479-11e5-8c28-82e833d55782.png">

**Comment by bengotow** [comment] 2015-11-30 19:54
Hi @luangch — this is currently intentional, but we'll fix it in an upcoming update. The issue is that clicking those buttons in search view feels very strange, because the mail doesn't disappear on some providers (it's still a search result, just in a different folder), and on other providers, it does but we have to re-run the search to know.

**Comment by bengotow** [comment] 2016-01-26 19:14
Merging into #537, since this is fixed on that branch.

**Closed by bengotow** 2016-01-26 19:14 UTC
Labels: enhancement

**Comment by jaymedavis** [comment] 2016-03-01 05:29
Should this be in 0.4.10-4e395b?

I am unable to archive mail from the search view.
