### ISSUE TITLE
Initial sync Error

### ISSUE THREAD

**Issue by flakerimi** [nylas/N1#6] opened 2015-10-05 17:55 UTC
Initial sync encountered error. Waiting to try again. 

Is this maybe because of Two factor Auth or something, I can send email but cannot receive, I use gmail.

**Comment by jasdeepsingh** [comment] 2015-10-05 17:57
Same here, Added my Google Apps email Failed on Initial Sync, submitted logs via Logstash.

**Comment by mchiang0610** [comment] 2015-10-05 18:03
This can be because their servers are overloaded at the moment. Try waiting a little bit and restart the app. It worked for me in the end.

**Comment by sbstnmsch** [comment] 2015-10-05 18:06
Yo, after 10mins everything went though. Thumbs up!

**Comment by jsadeli** [comment] 2015-10-05 18:24
Is the invite currently limited to a single PC only? I couldn't use Nylas on my other PC.

**Comment by jasdeepsingh** [comment] 2015-10-05 19:00
Works for me fine now. Replying from N1 :)

> On Oct 5 2015, at 2:24 pm, Jeffrey Sadeli &lt;notifications@github.com&gt;
wrote:  

>

> Is the invite currently limited to a single PC only? I couldn't use Nylas on
my other PC.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/6#issuecomment-145622440).![](https://github.com/notifications/beacon
/AAk2_CgfikSaSTsMb9sPnnZCU-n1TgpKks5o4rfBgaJpZM4GJLoR.gif)

**Comment by bengotow** [comment] 2015-10-05 19:09
Hey folks—thanks for reporting this issue. We've had an overwhelming number of downloads in the last two hours and our platform team is working to resolve some sync speed issues—your mail should appear soon. Sorry for the hassle—we knew we'd get a lot of installs but it's been a little crazy this morning.

More specifically, I think the "Initial sync encountered error" message is appearing because every once and a while, our API instances are unable to obtain connections to the database. 

(Two factor auth should be fine, we've got it enabled ourselves—but let me know if you run into issues!)

**Comment by dillonforrest** [comment] 2015-10-05 19:17
We're going to close this issue for now, as it seems like the issue is eventually resolving itself. However, if it persists, please let us know! I'll be more than happy to re-open it. :)

**Closed by dillonforrest** 2015-10-05 19:17 UTC
