### ISSUE TITLE
Issue with Quick Reply handling a large number of variables or certain variable names

### ISSUE THREAD

**Issue by mattkennedynz** [nylas/N1#2877] opened 2016-09-29 22:19 UTC
I'm probably going beyond the "quick" nature of "Quick Replies", but I'm finding the templating and placeholder variable functionality very useful for semi-personalised process emails. 

In a recent template I had six or so variables, but the 4th, 5th, and 6th variables would remain in yellow and highlighted in the sent email.

##### Are there any related issues?
Not that I can find

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.52

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Unfortunately I didn't keep my original email template. But my suspicion is that this bug is encountered with more than three variables and depending on the variable's name.

`Please could you discuss this with {{cio-full_name_1}}. If {{cio-first_name_1}} agrees to be involved...` is one of the problematic sections. For some reason this naming "works", but with `{{cio-full-name}}` there was an issue (the sent message containing the yellow highlighting formatting).

Can variable names only contain one hyphen, after which underscores should be used?

**Comment by bengotow** [comment] 2016-09-30 17:10
Hey! Thanks for reporting this - I'm going to try to reproduce this today and I'll let you know if we're able to figure it out.

**Comment by bengotow** [comment] 2016-09-30 18:55
Hi @mattkennedynz  - it looks like this is caused by your template variables being considered "misspelled" by the spellchecker. This will be fixed in the next release. In the meantime, if you use standard words or phrases (like "full name") in the templates, it should work. Let me know if that doesn't resolve the issue for you though—could be something else!

**Comment by bengotow** [comment] 2016-10-25 17:37
This has been fixed in 0.4.59, which we shipped earlier today. Enjoy!

**Closed by bengotow** 2016-10-25 17:37 UTC
Labels: bug, done-pending-release
