### ISSUE TITLE
Sending state when sending multiple messages

### ISSUE THREAD

**Issue by colllin** [nylas/N1#451] opened 2015-11-24 15:26 UTC
I fwded an email thread to someone with a private message.

Then I hit reply-all to reply to the thread.  It instantly created a new email in the UI for my reply, but for a solid 5-10 seconds, it displayed the private message I had fwded (in an uneditable mode) but with the original thread participants in the **To:** field, along with a loading spinner, so that it had the exact same appearance that a message has after clicking "Send", before it finishes sending.  I had a mini panic attack that my private message had been sent to the entire thread.  After 5-10 seconds, it finished "loading", or whatever it was doing (what was it doing??), and the private message was gone, replaced with an empty field for writing my new message.

**Comment by bengotow** [comment] 2015-11-25 22:54
Hey @colllin — thanks for reporting this. This one is... pretty interesting. I've been able to reproduce it on latest master and I'll see if we can track it down. It looks like the sending state is being applied to the message item for the second draft incorrectly. Stay tuned.

**Comment by bengotow** [comment] 2016-03-12 07:39
Hey! We shipped a fix for this yesterday in 0.4.14. Sorry for the delay - turned out to be tricky to track down. Enjoy!

**Closed by bengotow** 2016-03-12 07:39 UTC
Labels: bug

**Comment by colllin** [comment] 2016-03-12 23:46
Thank you!!

Collin
720-987-6472
