### ISSUE TITLE
Terrible "expanded message list" scrolling performance

### ISSUE THREAD

**Issue by knoopx** [nylas/N1#675] opened 2015-12-11 15:25 UTC
Scrolling the message list with just ~200 messages is painfully slow on a large desktop screen (2560x1440).

**Comment by mbilker** [comment] 2015-12-11 15:50
OS? Version of N1? GPU?

**Comment by knoopx** [comment] 2015-12-11 15:54
* Every N1 version I tried to date (Version 0.3.29-1904c6f (0.3.29-1904c6f))
* Mac Mini 2012 on Mavericks
* MacBook Pro (Retina, 13-inch, Mid 2014) on El Capitan

**Comment by knoopx** [comment] 2015-12-11 16:02
I get an average ~12fps when scrolling, the wider the list is, the slower to scroll. Here's a sample timeline capture while scrolling for you to debug: [TimelineRawData-20151211T170136.json.zip](https://github.com/nylas/N1/files/59588/TimelineRawData-20151211T170136.json.zip)

**Comment by mbilker** [comment] 2015-12-11 17:00
I will see if I can view this. I use Arch Linux from master. I may need to run the 0.3.29 release for Debian.

**Comment by mbilker** [comment] 2015-12-11 17:35
The Timeline dump reports a lot of the Scripting time during 3 React component mounts during a scroll event where the scripting time shoots up to >100ms (way more than 15ms for 60fps).

**Comment by bengotow** [comment] 2015-12-11 19:21
Holy crap that's slow—thanks for sending the timeline data. We do most of our dev on similar Macbooks and it should perform better than that. It looks like the app is unable to keep up with the scrolling, and starts to get bogged down. Instead of adding one row, rendering it, and repeating, it's accumulating ~6+ rows, rendering them for 140ms, etc.

Do you have any apps or tools running that might impact performance? Any sort of screen capture or custom window compositing / arrangement tools? I've seen it go this slow for me when I'm in"<5% battery" mode. I'll see if we can reproduce this, but it definitely shouldn't be this slow!

**Comment by knoopx** [comment] 2015-12-11 19:40
hey @bengotow sure, I run several heavy apps (java ide, big ass rails project, several other electron-based apps, several services...) but none of them should be "gpu intensive". I do use Spectacle.app/Quicksilver.app for "window management" on both computers if you think it may be related. I'm always plugged-in so it can't be CPU throttling.

**Comment by knoopx** [comment] 2015-12-11 19:55
Keep in mind that I'm reporting about the "expanded message list" view that appears once you reach certain window width. The "compact mode message list" works flawlessly.

**Comment by knoopx** [comment] 2015-12-11 19:59
The "expanded message list" is the one that shows a single preview of the message body, the labels it belongs to, and the "action buttons" over the hovered message along with a cool "fade out gradient" to truncate the message body.

**Comment by mbilker** [comment] 2015-12-11 23:29
@knoopx That is weird. I will see how to use this "expanded message list" under Linux and report back if I have similar performance issues. I use a 1080p monitor for my desktop with a GeForce GTX 750 Ti, but the issue we see here is with React compiling the components.

**Comment by mbilker** [comment] 2016-01-05 03:13
I do not see these performance issues on my end. Is this issue still present under `0.3.32` or the latest beta?

**Comment by grinich** [comment] 2016-02-08 23:54
We've optimized this so I'm going to close it. Please re-open if you continue to experience the issue.

**Closed by grinich** 2016-02-08 23:54 UTC
Labels: performance
