### ISSUE TITLE
Text only messages

### ISSUE THREAD

**Issue by wget** [nylas/N1#1279] opened 2016-02-09 23:38 UTC
Wrt the [discussion we had on Twitter](https://twitter.com/wget42/status/697195375086727172), being able to send text only message with N1 is a requirement for users, like me, using mailing lists software (mailman, etc.).

Some of them do not indeed support HTML+text emails. Currently Nylas N1 seems only to support HTML+text versions.

**Comment by bengotow** [comment] 2016-02-10 01:11
Merging as duplicate of #147

**Closed by bengotow** 2016-02-10 01:11 UTC
