### ISSUE TITLE
Privacy vs. Data Collection

### ISSUE THREAD

**Issue by herrbischoff** [nylas/N1#2464] opened 2016-06-16 10:06 UTC
A couple of days ago I received coupon codes from Nylas for a free year of Pro features. That's a nice gesture. The only problem is, I never signed up for an account. All I ever did was run a local copy of the client and sync engine and added my email accounts to said local instance.

Now, I received coupon codes to addresses I never even use publicly, let alone sign up for something. The only coherent explanation for this appears to be that the sync engine is secretly and without any confirmation or information about it collecting email addresses from the added accounts to add to your mailing lists. Those have been reported as junk mail, as I never agreed to receiving any kind of bulk email from you.

This is completely unacceptable. It's one thing to collect certain information upon signing up to something by agreeing to some convoluted ToS, designed to enable exactly this kind of data collection. Something you still do not do anyhow, by the way, leaving users in the dark about exactly where their credentials and emails are stored. This is the reason I never signed up for your service in The first place. It is another altogether to use an open source project to collect sensitive information without any mention of it anywhere. This is not only very bad form but may in fact be in conflict with certain open source licenses you use. At the very least it violates the spirit of FOSS.

Whatever the reasoning for this was originally, I for one am not going to touch any product of your group again. I was skeptical to begin with but now you've lost my trust. In the end, I have to conclude that you are either a rather confused and badly managed group of individuals ("company") with questionable priorities, or willfully ignorant and simply lying about your motivations and stance on privacy.

In a time before Facebook and others, serious privacy used to mean to be able to be reasonably private even from a company you're dealing with. I'm not aware that this definition has generally changed except in the mindset of Silicon Valley startup types, advertisers and possibly unsuspecting users. In this regard, your emails are to be viewed as a textbook example of unsolicited commercial email (UCE), collecting personal information without consent and using this information to send out business proposals on bulk. Something for which spam filters were built.

As this is in direct relation to the sync engine, its collection behavior should be considered inappropriate and therefore a bug.

**Comment by Omeryl** [comment] 2016-06-16 20:37
Hey,

I don't believe that to be the case, at least for me. I used a completely separate email, with my sync engine, all inside an isolated VM. I never once received a coupon code for that email. Are you sure you didn't accidentally sign up for the hosted engine at some point in time?

**Comment by grinich** [comment] 2016-06-16 21:11
hi @herrbischoff -- I just checked our logs. It looks like you were using the proprietary build of N1, which is available for download from our website and includes things like fonts we (Nylas) have paid to license and analytics+crash reporting code. In order to use the full open source stack, you need to build N1 yourself from the open source.

Note that even within the open source version of N1, there's still a box to sign up for the mailing list.  The sync engine and N1 from our open source repos do not phone home by default. (You can check the source.) 

It turns out that lots of our open source users still want to hear big announcements/updates, so they add themselves to the mailing list. You can remove yourself either by clicking "unsubscribe" in the bottom of the coupon emails, or from within N1 like this: 

![pasted image at 2016_06_16 02_02 pm](https://cloud.githubusercontent.com/assets/92417/16133110/0f07c5a6-33cb-11e6-8801-3976dd436ee0.png)

Alternatively if you email support@nylas.com we can manually remove them from any marketing lists.

Sorry about the unwanted spam. We love our beta users and wanted to send out the $84 coupon codes to as many of them as possible. We generated that list via usage stats from people who downloaded the compiled proprietary version from our website. We also cryptographically sign these builds and it's what the N1 auto-updater will download.

Our little company is growing and we're working on being more organized, but generally we're just doing the best we can. We open source almost all of our code and are also working to build a sustainable business around hosting and enterprise tools. It sounds like our hosted platform isn't a good fit for your security needs, but I'm glad you still are able to get some value from the code we've open sourced and GPL licensed.

I'm going to close this issue since it's not a bug with N1 currently, but feel free to continue the convo and I'll try to do the same (though I might be a bit slow in responding).

--Michael (Founder & CEO at Nylas)

**Closed by grinich** 2016-06-16 21:11 UTC
