### ISSUE TITLE
Columns do not remember width

### ISSUE THREAD

**Issue by Zeklandia** [nylas/N1#287] opened 2015-10-29 22:02 UTC
After restarting Nylas, the far left, message list, and message content views will be restored to their default sizes.

**Comment by Zeklandia** [comment] 2015-10-29 22:14
Also happens when switching from one view to another and then back.
I.e. Inbox --> Drafts --> Inbox

**Comment by bengotow** [comment] 2015-11-24 06:49
Merging as a duplicate of #287

**Closed by bengotow** 2015-11-24 06:49 UTC

**Comment by Zeklandia** [comment] 2015-11-25 04:32
Uh... It is issue #287.

**Comment by jstejada** [comment] 2015-12-25 17:48
merging into #833
