### ISSUE TITLE
Enable setting the root path/folder and separator

### ISSUE THREAD

**Issue by brkattk** [nylas/N1#511] opened 2015-11-30 14:22 UTC
Within an IMAP account it would be helpful to be able to set the namespace for various folders. It would also be helpful if we could map those to the generic "Sent", "Archive", etc.

[fastmail IMAP settings](https://www.fastmail.com/help/technical/servernamesandports.html)
[Dovecot - Namespaces](http://wiki.dovecot.org/Namespaces)

**Comment by bengotow** [comment] 2015-11-30 19:46
Closing as duplicate of #454

**Closed by bengotow** 2015-11-30 19:46 UTC
