### ISSUE TITLE
IMAP: N1 always sends my email address as the IMAP/SMTP username

### ISSUE THREAD

**Issue by bene23** [nylas/N1#954] opened 2016-01-11 10:47 UTC
Hi, I want to add an IMAP Account, but it doesnt work. Settings are correct. I think Problem is STARTTLS. My SMTP Server use STARTTLS Port 25. Are there any possibilities to get this work? I really want to use nylas n1.

**Comment by posidonius** [comment] 2016-01-11 13:12
use port 587

**Comment by bene23** [comment] 2016-01-11 17:56
Still doesnt work. I tried both. 587 + SSL and 587 without SSL. Always: "invaild credentials".

**Comment by bengotow** [comment] 2016-01-11 18:12
Hi @bene23 — here's a bit more info about the restrictions of our IMAP/SMTP support: https://nylas.zendesk.com/hc/en-us/articles/216118977-What-are-the-limitations-of-IMAP-SMTP-support- Maybe it's something on there?

**Comment by vectorchem** [comment] 2016-01-12 16:28
Same problem here -- I checked restrictions by @bengotow and all conditions are met by my mailserver. Connections via Apple Mail works fine. My email address is not my username, though.

**Comment by psychonaut** [comment] 2016-01-15 17:24
That's the case. Nylas is sending username@domain. It's my problem as well. Even you put just plain username in configuration dialog it sent it with domain:

```
Jan 15 18:12:01 chlor dovecot: imap-login: Disconnected (auth failed, 1 attempts in 15 secs): user=<eloy@domain.net>, method=PLAIN, rip=xxx.xxx.xxx.xxx, lip=aaa.aaa.aaa.aaa, TLS: Disconnected, session=<KqZ9f2IplAA0IErL>
```

**Comment by rixx** [comment] 2016-01-15 18:25
I can confirm this: When I enter `user` as username and `mail.domain.com` as mailserver, Nylas sends `user@domain.com` as username, which is wrong with traditional mailserver setups.

And since there is no way to skip the setup or configure additional data, there isn't even place for a workaround.

**Comment by theanalyst** [comment] 2016-01-28 20:54
Facing the same issue, have starttls at port 25 in my email server as well :(

**Comment by theanalyst** [comment] 2016-01-28 21:14
update seems working when I end up using full email.. so disregard my earlier comment

**Comment by grinich** [comment] 2016-02-08 19:51
this should be fixed by this afternoon

**Comment by vectorchem** [comment] 2016-02-09 02:06
Sorry, does not work for me -- still returning "Invalid credentials"

**Comment by psychonaut** [comment] 2016-02-09 17:02
Nope, still user@domain is sent to imap server.

**Comment by teger** [comment] 2016-02-12 13:41
Yes it's my problem.
the username is user@domain and not the field username !!

Why ? How to fix this?

Thanks

**Comment by logandavis** [comment] 2016-02-13 01:33
We just deployed a backend update to fix this issue. If you continue to have problems authenticating generic IMAP accounts that use IMAP/SMTP-specific credentials, please email support@nylas.com.

**Closed by logandavis** 2016-02-13 01:33 UTC
Labels: account-setup, mail-sync

**Comment by psychonaut** [comment] 2016-02-13 18:30
confirmed, it's working now.

**Comment by grinich** [comment] 2016-02-13 21:23
Great! :)
