### ISSUE TITLE
Better Touch Tool and Topbar (OS X)

### ISSUE THREAD

**Issue by Zn4rK** [nylas/N1#1063] opened 2016-01-18 17:49 UTC
For some reason, I can't seem to use [Better Touch Tool](http://www.boastr.net/downloads/) with Nylas N1. It works on other applications that runs Electron (like Slack).

Neither the Window Snapping nor the gestures work. I feel like there is something in the implementation of the topbar or the window it self that prevents this behavior.

The gestures I'm using are these:
![screen shot 2016-01-18 at 18 42 35](https://cloud.githubusercontent.com/assets/873043/12398399/cf1988bc-be13-11e5-8bcd-411f30ca5f98.png)

Nylas N1:
Version 0.3.43-b95f1f7 (0.3.43-b95f1f7)

Mac OS X
Version 10.10.5 (14F1509)

BetterTouchTool
Version 1.5

While writing this issue I also noticed that the window control-buttons don't respect the system UI. 
This has already been covered here though. https://github.com/nylas/N1/issues/561

**Comment by Zn4rK** [comment] 2016-01-18 17:53
I also just now noticed that the topbar does not "respect" the system UI. I'm using the "Graphite" apperance, but Nylas N1 is showing red, yellow and green window controls.
Example:
![screen shot 2016-01-18 at 18 51 01](https://cloud.githubusercontent.com/assets/873043/12398535/9c4ae5ec-be14-11e5-893c-534d65f1ceab.png)
Settings (also note the all grey window controls):
![screen shot 2016-01-18 at 18 50 44](https://cloud.githubusercontent.com/assets/873043/12398534/9c4aa24e-be14-11e5-88c7-57f2f26deba1.png)

**Comment by mbilker** [comment] 2016-01-18 22:51
Thanks for the report @Zn4rK. Currently, the top bar is implemented all in software (covered [here](https://github.com/nylas/N1/issues/313#issuecomment-152668972)). Therefore, it is harder to integrate Better Touch Tool with N1.

**Comment by bengotow** [comment] 2016-01-19 18:58
Closing as duplicate of #1020.

**Closed by bengotow** 2016-01-19 18:58 UTC
Labels: platform-os-x, ui
