### ISSUE TITLE
Suggestion: Introduce zoom levels into client

### ISSUE THREAD

**Issue by thorpj** [nylas/N1#699] opened 2015-12-13 02:23 UTC
I think it would be useful if users could change the zoom level of the whole client. That way, we could choose to have more, or less information in the client at one time. Or, it could be used so that client can be made small enough to fit on a smaller monitor (e.g. i have a portrait monitor @ 1280 x 1024) while still being useful.

**Comment by mbilker** [comment] 2015-12-13 02:24
This shouldn't be too difficult because Chromium supports zoom levels.

**Comment by thorpj** [comment] 2015-12-13 02:26
@mbilker That was my main concern, so you bring good news!

**Comment by mbilker** [comment] 2015-12-13 02:28
Looks like it was merged into Electron in atom/electron#406.

**Comment by thorpj** [comment] 2015-12-13 02:32
@mbilker So if it's part of atom/electron , which is based on node.js and chromium, we should see this coming to N1?

**Comment by mbilker** [comment] 2015-12-13 03:30
@thorpj Maybe. It depends on how difficult it is to change it on the fly.

**Comment by thorpj** [comment] 2015-12-13 03:32
@mbilker Okay, thanks. I guess we just wait and see now.

**Comment by bengotow** [comment] 2015-12-15 18:44
Hey folks! Zoom levels are a bit tricky—the chromium feature allows you to pinch-to-zoom as if the app were a web page. Instead of doing that, I think we'll opt to support different font sizes, so you can make the entire UX larger, like this: 

![image](https://cloud.githubusercontent.com/assets/1037212/11820332/c18aea4e-a318-11e5-932c-3db78f7b36c2.png)

( To take the screenshot, I made the `font-size-base` larger in the theme's ui-variables.less. Unfortunately, you can see there are some issues ;-))

**Comment by mbilker** [comment] 2015-12-16 04:36
Speaking of zooming of a [WebFrame](https://github.com/atom/electron/blob/master/docs/api/web-frame.md). I was able to change the zoom **factor** of my window (bolded because there is a difference between zoom factor and zoom level). I used `require('electron').webFrame.setZoomFactor(1.2)` to set the window to 120% where 100% is the original size.

![2015-12-15-23-34-26_1279x799](https://cloud.githubusercontent.com/assets/1266541/11832265/a5aab518-a384-11e5-8db6-585273cd83d2.png)

**Comment by Cu8eR** [comment] 2015-12-18 10:52
+1

**Comment by edsiper** [comment] 2015-12-18 14:55
+1  , I cannot use Nylas because content looks too small for me:

![nylas_content_size](https://cloud.githubusercontent.com/assets/369718/11899486/e6691dba-a564-11e5-99de-4077cb7760fa.png)

**Comment by bengotow** [comment] 2016-01-08 19:32
I think changing the web frame zoom is the best solution until we build something more sophisticated. It resizes the top nav bar and a few things I wish it didn't, but it's also very consistent and theme developers don't need to take it into account. I'm going to add a config option for changing the interface zoom and we'll get it into a future release.

**Closed** 2016-01-08 19:32 UTC
Labels: enhancement, feature-request, in progress, ui

**Comment by kakubei** [comment] 2016-02-26 18:27
+1 Can't see anything when composing emails. Any progress on this?

**Comment by thorpj** [comment] 2016-02-26 23:23
+kakubel Yes, zoom levels are there in the settings. If they're not, check for updates.

**Comment by kakubei** [comment] 2016-02-27 12:51
Oh, ok. Thanks.

> On Feb 27 2016, at 12:24 am, thorpj &lt;notifications@github.com&gt; wrote:  

>

> +kakubel Yes, zoom levels are there in the settings. If they're not, check
for updates.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/699#issuecomment-189523486).![](https://github.com/notifications/beac
on/ABZb68dtYtaHuSkm9L6Zt6t5kkWJnPdlks5poNX0gaJpZM4G0O-k.gif)

**Comment by rendsvig** [comment] 2016-04-23 12:21
Yes, apparently it cause problems -- spell checker underlining disappeared for some zoom level.
I used mbilker's suggestion:

Menu > Developer > Toggle Developer Tools > Choose "Console" tab >Then run

require('electron').webFrame.setZoomFactor(1.2)

**Comment by yourfriendaaron** [comment] 2016-04-23 17:31
Thanks, that works!

**Comment by collinksmith** [comment] 2016-05-13 04:52
+1 Seems like a very standard and important feature to be able to change zoom level with ⌘+= and ⌘+-

**Comment by Ikaruseijin** [comment] 2016-06-12 17:34
I too would like to see the ability to change the text size in the app. I appreciate the option to jury-rig it via the Developer Tools but there should be something in settings to do the job.

I would like the text smaller personally. For the same amount of space the window takes I get about 3/5 of what Mail.app (in Mac) displays. Additionally, people with vision issues would likely appreciate being able to increase the text size.

So I encourage continued work on this.

**Comment by Ikaruseijin** [comment] 2016-06-12 17:42
Closed? The issue isn't resolved yet. This is an important property for an app to have, in fact they all should be able to increase and decrease the text size. Increase for those who have vision issues. I'm appreciative that there is an option to adjust things via Developer Tools but unless it's part of the settings, most people will not use it or even know it exists.

**Comment by mbilker** [comment] 2016-06-12 22:40
The setting used to be there, but it affected more than just text size.
Buttons are backed by images, which were scaled incorrectly when using a
zooming scale factor.

**Comment by gmbaranzoni** [comment] 2017-11-16 11:05
The solution offered by @mbilker and @rendsvig works very well for me that I am running Nylas on a Ubuntu 16.04 laptop. However, as soon as I click on another application the web frame goes back to its original dimention. Is ther any way to make it permanent?

Thanks
GMB
