### ISSUE TITLE
Get new messages button and message synchronization indicator

### ISSUE THREAD

**Issue by aliukevicius** [nylas/N1#271] opened 2015-10-29 12:19 UTC
I open N1 mail client only when I have time to read mail and one thing I would like to see is a button to get new mail messages and also an indicator which will show if N1 client is checking for new mail messages at the time. Because at the moment I don't see any way in which you can identify if N1 client is in process of synchronizing messages or not.

**Comment by dgonzalezr** [comment] 2015-10-29 14:21
Totally agree, it's a feature that must be included.. I guess..

**Comment by mcescalante** [comment] 2015-11-04 18:45
This is likely a dupe of #167

**Comment by suchanlee** [comment] 2015-11-04 21:15
It would be great to know that N1 is currently in the process of fetching data from server

**Comment by bengotow** [comment] 2015-11-24 06:48
Hi folks—N1 is pushed mailbox changes from the sync engine and doesn't poll for mail changes, so there's no way to trigger it. We were experiencing a lot of sync issues last month when the client was open sourced, but your mail should appear almost instantly now. Going to go ahead and close this issue.

**Closed by bengotow** 2015-11-24 06:48 UTC
