### ISSUE TITLE
Typing "g" followed by "i" does not return to the inbox, "GI" does

### ISSUE THREAD

**Issue by shmuel** [nylas/N1#1096] opened 2016-01-21 21:39 UTC
If I am on an individual email message and I type “GI” I am sent back to the inbox as expected. However if I type “gi” I am not sent back to the inbox.

I expect to be able to do this with lowercase letters (without the shift key) as I can on Google.

This functionality is promised to work as described above by the preferences under: Shortcuts > Jumping.

**Comment by mbilker** [comment] 2016-01-21 22:07
While this is a duplicate of #854, the "GI" part is new and not part of that issue.

**Comment by jstejada** [comment] 2016-03-23 00:28
I'm going to merge this into #854

**Closed by jstejada** 2016-03-23 00:28 UTC
Labels: bug, design
