### ISSUE TITLE
iCloud two factor auth doesn't allow Nylas to sign in

### ISSUE THREAD

**Issue by winnieking** [nylas/N1#2862] opened 2016-09-21 15:13 UTC
##### What operating system are you using?
Win10

##### What version of N1 are you using?
0.4.52
--

##### Do you have any third-party plugins installed? If so, which ones?
no
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
icloud

I enabled to factor authentication on my iCloud account and it cause Nylas N1 to say that it couldn't sync with my @me.com email account and create app specific password.
But it show "Error when connecting to the server. Please check your settings."

the other gmail has app specific password already done.

**Comment by delahaya** [comment] 2016-09-23 14:12
I am also running into the same issue.  Im also experiencing the quitting when hitting send issue while full screen running macOS Sierra.

**Comment by KyleKing** [comment] 2016-09-24 13:13
What operating system are you using?

macOS Sierra 10.12

What version of N1 are you using?

0.4.52

Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

iCloud

------

^ Same issue here

**Comment by dcondrey** [comment] 2016-10-09 04:36
When trying to add Icloud account to Nylas with 2-factor auth setup on Icloud account, Nylas returns "Invalid credentials. Please check that your IMAP username and password are correct.".

![screen shot 2016-10-08 at 9 34 53 pm](https://cloud.githubusercontent.com/assets/2615179/19217947/484b9332-8d9f-11e6-9290-061caf616526.jpg)

**Comment by grinich** [comment] 2016-10-09 16:28
dupe of #1911

more info: https://support.nylas.com/hc/en-us/articles/219129988-I-m-using-iCloud-two-factor-authentication-and-can-t-sync-my-account-

**Closed by grinich** 2016-10-09 16:28 UTC
Labels: account-management
