### ISSUE TITLE
Accents in spanish characters not displaying properly in composer

### ISSUE THREAD

**Issue by brettgerry** [nylas/N1#211] opened 2015-10-27 01:24 UTC
Ex. The following sentence: árbol para por qué es árbol miércoles es hoy para ver sí tengo suérte.

In the composer results in:

![accent bug](https://cloud.githubusercontent.com/assets/2729391/10747078/7ed32698-7c0e-11e5-99a6-f3fc1dab0fc1.png)

**Comment by khamidou** [comment] 2015-10-27 03:31
It works on my machine --- Yosemite with the french locale. @brettgerry do you know the user's locale?

**Comment by xedef** [comment] 2015-10-27 04:12
Confirmed in the US locale (⌥ + e and then the vowel to put the accent on )

**Comment by hmaesta** [comment] 2015-10-27 11:23
Same bug here, writing in Portuguese.

I am using "**U.S. Internacional - PC**" as Keyboard layout.
`System Preferences > Keyboard > Input Sources > +`

**Comment by fameal** [comment] 2015-10-27 15:15
Same bug with "El Capitan". Using US International. When I press ⌥ + e it only writes the ´ and then, when I press the letter, it writes the letter with the accent. For me, **it only happens when the previous letter is a vowel.** For example: a´é

**Comment by lucasfs7** [comment] 2015-11-04 19:21
same for me for pt-BR using "U.S. Internacional - PC"

**Comment by sergiomajluf** [comment] 2015-11-05 15:21
I confirm it happens in Yosemite too.

If the Input source (keyboard layout) is in English like @fameal said, fails when accented character is preceded by a vowel. It Input Source is Spanish, it fails either way:

>written with english layout:
>préstame atenci´ón

>written with spanish layout:
>pr´éstame atenci´ón

**Comment by juan-diego** [comment] 2015-11-05 21:18
Same for me. I am using El Capitan 10.11.1 using an Spanish (Spain) keyboard, region set to Spanish -Spain and input source "Español - ISO"

**Comment by emorikawa** [comment] 2015-11-23 16:26
This has been fixed in c2ce51a and will go out in the next stable release (0.3.24).

The issue was due to the composer not properly handling [composition events](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent). We now treat the full composition lifecycle as a single atomic edit operation.

This issue was related to a variety of other issues including: #62, #384, #332, #89, #211

**Closed by emorikawa** 2015-11-23 16:26 UTC
Labels: bug
