### ISSUE TITLE
Flagged mails not appearing as Starred on Nylas N1

### ISSUE THREAD

**Issue by paper9oll** [nylas/N1#1067] opened 2016-01-19 05:15 UTC
Hi all,

I have this problem where N1 won't display flagged (starred) mails from Outlook.com. But when i flagged (starred) the mail on N1 ... Outlook.com will reflect the changes (flagged).

**Comment by emfree** [comment] 2016-02-02 20:53
Hi @paper9oll, thanks for the report. Could you send an email to support@nylas.com with the email address that you're seeing this for? I haven't able to reproduce with an outlook.com account.

**Comment by paper9oll** [comment] 2016-02-03 08:18
... okay but what i'm suppose to type for the subject and content

**Comment by emfree** [comment] 2016-02-03 19:13
Whatever you like! How about "N1 github issue #1067"?

**Comment by DakotaNelson** [comment] 2016-02-10 00:55
Hi @paper9oll! We've been unable to replicate this bug - is it still occurring for you?

I'm going to close this issue out since we can't pin the bug down, but feel free to reopen if you have any more details that can help us find it.

**Closed by DakotaNelson** 2016-02-10 00:55 UTC
Labels: bug, mail-sync

**Comment by tylerwhipple** [comment] 2016-03-03 00:45
@DakotaNelson I am having this bug. OSX 10.11.3 (15D21), Nylas Version 0.4.10-4e3595b (0.4.10-4e3595b)

**Comment by tylerwhipple** [comment] 2016-03-03 00:46
Outlook.com email's flags/starts are not showing on nylas, but work within Apple Mail
