### ISSUE TITLE
No way to manualy refresh/download new emails

### ISSUE THREAD

**Issue by dszmaj** [nylas/N1#233] opened 2015-10-27 18:29 UTC
Email feed is not "real time" I do not receive new emails and don't have a way to download/refresh it manualy

**Comment by mcescalante** [comment] 2015-10-27 19:53
At first, I was also looking for some sort of "refresh" function but noticed that it seemed to be regularly polling. I think that even clarifying to users that they don't need to be in search of a "sync" button or anything would help, since many clients have a "get mail" button or similar.

**Comment by dszmaj** [comment] 2015-10-27 20:07
Yes of course, but it's not "instant" comparing to other mail clients so there
is a room for improvement. Often I want to receive emails almost instantly, no
matter what, so instead of hitting refresh button I must log into the
traditional web app, its annoying, and would definitely force me to switch
clients

> On Oct 27 2015, at 8:53 pm, Mike Escalante &lt;notifications@github.com&gt;
wrote:  

>

> At first, I was also looking for some sort of "refresh" function but noticed
that it seemed to be regularly polling. I think that even clarifying to users
that they don't need to be in search of a "sync" button or anything would
help, since many clients have a "get mail" button or similar.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/233#issuecomment-151624119).![](https://github.com/notifications/beac
on/ADvjwC-Wg8FKfNElFgKlTOnAtAeF1dQpks5o_83PgaJpZM4GWuhd.gif)

**Comment by jetlej** [comment] 2015-10-28 13:56
+1

**Comment by bengotow** [comment] 2015-10-28 19:11
Hey folks—N1 retrieves new mail via a streaming connecting to the sync engine, so new email is "pushed" to the app as soon as it's available. There isn't any polling, periodic checking for mail, etc. As soon as it's pulled through the sync engine, it's visible in the app.

We've had a few load issues this week that have slowed down incoming mail from Gmail and other providers—once those are resolved, you should see new mail within a few seconds.

That said, we've had a lot of requests for a "Check Mail" or "Refresh" button. We'll see if there's a way we can work something into the UI.

**Comment by jwood803** [comment] 2015-10-29 14:31
Sounds awesome @bengotow! I was noticing that I'd get mail on my phone far more in advanced than through the app. Seems like y'all have a process for improving this. Thanks!

**Comment by mcescalante** [comment] 2015-11-04 18:46
This should be connected to #167 since they all have the same end-goal.

**Comment by bengotow** [comment] 2015-12-07 18:53
Thanks—closing as duplicate of #167

**Closed by bengotow** 2015-12-07 18:53 UTC

**Comment by adriaanmol** [comment] 2016-07-12 07:03
I am just not getting new mail. How to fix this? Restarting the app doesn't work either. Again load issues?
