### ISSUE TITLE
[Feature-Request] Signature Switcher

### ISSUE THREAD

**Issue by TheRojam** [nylas/N1#1812] opened 2016-03-22 19:18 UTC
I have many identities on one account i would like to change the signature by choosing an id.
at the moment i can't do this.

**Comment by jstejada** [comment] 2016-03-23 17:51
Hi rojam, do you mean you want to have a signature per alias? If so, this is a duplicate of #848

**Comment by TheRojam** [comment] 2016-03-23 17:56
@jstejada in outlook you can switch signatures while you write a mail this is a feature i like to have it.
#848 could also be a option. :) :+1:

**Comment by jstejada** [comment] 2016-03-23 19:28
oh I see, what does this feature look like? could you send a screenshot?

**Comment by knireis** [comment] 2016-04-10 17:04
+1

**Comment by bengotow** [comment] 2016-06-01 17:35
Merging into https://github.com/nylas/N1/issues/1047!

**Closed by bengotow** 2016-06-01 17:35 UTC
Labels: enhancement request from user
