### ISSUE TITLE
E-mail without text when using font via css @import

### ISSUE THREAD

**Issue by jsvini** [nylas/N1#820] opened 2015-12-23 19:02 UTC
This is the message in Nylas 0.3.32 - Windows (Gmail).

![image](https://cloud.githubusercontent.com/assets/4185886/11982786/0805e3d2-a98d-11e5-963c-800c0e9ba477.png)

And this is the same message in gmail.com:

![image](https://cloud.githubusercontent.com/assets/4185886/11982812/4cffc1a6-a98d-11e5-8b5b-fdd7a491b537.png)

You can see message the source code in: http://get.invisionapp.com/weekly-digest-51
The font is Open Sans via Google Fonts

**Comment by mbilker** [comment] 2015-12-24 08:06
Thanks for reporting this! This appears caused by the CSP (Content Security Policy) placed on messages.

**Comment by bengotow** [comment] 2015-12-28 19:13
Good find! I think we need to add `font-src: unsafe-inline` to the the app's global CSP. I'll see if I can reproduce and fix this.

**Comment by bengotow** [comment] 2015-12-28 19:27
This is fixed in `acd960d611c050ec3af9f9e480b7fc7ee5ea7ff3`—I think it's actually safe for us to allow CSS from any domain to be loaded into emails.

**Closed by bengotow** 2015-12-28 19:27 UTC
Labels: bug
