### ISSUE TITLE
Wrong Merging e-mails

### ISSUE THREAD

**Issue by rica-benhossi** [nylas/N1#2129] opened 2016-05-04 17:40 UTC
N1 is joining different emails with the same subject and sender as if they were a conversation. It is a problem because, although the message has the same subject and sender, it can have different content, which means that they are not a conversation. For exemple, if someone sends me 2 different emails with the subject "ERROR", N1 groups it in one message, like it was a conversation. Although the subject and the sender are de the same, these e-mails are 2 different things.

##### Are there any related issues?

...

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.32
--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only have a Gmail account

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes, with every mail with the same subject.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Gmail webmail

**Comment by grinich** [comment] 2016-05-04 18:00
Are they threaded together in the Gmail web UI?

**Comment by rica-benhossi** [comment] 2016-05-06 17:37
I was trying to simulate the problem when I realized that Gmail Web also does that, according to the Conversation View parameter. My mail had this feature on. So I've turned it off in order to testing, and after this, Gmail wasn't threading my mails anymore... However, N1 is putting mails with the same subject and sender together. I think that is correct when the messages is send forward or (fw:) and replied (re:). Otherwise, if the message is a new one, even though the sender and the subject are the same, N1 should treat this a different message, and not group it with the other ones.
Although, assuming that Gmail was doing this according to Conversation View, It's not a problema at all. But would be great if N1 could have some feature like that.

Thanks for the quick answer and sorry for my delay to replay that...

**Comment by bengotow** [comment] 2016-05-06 17:44
Hi @rica-benhossi — thanks for the reply! It sounds like this may be a duplicate of #439. Unfortunately, N1 is really designed for threaded conversation viewing, but if there's enough interest we may consider changing it some day. Cheers!

**Closed by bengotow** 2016-05-06 17:44 UTC
