### ISSUE TITLE
App threw an error when running [TypeError: Cannot read property 'getVersion' of undefined]

### ISSUE THREAD

**Issue by handicraftsman** [nylas/N1#1415] opened 2016-02-25 14:47 UTC
````
ancient@NickolayPC:~/N1$ ./N1.sh --dev
App threw an error when running [TypeError: Cannot read property 'getVersion' of undefined]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'getVersion' of undefined
    at parseCommandLine (/home/ancient/N1/src/browser/main.js:107:18)
    at start (/home/ancient/N1/src/browser/main.js:17:12)
    at Object.<anonymous> (/home/ancient/N1/src/browser/main.js:148:3)
    at Object.<anonymous> (/home/ancient/N1/src/browser/main.js:150:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/home/ancient/N1/electron/resources/default_app/main.js:258:23)
    at Module._compile (module.js:425:26)
^Cancient@NickolayPC:~/N1$ 
````
Just compiled and started. 

Output of `uname -a` command:
````
Linux NickolayPC 4.3.0-1-686-pae #1 SMP Debian 4.3.3-7 (2016-01-19) i686 GNU/Linux
````

Output of `lsb_release -a` command:
````
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux stable-updates (sid)
Release:	stable-updates
Codename:	sid
````

**Comment by handicraftsman** [comment] 2016-02-25 14:48
Output of `nodejs --version` command:
````
v4.2.5
````
Output of `npm --version` command:
````
1.4.21
````

**Comment by handicraftsman** [comment] 2016-02-25 14:49
Output of `coffee --version` command:
````
CoffeeScript version 1.10.0
````

**Comment by spetz83** [comment] 2016-02-25 14:50
That looks gross. You should consider changing the title of your issue to something more descriptive though. Maybe this "App threw an error when running [TypeError: Cannot read property 'getVersion' of undefined]"

**Comment by mbilker** [comment] 2016-02-25 16:19
Dupe of #1399

**Closed by mbilker** 2016-02-25 16:19 UTC
