### ISSUE TITLE
Opening specific e-mail crashes N1

### ISSUE THREAD

**Issue by federicoiosue** [nylas/N1#1540] opened 2016-03-02 10:04 UTC
**OS**: Linux Manjaro

**N1 version**: 0.4.10

**Bug description**:  Opening an e-mail containing an access request to a shared Google Drive folder causes the application crash and recursively start again.

**Steps to reproduce**:
 1. Open Google Drive
 2. Select  folder and: Share->Andvanced->Copy the link on top. This link should be only for collaborators, to trigger the access request on the next step
 3. Using browser's Incognito Mode or being logged out from the previous Google account try to access to the link above
 4. Request access to that shared folder as shown in the following picture:
![selezione_074](https://cloud.githubusercontent.com/assets/487104/13456775/0f2803e8-e065-11e5-9e90-d64237241643.png)
 5. The e-mail sent to the first account is the one causing me N1's crash.

I've performed some tests by permuting accounts and folders but the result is always the same.
Opening the same e-mail using another client (Geary or Google Inbox) works without issues.

**Comment by bashok001** [comment] 2016-03-02 18:48
Not able to reproduce this. I just saw had a request access email.

**Comment by bengotow** [comment] 2016-03-11 19:45
Hey! I've finally been able to reproduce this with a specific email. It appears that Autolinker (a library we use which takes things that look like links and makes them clickable) is getting stuck in an infinite loop. I consider this to be a serious bug, and we're looking to move away from Autolinker entirely because it's been the source of other issues as well. (And it actually uses regex to parse HTML...) Stay tuned.

**Comment by federicoiosue** [comment] 2016-03-11 20:10
Great thanks!

  

It's still happening to me whenever someone ask for Google Drive folder
sharing access.

  
![](https://link.nylas.com/open/7vjrx0c0tcxineb9xy9cu8dii/3ee6f27805d245fabd38
d0d6e87e6fa1)

> On Mar 11 2016, at 8:46 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hey! I've finally been able to reproduce this with a specific email. It
appears that Autolinker (a library we use which takes things that look like
links and makes them clickable) is getting stuck in an infinite loop. I
consider this to be a serious bug, and we're looking to move away from
Autolinker entirely because it's been the source of other issues as well. (And
it actually uses regex to parse HTML...) Stay tuned.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1540#issuecomment-195518834).![](https://github.com/notifications/bea
con/AAduwBZI4fpDKqLuDkZEtrnRYexSj0nDks5pscaAgaJpZM4HnSSM.gif)

**Comment by bengotow** [comment] 2016-03-14 19:32
I think this will be resolved in the next release now that we have removed `autolinker`. Stay tuned!

**Comment by bengotow** [comment] 2016-03-25 23:43
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!

**Closed by bengotow** 2016-03-25 23:43 UTC
Labels: bug, done-pending-release
