### ISSUE TITLE
Filter only the unread emails

### ISSUE THREAD

**Issue by MpStyle** [nylas/N1#266] opened 2015-10-29 10:22 UTC
How can I filter (or search) the unread emails?

**Comment by axllent** [comment] 2015-11-01 01:47
If you are linked to Gmail, you can search for "is:unread" as I pointed out in #327, but that isn't a solution, just a work-around.

**Comment by bengotow** [comment] 2016-01-06 00:47
Thanks—definitely on the roadmap. Closing as a duplicate of #200.

**Closed by bengotow** 2016-01-06 00:47 UTC
