### ISSUE TITLE
Google Sign In doesnt work for me

### ISSUE THREAD

**Issue by delixyr** [nylas/N1#2044] opened 2016-04-24 05:05 UTC
##### Are there any related issues?
Couldnt find any!
...

##### What operating system are you using?
Windows 10 x64 Insider preview latest build 14316

##### What version of N1 are you using?
0.4.25
--

**Bug?**
##### Do you have any third-party plugins installed?
none

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
gmail.
When I try to add a gmail account, a splash screen appears "sign into google from your browser" and nothing happens. No browser window opens. It just keep on showing.

...
![untitled](https://cloud.githubusercontent.com/assets/4602841/14765653/2d864e04-0a08-11e6-8afc-e9886dc21981.png)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No
...

**Comment by mbilker** [comment] 2016-04-25 05:29
What browser do you have set as default?

**Comment by delixyr** [comment] 2016-04-25 08:42
![default browser](https://cloud.githubusercontent.com/assets/4602841/14778223/5bef8d5e-0aef-11e6-973b-bc957ba35e46.png)

**Comment by bengotow** [comment] 2016-04-25 15:06
Closing as duplicate of #2044

**Closed by bengotow** 2016-04-25 15:06 UTC
Labels: bug, needs-steps-to-reproduce
