### ISSUE TITLE
Ububntu The package is of bad quality while using prebuilt-deb

### ISSUE THREAD

**Issue by kirtangajjar** [nylas/N1#757] opened 2015-12-18 13:48 UTC
When i installed N1 from recent email about taiga theme, and downloaded the deb file from `http://inbox.cmail20.com/t/d-l-jiuudud-dttufhri-j/`. When i proceeded to install the file, a message showed up saying that package i was installing was bad. Here is the screenshot and details.

http://imgur.com/BfOE0FD
 
```
Lintian check results for /home/kirtan/Downloads/N1.deb:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_IN.ISO8859-1"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
E: nylas: control-file-has-bad-permissions postinst 0775 != 0755
E: nylas: control-file-has-bad-permissions postrm 0775 != 0755
N: Some overrides were ignored, since the tags were marked "non-overridable".
N: Use --verbose for more information.
```

**Comment by mbilker** [comment] 2015-12-18 14:57
Dupe of #710

**Comment by jstejada** [comment] 2015-12-18 22:25
merging into #710

**Closed by jstejada** 2015-12-18 22:25 UTC
