### ISSUE TITLE
Feature Request: Actionable Notifications

### ISSUE THREAD

**Issue by xasos** [nylas/N1#1134] opened 2016-01-25 17:04 UTC
Something akin to Mail.app would be great - allowing customization for two quick actions on a mail notification.

Example:
<img src="http://core0.staticworld.net/images/article/2013/10/mavericks-mail-trustbutnotify-100065896-orig.jpg"></img>

**Comment by mbilker** [comment] 2016-01-25 20:32
Dupe of #840

**Closed by mbilker** 2016-01-25 20:32 UTC
