### ISSUE TITLE
I installed the latest version 0.4.32 yesterday, I realized today that although the send later plugin is activated the software is not able to send mails later. 

### ISSUE THREAD

**Issue by jsamwini** [nylas/N1#2119] opened 2016-05-04 02:11 UTC
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by KevinMartin** [comment] 2016-05-04 02:18
Dupe of #2106

**Comment by bengotow** [comment] 2016-05-04 06:54
Closing as dup of #2106 - this will be fixed in a patch tomorrow morning!

**Closed by bengotow** 2016-05-04 06:54 UTC
