### ISSUE TITLE
Feature Request: Change password UI

### ISSUE THREAD

**Issue by mpcabd** [nylas/N1#1810] opened 2016-03-22 11:14 UTC
**Feature Request**

When my work email password expired I had to remove my account and add it again, Nylas didn't show an error that my password is no longer valid, and didn't have any UI that will allow me to change it.

**Comment by YuriSolovyov** [comment] 2016-03-22 17:50
I think this is tracked at #1019

**Comment by bengotow** [comment] 2016-03-22 17:57
Closing as duplicate of #1019

**Closed by bengotow** 2016-03-22 17:57 UTC
