### ISSUE TITLE
Reset size of letters list panel

### ISSUE THREAD

**Issue by Chuckland** [nylas/N1#243] opened 2015-10-28 05:01 UTC
How to replicate:
1. Open any list, e.g. Inbox
2. Change letters list width
3. Go to Drafts
4. Return to Inbox
5. List width is reset

Screencast: http://quick.as/d8doI3kd7

N1 Version 0.3.19-de7d1bb (0.3.19-de7d1bb)

**Comment by bengotow** [comment] 2015-11-24 06:48
Merging as a duplicate of 97

**Closed by bengotow** 2015-11-24 06:48 UTC

**Comment by jstejada** [comment] 2015-12-25 17:48
merging into #833
