### ISSUE TITLE
Some messages get stuck in the "unread" state

### ISSUE THREAD

**Issue by louim** [nylas/N1#539] opened 2015-12-02 00:24 UTC
Hello!

it seems like sometimes, after clicking on a message to read it and coming back to the inbox will not mark the message as "read". No matter how many time I keep going back to the message and back to the inbox, it will stay "unread". I'm not 100% sure, but it seems to happen more when the message is a long thread with many messages collapsed.

In any case, clicking ob the "Mark as read button" works.

**Comment by matthewbassett** [comment] 2015-12-03 05:38
Hi,
Just to add a bit of information in this one... I believe I am having the same issue as @louim. My messages are marking as read in the inbox without any issue, however the unread badge for inbox just keeps going up, I mark as read but the number does not change. On the server side there is no issue (All emails marked as read are), so the problem is only a cosmetic one I believe.

Email type: Exchange (My gmail is working fine with no issues)
Nylas Version: 0.3.26-c1ce330

**Comment by jstejada** [comment] 2015-12-03 21:18
hey guys, thanks for reporting this. I'm merging this into #489

**Closed by jstejada** 2015-12-03 21:18 UTC

**Comment by louim** [comment] 2015-12-03 21:23
@jstejada, my problem is not the same as @matthewbassett, and not the same that #489. My count of unread message is in sync with the sidebar.

The problem is messages not being marked as read when actually opening them. They stay marked as unread in the sidebar **and** the main listing.

**Comment by matthewbassett** [comment] 2015-12-14 03:33
Issue is fixed with the new update. Thanks for your quick bug fixes (:
