### ISSUE TITLE
Unable to CC or BCC!

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2033] opened 2016-04-22 15:37 UTC
##### Are there any related issues? No

...

##### What operating system are you using? 10.11.4
...

##### What version of N1 are you using?  0.4.25-a22631a 

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? No
![ss1](https://cloud.githubusercontent.com/assets/16170272/14746595/90292bea-086d-11e6-97cb-f6e0e41d3173.jpg) 
  

![ss2](https://cloud.githubusercontent.com/assets/16170272/14746606/a1ca333a-086d-11e6-966e-7183cab52827.jpg)

...

**Comment by oldhickory30** [comment] 2016-04-22 15:44
Every since the last update I have been unable to Bcc or CC messages, when I click on either mail option the window collapses making impossible to add a recipient to the CC or Bcc section. I am told this is a Gmail feature however I am not using Gmail! I know of one other person having the same problem. I have been using Nylas from day one but this glitch has made Nylas completely unusable! Have been in contact with Nylas direst but they have been unable to offer a fix or offer any suggestions! I even uninstalled and re-stalled Nylas again to no avail! Are my day with Nylass over?

**Comment by bengotow** [comment] 2016-04-22 17:55
Hey @oldhickory30 — thanks for filing this. Are you trying to click the "Cc", "Bcc" buttons on the far right? Also do you know what theme you're using? This could be theme related.

**Comment by bengotow** [comment] 2016-04-22 17:58
Hey—looks like it's not the theme. If you don't mind, could you choose Apple > About this Mac from the system menu and post a screenshot of this window? I think it's possible that this is caused by N1 not running fast enough on your machine.

![image](https://cloud.githubusercontent.com/assets/1037212/14750325/1082a87e-0879-11e6-8923-d2f41b3f1bb7.png)

**Comment by oldhickory30** [comment] 2016-04-22 17:59
Yes I am clicking on the cc and Bcc buttons just like I’ve always done but then it collapses the window.
Right now I’m using the light theme however I have tried them all thinking the same thing however doesn’t appear to be the case.
Again it stated immediately after installing the last update.



On April 22, 2016 at 11:55:24 AM, Ben Gotow (notifications@github.com) wrote:

Hey @oldhickory30 — thanks for filing this. Are you trying to click the "Cc", "Bcc" buttons on the far right? Also do you know what theme you're using? This could be theme related.

**Comment by oldhickory30** [comment] 2016-04-22 21:11
I'm using the light theme however tried all with no success and yes I'm clicking on Bcc and cc to no avail!

**Comment by oldhickory30** [comment] 2016-04-22 21:17
![specs](https://cloud.githubusercontent.com/assets/16170272/14755137/456f9b04-089d-11e6-95fc-a2cde628d71a.jpg) Pretty confident that my machine is more then fast enough however here you go Ben.

**Comment by oldhickory30** [comment] 2016-04-25 18:14
Any further suggestions? I'd really like to go back using Nylas!

**Comment by bengotow** [comment] 2016-05-03 15:32
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!

**Closed by bengotow** 2016-05-03 15:32 UTC
Labels: bug, done-pending-release

**Comment by oldhickory30** [comment] 2016-05-03 15:36
Yep, still an issue and unusable, I have to click on bcc twice to get that option and cc will not open at all.

**Comment by oldhickory30** [comment] 2016-05-03 17:06
With this morning release of the latest update, bcc and cc is still messed up and acting unstable. Back to my old client, hopefully someday it will be resolved.

**Comment by oldhickory30** [comment] 2016-05-03 21:15
The bcc and cc have completely stopped working again!

On May 3 2016, at 9:33 am, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey—a fix for this issue shipped in 0.4.32. You can grab the update from the
Releases page, and it should hit the auto-updaters today. Feel free to re-open
if you still have trouble!

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/2033#issuecomment-216567692)![](https://github.com/notifications/beac
on/APa9IEKxw64Mju8Yw-nlhr3q4A14g_Myks5p92q4gaJpZM4INuh0.gif)

**Comment by passingnotes** [comment] 2017-04-19 18:17
this is happening again, april 19th 2017 right after release of Nylas 2.0 - tried a couple of themes, seems one must forcefully doubleclick the cc/bcc items to display fields
