### ISSUE TITLE
App is not launched.

### ISSUE THREAD

**Issue by akovalyov** [nylas/N1#2424] opened 2016-06-13 15:44 UTC
I'm using Linux Mint 17.

After reboot I realized that the app is not launched anymore.
Nylas version is 

```
$ nylas -v
0.4.40-85cf726
```

I have upgraded from 0.4.35 or so (don't really remember).
No third-parties installed, only some of standard plugins are activated.

I don't believe that it is related to email accounts, but just in case - two gmail ones and one regular smtp.

I will try to roll back the version.  

Here is the log

```
$ cat /tmp/Nylas-N1-4820.log 
{"host":"andrew-N501JW","timestamp":"2016-06-13T15:34:00.403Z","payload":"TypeError: Cannot read property 'core' of undefined\n    at Function.plus.setValueForKeyPath (/usr/share/nylas/resources/app.asar/src/config-utils.js:95:19)\n    at ConfigPersistenceManager.setRawValue (/usr/share/nylas/resources/app.asar/src/browser/config-persistence-manager.js:54:11)\n    at Config.module.exports.Config.setRawValue (/usr/share/nylas/resources/app.asar/src/config.js:412:36)\n    at Config.module.exports.Config.set (/usr/share/nylas/resources/app.asar/src/config.js:159:12)\n    at Config.module.exports.Config.pushAtKeyPath (/usr/share/nylas/resources/app.asar/src/config.js:200:12)\n    at Application.temporaryInitializeDisabledPackages (/usr/share/nylas/resources/app.asar/src/browser/application.js:169:19)\n    at Application.start (/usr/share/nylas/resources/app.asar/src/browser/application.js:98:10)\n    at EventEmitter.app.on (/usr/share/nylas/resources/app.asar/src/browser/main.js:168:24)\n    at emitOne (events.js:95:20)\n    at EventEmitter.emit (events.js:182:7)"}
{"host":"andrew-N501JW","timestamp":"2016-06-13T15:34:00.408Z","payload":"ErrorReporter: Shipping Logs. Exception occurred\n"}
{"host":"andrew-N501JW","timestamp":"2016-06-13T15:34:00.409Z","payload":"/usr/share/nylas/resources/app.asar/src/nylas-private-ship-logs-task\n"}
{"host":"andrew-N501JW","timestamp":"2016-06-13T15:34:00.703Z","payload":"[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()\n"}
{"host":"andrew-N501JW","timestamp":"2016-06-13T15:34:00.711Z","payload":"Running log ship: /tmp, Nylas-N1-4820[.0-9]*.log$\n"}
{"host":"andrew-N501JW","timestamp":"2016-06-13T15:34:01.653Z","payload":"Error uploading /tmp/Nylas-N1-4820.log: status code 204\n"}
{"host":"andrew-N501JW","timestamp":"2016-06-13T15:34:01.653Z","payload":"ErrorReporter: Shipped Logs.\n"}
```

Feel free to close it if it is duplicate or not relevant anymore.

**Comment by khandieyea** [comment] 2016-06-15 02:24
I also have the same problem "Cannot read property 'core' of undefined"

```
$ nylas -v
0.4.45-7637265
```

**Comment by bengotow** [comment] 2016-06-15 17:23
Hey! Thanks for filing this and confirming that it's an issue with the very latest 0.4.45 release. 

Can you take a look at the config file at `~/.nylas/config.json`? It should look something like this, but it sounds like your copy is missing the "core" section. You may be able to resolve the problem by adding a totally empty entry (`"core":{}`}, which the app will then populate. If that doesn't work, I'd recommend deleting ~/.nylas/config.json entirely. You'll need to re-connect each of email accounts.

```
{
  "*": {
    "env": "production",
    "core": {
      "themes": [
        "ui-light"
      ],
      ....
```

Thanks—this is really strange...

**Comment by akovalyov** [comment] 2016-06-15 17:39
@bengotow I've downgraded to `0.4.38-27d21d1`.  I can upgrade once again and try to reproduce/fix that behaviour, if it helps you. 
Just to be sure - if I back up `~/.nylas/config.json` and if everything goes wrong - will simple restoring of that file restore all the configuration of email accounts? Or should I backup anything else?

**Comment by khandieyea** [comment] 2016-06-15 21:40
@bengotow @akovalyov After downgrading back to 0.4.38, and re-upgrading to 0.4.45-7637265 , all systems are go

**Comment by huwd** [comment] 2016-06-17 13:15
I can confirm I have had this issue too:
Ubuntu 16.04:
```
~ nylas -v
0.4.45-7637265
```
~/.nylas/config.json only contained `{}`

changing it to `"core":{}` threw a "Failed to load "config.json" error, which had a reset configuration button - and now N1 launches.

**Comment by bengotow** [comment] 2016-07-20 21:37
Hey folks—going ahead and closing this since it sounds like original issue was resolved.

**Closed by bengotow** 2016-07-20 21:37 UTC
Labels: bug
