### ISSUE TITLE
Multiple drafts when writing reply

### ISSUE THREAD

**Issue by mitjafelicijan** [nylas/N1#284] opened 2015-10-29 21:10 UTC
When I try to reply draft is created. A couple of times there were two drafts created for the same reply. And when I send email draft still exists. I opened gmail webclient to make sure that this is only sync problem but draft message was not deleted after sending it even on gmail webclient.

**Comment by justinsincl** [comment] 2015-11-02 20:40
I'm seeing the same issue.

Write a reply in Nylas >> Send >> Look at Gmail web view >> See sent item in thread and a draft item in thread.

**Comment by cacyss0807** [comment] 2015-11-12 16:18
I am having the same problem. In my case it disappeared when I did **not** started writing a response using the template plug-in. So my guess is that this problem is due to the template plug in.

**Comment by grinich** [comment] 2016-01-08 02:05
This should be fixed now. Please re-open if you have steps to reproduce.

**Closed by grinich** 2016-01-08 02:05 UTC

**Comment by yuna-adelieweb** [comment] 2016-06-23 17:03
I have the latest Nylas N1 version but whenever I write anything it saves multiple drafts per minute before I'm finished. I know it's auto-saving but this never happened before the latest update. I finished writing a lengthy email and had 506 drafts. Please help! I love[d] Nylas but I depend on drafts for a lot of the emails I write and this is reason enough for me to have to look for a different program to handle emails. Thank you so much.
