### ISSUE TITLE
Minor UI Bugs

### ISSUE THREAD

**Issue by Ehesp** [nylas/N1#90] opened 2015-10-14 07:54 UTC
*First hover doesn't show a tooltip*

1) Move your mouse over the "Archive" icon - no tooltip appears.
2) Move your mouse along to the "Mark as Unread" icon - a tooltip appears.
3) Move your mouse back to the "Archive" icon - the tooltip now appears for this.

*Icon active flash*

1) Click the "Toggle Sidebar" button (top right).
2) When it goes from "inactive" to "active", the "Apply Labels" icon goes active for a very short period of time (turns blue) and flashes back to normal again.

**Comment by bengotow** [comment] 2015-10-14 17:14
Hey @Ehesp,

Thanks for reporting these! The first one is—for better or worse—intended behavior. On Mac OS X, tooltips take a while to appear the first time, and then appear instantly as you scroll over buttons. You're not the first person who's been thrown off by that behavior though—we might consider changing it, especially on other platforms. (Here's a video of the intended behavior: http://imgur.com/qXVFmLH)

The active icon flashing is definitely an issue—I'm going to look into that one today and I'll let you know if we can assemble a fix.

**Comment by Ehesp** [comment] 2015-10-15 15:33
Ah so it is, never actually noticed that to be honest but just seemed to notice it here as I wasn't sure what a couple of the icons did.

With point 2, good stuff - not a biggy though.

Also, when using the dark scheme, the message body text is still black here:

![image](https://cloud.githubusercontent.com/assets/842078/10518577/069af0aa-735a-11e5-8866-43fad83bf6f2.png)

Changing the `inbox-html-wrapper` to force a color `color: #c2c2c2;` works fine for all of my inbox items.

Also the same here in the GitHub plugin sidebar:

![image](https://cloud.githubusercontent.com/assets/842078/10518671/66b19da4-735a-11e5-87a2-daf490b359ff.png)

**Comment by grinich** [comment] 2015-10-23 22:12
closing ads dupe of https://github.com/nylas/N1/issues/145

**Closed by grinich** 2015-10-23 22:12 UTC
