### ISSUE TITLE
N1 for mac OS X: Dark theme support

### ISSUE THREAD

**Issue by mataal** [nylas/N1#422] opened 2015-11-18 09:22 UTC
I have the dark theme enabled for my mac (El Capitan V10.11.1).

The status menu for N1 in the dark theme is not visible (font colour needs to be changed when in dark theme?) 

A quick video of this behaviour is available https://www.dropbox.com/s/pq5k3ebvcai8jnc/N1%20dark%20theme.mov?dl=0

**Comment by jstejada** [comment] 2015-11-18 17:58
hey @mataal thanks for reporting. I'm closing this as a duplicate of #416

**Closed** 2015-11-18 17:58 UTC
