### ISSUE TITLE
Messages that have the Trash "label" shouldn't show in other labels

### ISSUE THREAD

**Issue by hirozed** [nylas/N1#795] opened 2015-12-21 17:05 UTC
I'm noticing that emails that have been marked with the Trash label are showing in the Important, All Mail, etc. labels as well.  I believe that anything that is in the trash should only show in the trash, no matter if they have the important label attached as well.

**Comment by grinich** [comment] 2016-01-25 23:25
dupe of #1135

**Closed by grinich** 2016-01-25 23:25 UTC
