### ISSUE TITLE
Unread account doesn't update immediately after archiving an email

### ISSUE THREAD

**Issue by iBeliever** [nylas/N1#142] opened 2015-10-22 20:42 UTC
After I archive an email in N1, it takes a couple of seconds before the unread badge in the mailboxes list and on the dock icon (I'm on a Mac) updates or goes away. If it matters, I'm connected to a Gmail account.

**Comment by bengotow** [comment] 2015-10-22 21:20
Hey—thanks for reporting this. This is actually a known issue caused by us debouncing an expensive `SELECT COUNT(*)....` under the hood. We're moving to a new model where we'll update counts without re-running queries, and that should fix it. Stay tuned!

**Comment by bengotow** [comment] 2015-11-24 06:37
Hi @iBeliever — this landed today in b2f8b34a32d87f59c13a77d3a3d74cf5ca4c715b and will be included in the next release. Thanks for the report!

**Closed by bengotow** 2015-11-24 06:37 UTC
Labels: enhancement
