### ISSUE TITLE
Opening developer tools makes N1 un-moveable

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#529] opened 2015-12-01 17:37 UTC
When we toggle developer tools to open, N1 wont respond to drag and drop and stays stuck in one place.

**Comment by bengotow** [comment] 2015-12-01 18:54
Hey @bashok001 — this appears to be a regression in Electron. I've filed an issue with them here: https://github.com/atom/electron/issues/3647

**Comment by jackiehluo** [comment] 2016-07-29 00:50
Closing this issue for now since it should be fixed—let us know if it's not!

**Closed by jackiehluo** 2016-07-29 00:50 UTC
Labels: blocked-on-electron
