### ISSUE TITLE
Option to disable tray

### ISSUE THREAD

**Issue by Lowseling** [nylas/N1#594] opened 2015-12-06 22:10 UTC
Hi all,

Will you ever add an option to disable system tray icon? I think that the system tray icon is a good idea, but I personally don't need it and I think that an option to enable/disable the system tray icon can be good for other users that don't need it :)

Loving N1 by the way,
Good work!

**Comment by jstejada** [comment] 2015-12-07 01:13
Hi @Lowseling what OS are you using? there is an option under Preferences - > Workspace

**Comment by Lowseling** [comment] 2015-12-07 17:02
@jstejada I'm on ArchLinux, but I don't see the option under Workspace

**Comment by grinich** [comment] 2015-12-12 21:06
marking as bug because we actually have this feature i think

**Comment by jstejada** [comment] 2015-12-12 21:19
hey guys! so this was initally by design because we considered that the system tray icon should always be present on Linux and Windows, but we'll add the option to hide it in those platforms too!

**Closed** 2015-12-21 05:33 UTC
Labels: enhancement, platform-linux
