### ISSUE TITLE
Accents in portuguese characters not displaying properly in composer

### ISSUE THREAD

**Issue by luispaulobio** [nylas/N1#2384] opened 2016-06-06 14:25 UTC
Ex. The following sentence: Olá. Querido amigo, como você está seu coração?

In the composer results in:
![captura de tela de 2016-06-06 10-31-26](https://cloud.githubusercontent.com/assets/19779507/15825024/16dcd6ca-2bd0-11e6-876a-c40bb56ea308.png)

I' m using:
Ubuntu 16.04 LTS (language and keyboard > PT-BR)
Nylas N1 version: 0.4.40.-85cf726
E-mails services: @gmail.com, @hotmail.com and @yahoo.com.br (bug in all)

**Comment by bengotow** [comment] 2016-06-06 18:11
Hi - can you try upgrading to N1 0.4.44?

**Comment by bengotow** [comment] 2016-06-06 18:17
(Sorry! 0.4.44 is still in testing—stay tuned :-))

**Comment by albertocg** [comment] 2016-09-10 18:25
Tried to reproduce just in case and didn't seem to happen.
![screenshot from 2016-09-10 13-24-19](https://cloud.githubusercontent.com/assets/5740892/18412657/1903485a-775a-11e6-86a3-f40b8d0c2d28.png)

**Comment by jackiehluo** [comment] 2016-10-01 06:45
Closing since it looks like this issue is resolved!

**Closed by jackiehluo** 2016-10-01 06:45 UTC
Labels: linux
