### ISSUE TITLE
Drafts appear multiple times -- Duplicate drafts

### ISSUE THREAD

**Issue by awmartin** [nylas/N1#933] opened 2016-01-08 16:18 UTC
Drafts (in this case, authored in the Gmail interface and synced to N1) sometimes appear multiple times. After the first sync of a new draft, it seems all that one needs to do to reproduce this is to wait. Often another copy of the draft will appear will no further user interaction.

<img width="721" alt="screen shot 2016-01-08 at 11 11 04 am" src="https://cloud.githubusercontent.com/assets/57281/12202668/0121635c-b5f9-11e5-8c8b-0157c2ab2326.png">

**Comment by danielbayley** [comment] 2016-02-05 16:13
+1. They appear _many_ multiple times for me (using iCloud mail).

**Comment by Michael-A-D** [comment] 2016-02-16 20:32
I have experienced that too, it seems that what happen is that the first draft is synced, then somehow on gmail side (in my case), it is either replaced by an updated draft or sent. In both cases, the old draft won't be removed from the synced version of the draft folder, the new one or the sent message will be synced, and the message will appear two (then more) times in the conversation.

**Comment by danielbayley** [comment] 2016-02-18 19:22
This is really getting out of control for me. It makes N1 almost unusable. Dozens of drafts show up for every email I send.

I also use [N1-Markdown-Composer](https://github.com/nylas/N1-Markdown-Composer), which crushes all the content into one big wall of text, making matters worse!

**Comment by bartlomn** [comment] 2016-02-18 19:39
+1. Initially I thought it is related to #869. Multiple drafts lingering for every email I send from N1 interface. Have to manually clear those up from gmail UI at the end of business day,
This makes version 0.4.5-b0ec335 quite tricky to use.

**Comment by orky** [comment] 2016-02-18 22:59
+1 I have to change my whole workflow to only compose mails I am ready to send. Drafts continue to stay in the thread as well even after they are sent. That might be one of the underlying issues.

**Comment by danielbayley** [comment] 2016-03-02 17:40
It really is out of control, literally hundreds of drafts for one lengthy email. Even if I compose it in Apple Mail and not in N1, the problem is still there (information that I hope will help…)

**Comment by awmartin** [comment] 2016-03-02 17:44
It's a deal-breaker for me. I can't trust which draft is being authored or sent. I haven't used N1 seriously in weeks because of this.

I do remember a console message appearing regarding an invalid or absent id for the message. I will take a look again.

It would be nice to either have someone look at this or to provide direction so someone else can attempt a fix.

**Comment by bengotow** [comment] 2016-03-03 02:11
Hey folks—I've been debugging this all day and it looks like there are a few separate bugs contributing to this. These are really serious issues and they should be fixed in the next release. Here's a quick rundown:

- When the Sync Engine failed to save changes to a draft (due to an intermittent connection issue usually), a bug in http://www.proxysql.com/ caused the database transaction to be committed instead of rolled back. This caused many, many copies of the message to appear in N1. These messages were not actually sent, would not appear in Gmail / Outlook.com, etc. We've worked with the author of ProxySql to fix this bug and it should be fixed in our production environment by the end of the week.

- We autosave messages as you compose them, and there was an edge case where an autosave could start before but finish /after/ you sent the message. This isn't harmful, but caused the draft to be re-saved to the local cache after it was deleted. A fix for this is in review and should be on master tomorrow.

Sorry for the hassle folks—I appreciate all the debug info and feedback. Stay tuned—

**Comment by johnchourajr** [comment] 2016-03-04 16:55
Same issue for me.

**Comment by bartlomn** [comment] 2016-03-04 17:10
It actually got much better for me after last update. Now I am running on Version 0.4.10-4e3595b, and the issue rarely (if ever) shows up.

**Comment by arpitchauhan** [comment] 2016-03-09 15:25
I use 0.4.10 on Windows, and I face the same issue.

**Comment by bengotow** [comment] 2016-03-12 03:41
Hey folks! Thanks for filing this. We've made a lot of changes in 0.4.14 to resolve this issue. If you continue having this problem after you upgrade, feel free to re-open or file another issue.

**Closed by bengotow** 2016-03-12 03:41 UTC

**Comment by rmmls** [comment] 2016-03-15 08:05
Hi, 

The issue still appears.
I use outlook.com account and N1 is duplicating my email messages after send

**Comment by sbingram** [comment] 2016-06-24 17:00
I'm having a problem too. I just loaded N1 for the first time and Drafts seems out of control on one message. It's up to 136  and counting. I went in to old style email client and deleted the drafts and that seemed to make it worse. They seem to even be replicating in Trash. Had to shut it down. I'm using 0.4.45-7637265 on Mac.

**Comment by sbingram** [comment] 2016-06-24 17:32
Follow up to above post. I went into classic email client and removed all of the mess including the ones in Trash. Then I started N1 again and went away for some time. When I came back everything was good. I guess once the loop was stopped, the program did eventually fix everything included the treaded trash message.

**Comment by alastairstone** [comment] 2016-07-12 09:47
Getting this problem too, is it related to this in anyway? http://www.macobserver.com/tmo/answers/how_to_configure_apple_mail_to_avoid_duplicate_drafts_with_gmail

**Comment by originalgeneous** [comment] 2016-07-17 00:18
Same problem. I see 120 duplicate drafts on one email. Interesting that such an old bug is still around.

**Comment by arpit10i** [comment] 2016-07-17 00:21
@originalgeneous I have experienced similar issue with Outlook 2016 on Windows, when using Gmail. So it might be Gmail that's at fault.

**Comment by originalgeneous** [comment] 2016-07-17 00:23
@arpitchauhan doesn't happen with Mac Mail or Mac Airmail.
