### ISSUE TITLE
Spam appears in Sent Items

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#409] opened 2015-11-16 05:20 UTC
When I browsed through the Gmail folders in N1, I noticed Spam messages in Sent Items. I believe they are present there because the From header is set to my email address. The Gmail Web Client correctly discards the messages from Sent Items.

![2015-11-16-001956_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11174813/cd4875aa-8bf7-11e5-9baf-9081478a23ba.png)

EDIT: Yes there is personal information present. I haven't found a decent Linux photo editing program that isn't GIMP (thinking about it, I probably should relearn GIMP...)

**Comment by bengotow** [comment] 2015-11-21 02:22
Hey @mbilker — It looks like Gmail is probably including those threads in the `Sent Mail` IMAP folder, even though you don't see them in Gmail's web interface. Can you try using another third-party email client (like Mail on iOS, or Thunderbird), and see if you see these items in your Sent Mail? We could always manually remove them when we query for the Sent Mail folder, but it'd be a little tricky.

**Comment by mbilker** [comment] 2015-11-21 03:55
Thunderbird has a separate Spam tab and the spam messages do not appear in the `Sent Mail` tab in Thunderbird. Most of the spam I get appears in the spam tab in N1, but the spam in the Sent Mail tab has a Spam label associated with it.

**Comment by grinich** [comment] 2016-01-25 23:25
dupe of #1135

**Closed by grinich** 2016-01-25 23:25 UTC
Labels: mail-sync
