### ISSUE TITLE
UI doesn't show which inbox/account is active

### ISSUE THREAD

**Issue by ismith** [nylas/N1#433] opened 2015-11-19 21:13 UTC
I'm looking at the dropdown where I can pick [redacted1]@gmail.com, [redacted2]@other.org, etc, and while it works to switch which inbox's contents are displayed, if I'm not clicking on it, it always just shows the same email address.

Likewise, when I use apple-1, apple-2, ... to switch active inboxes, it doesn't change the UI to say which inbox is currently active.

LMK if this description is unclear, I can take & redact screenshots.

**Comment by jstejada** [comment] 2015-11-20 00:03
Hey @ismith, this is definitely unexpected behavior and we can't seem to replicate.How long are your email addresses? Could you provide system logs from the Console app and a screenshot if possible?
Thanks!

**Comment by ismith** [comment] 2015-11-20 00:11
Definitely - will upload when I have time to redact.  In the meantime they're 18, 20, and 24 characters.

**Comment by bengotow** [comment] 2015-11-20 00:27
Might be related to https://github.com/nylas/N1/issues/212?

**Comment by MaestroDarius** [comment] 2015-11-24 12:54
It's more like the first comment to the #212 thread belongs to this thread. #212 is just a suggestion of UI customization, not an issue, like this one is.

I'm having this same issue. When switching accounts with the ⌘+1/⌘+2 commands AND when switching by clicking on them with the mouse. It just stays stuck showing as the current account the one that was active when opening the client. It DOES switch between accounts alright (all the labels change and the current inbox, the issue is just it doesn't update the account in the "account switcher" to reflect this change.

**Comment by jmotlong** [comment] 2015-11-24 16:22
I'm experiencing the same issue. I also have 3 gmail accounts. Didn't have the problem when I was only using with 2 accounts. I then installed the 3rd and also installed the Social Profiles and Rules plugins and encountered this issue, but it didn't go away when I undid those actions, so it may be unrelated... Lengths of the account names (email addresses) are 18, 20 & 23.

**Comment by jstejada** [comment] 2015-11-24 17:42
Thanks guys, we are going to look into this. We are trying to replicate this, could you provide system logs from the Console app and a screenshot if possible?
Thanks!

**Comment by alfredxing** [comment] 2015-11-24 21:36
I just downloaded the app, and I'm seeing the same thing.

Here's a screencast of the issue (with lots of information blanked out via developer console): http://gfycat.com/GraveBruisedAnteater

I also get these errors from the JS console:
```
Uncaught ReferenceError: nylasEnv is not definedAnalyticsStore.identify @ analytics-store.js:159(anonymous function) @ analytics-store.js:85module.exports.Publisher.listen.eventHandler @ reflux-coffee.js:199emitOne @ events.js:82emit @ events.js:169trigger @ reflux-coffee.js:211AccountStore.onSelectAccountId @ account-store.js:163__bind @ account-store.js:3module.exports.listen.eventHandler @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/reflux/src/Publish…:36emit @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/reflux/node_module…:72module.exports.trigger @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/reflux/src/Publish…:52module.exports.functor @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/reflux/src/createA…:32AccountSwitcher._onSwitchAccount @ account-switcher.js:224__bind @ account-switcher.js:3AccountSwitcher._renderAccount.React.createElement.onClick @ account-switcher.js:120executeDispatch @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPlu…:110SimpleEventPlugin.executeDispatch @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/SimpleEv…:305forEachEventDispatch @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPlu…:98executeDispatchesInOrder @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPlu…:119executeDispatchesAndRelease @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPlu…:46forEachAccumulated @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/forEachA…:23EventPluginHub.processEventQueue @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPlu…:253runEventQueueInBatch @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEve…:18ReactEventEmitterMixin.handleTopLevel @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEve…:44handleTopLevelImpl @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEve…:80Mixin.perform @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transact…:134ReactDefaultBatchingStrategy.batchedUpdates @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDef…:66batchedUpdates @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpd…:110ReactEventListener.dispatchEvent @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEve…:174
nylas-private-error-reporter.js:92 Uncaught ReferenceError: nylasEnv is not definedmodule.exports.ErrorReporter.getVersion @ nylas-private-error-reporter.js:92module.exports.ErrorReporter.reportError @ nylas-private-error-reporter.js:83module.exports.ErrorReporter.onDidThrowError @ nylas-private-error-reporter.js:48module.exports.bind @ nylas-private-error-reporter.js:30module.exports.ErrorLogger.notifyExtensions @ error-logger.js:162(anonymous function) @ error-logger.js:179module.exports.Emitter.emit @ /Users/alfred/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emit…:86(anonymous function) @ atom.js:292
```

Let me know if you need more information!

/cc @jstejada

**Comment by jstejada** [comment] 2015-11-24 21:45
awesome, thanks @alfredxing, that's really helpful. I'll report back soon

**Comment by mzupan** [comment] 2015-11-25 02:11
I'm seeing the same thing I believe and it looks like the log is the same

```
{"host":"mike-zupan","timestamp":"2015-11-25T02:09:36.795Z","payload":["0: SELECT `Contact`.`data` FROM `Contact`  WHERE `Contact`.`account_id` = 'ccy6ovgpdko34akekln0w02v8'  "]}
{"host":"mike-zupan","timestamp":"2015-11-25T02:09:37.805Z","payload":["0: SELECT `Label`.`data` FROM `Label`  WHERE `Label`.`account_id` = '170djl2t5z0qvf3fxu8mjx9kb'  "]}
{"host":"mike-zupan","timestamp":"2015-11-25T02:09:37.806Z","payload":["0: SELECT `data` FROM `JSONObject` WHERE key = ? LIMIT 1"]}
{"host":"mike-zupan","timestamp":"2015-11-25T02:09:37.817Z","payload":{"stack":"ReferenceError: nylasEnv is not defined\n  at AnalyticsStore.identify (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/nylas-private-analytics/lib/analytics-store.js:165:30)\n  at AnalyticsStore.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/nylas-private-analytics/lib/analytics-store.js:91:24)\n  at EventEmitter.eventHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/modules/reflux-coffee.js:197:27)\n  at emitOne (events.js:82:20)\n  at EventEmitter.emit (events.js:169:7)\n  at AccountStore.trigger (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/modules/reflux-coffee.js:209:30)\n  at AccountStore.onSelectAccountId (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/account-store.js:183:19)\n  at AccountStore.onSelectAccountId (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/account-store.js:18:17)\n  at EventEmitter.eventHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)\n  at EventEmitter.emit (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/reflux/node_modules/eventemitter3/index.js:72:35)\n  at Function.module.exports.trigger (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)\n  at Function.functor (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/reflux/src/createAction.js:32:56)\n  at AccountSwitcher._onSwitchAccount (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/account-sidebar/lib/account-switcher.js:241:15)\n  at AccountSwitcher._onSwitchAccount (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/account-sidebar/lib/account-switcher.js:12:17)\n  at React.createElement.onClick (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/account-sidebar/lib/account-switcher.js:137:26)\n  at Object.executeDispatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110:21)\n  at SimpleEventPlugin.executeDispatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/SimpleEventPlugin.js:305:40)\n  at forEachEventDispatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:98:5)\n  at Object.executeDispatchesInOrder (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:119:3)\n  at executeDispatchesAndRelease (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:46:22)\n  at Array.forEach (native)\n  at forEachAccumulated (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23:9)\n  at Object.EventPluginHub.processEventQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:253:5)\n  at runEventQueueInBatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)\n  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:44:5)\n  at handleTopLevelImpl (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:80:24)\n  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:134:20)\n  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)\n  at Object.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:110:20)\n  at ReactEventListener.dispatchEvent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:174:20)\n","message":"nylasEnv is not defined"}}
```

**Comment by jstejada** [comment] 2015-11-25 22:35
hey guys, we're publishing a fix on the next release, so I'll close this. Check out the changelog!

**Closed by jstejada** 2015-11-25 22:35 UTC
Labels: bug
