### ISSUE TITLE
Reloading uncontrollably on Arch x86_64

### ISSUE THREAD

**Issue by MatFluor** [nylas/N1#1579] opened 2016-03-06 08:45 UTC
Hey there,

I installed N1 from AUR (v.0.4.10-1) and tried to run it.

So far, it once showed me my list of mails, the rest of the time it is reloading constantly.

OS:
- Netrunner rolling (Manjaro base)
- Kernel 4.1.18-2

Other Software (maybe related):
- Atom runs without issues

Effects:
- Showing "Loading N1..." screen
- Trying to render inbox
  - Unlabeled button on the left upper side
  - input field on the right
  - blue bar underneath (I assume that is "set as default mail client" if my eyes were fast enough)
- "Resetting" back to Loading screen

I recorded my screen while this is happening - might be a bit more "visual" instead of the description above ;-)

(I hope this works)
http://i.imgur.com/1KAtG61.gif

Greets,
Mat

**Comment by mbilker** [comment] 2016-03-06 19:26
Could you check your `jounalctl` and `coredumpctl` for any indication of core dumps of the renderer process? There appears to be issues related to font rendering in 0.4.10 because of the Electron version N1 uses.

**Comment by mbilker** [comment] 2016-03-06 19:26
Also dupe of #1529

**Closed by mbilker** 2016-03-06 19:26 UTC
